### ISSUE TITLE
Pagination

### ISSUE THREAD

**Issue by descovi** [sorare/api#1]
Hi, I'm a Ruby on Rails developer, but I'm not an expert of Graphql.
I read the documentation directly on [graphql](https://api.sorare.com/graphql/playground), but I don't understand how I can paginate with _after_ keyword.

I tried this

```
    {
      allCards(first: 3, after: 'b0463b90-bdf7-48ec-9416-587b368fd96b') {
        nodes{
          ... on WithPictureInterface {
              pictureUrl
            }
          id
          player {
            id
            displayName
            slug
          }
        }
      }
    }
```

But the result is always the same.

What I'm doing wrong?

Thanks!

**Comment by Vinedine** [comment]
You need to do something like this;

### Request

```
query { 
  allCards (first:2) {
    edges {
      cursor
      node {
        slug
      }
    }
    pageInfo {
      startCursor
      endCursor
      hasPreviousPage
      hasNextPage
    }
  }
}
```

### Response

```
{
  "data": {
    "allCards": {
      "edges": [
        {
          "cursor": "MQ",
          "node": {
            "slug": "ralf-fahrmann-2020-common-531"
          }
        },
        {
          "cursor": "Mg",
          "node": {
            "slug": "ralf-fahrmann-2020-common-569"
          }
        }
      ],
      "pageInfo": {
        "startCursor": "MQ",
        "endCursor": "Mg",
        "hasPreviousPage": false,
        "hasNextPage": true
      }
    }
  }
}
```
The request returned the first 2 cards.  Then from the response you can use the **endCursor** to get the next in the list;

### Request

```
query { 
  allCards (first:2 after:"Mg") {
    edges {
      cursor
      node {
        slug
      }
    }
    pageInfo {
      startCursor
      endCursor
      hasPreviousPage
      hasNextPage
    }
  }
}
```

### Response

```
{
  "data": {
    "allCards": {
      "edges": [
        {
          "cursor": "Mw",
          "node": {
            "slug": "ralf-fahrmann-2020-common-533"
          }
        },
        {
          "cursor": "NA",
          "node": {
            "slug": "odisseas-vlachodimos-2019-common-68"
          }
        }
      ],
      "pageInfo": {
        "startCursor": "Mw",
        "endCursor": "NA",
        "hasPreviousPage": false,
        "hasNextPage": true
      }
    }
  }
}
```
You can then loop like this until **hasNextPage** is false.

(If you do not include **first** it will get 50 cards)

**Comment by descovi** [comment]
Thanks!

**Comment by jeremoquai** [comment]
@Vinedine hello when I loop I'm blocked (too many API calls I guess) : if I cannot filter in the query itself, and I can retrieve the whole data to filter locally, how can I do ??? Thanks !!!

**Comment by Vinedine** [comment]
Yes that is correct there is a limit on the amount of calls #13 

What exactly are you trying to do? Get all the cards? If so maybe you need to create the slugs via your code and use the Cards query.

**Comment by jeremoquai** [comment]
Hello @Vinedine and thanks again for your time.

I'm "just" trying - as an example - to get all the cards below a given price.

Either I can filter on the price in the query but I haven't been able to find how, or I need to retrieve all the card slugs with their prices (but then I'm blocked because of the too many API calls) and perform the filter locally, and then re-query the slugs for more infos.

So I'm a little bit stuck here.   :-/

**Comment by Vinedine** [comment]
What you are trying to do is not possible with the API.

I tried something similar.  However I was trying to get all prices for a given player and did it this way;

First get this information (at player level);

![image](https://user-images.githubusercontent.com/19403380/114572895-312d6800-9c78-11eb-9719-3362667a3206.png)

With this you can create the slugs yourself and then call with your list of slugs

![image](https://user-images.githubusercontent.com/19403380/114573077-59b56200-9c78-11eb-9512-8deaebe03206.png)

Performance wise it is not ideal but it is the only way you can do it by staying underneath the API rate limit.

**Comment by jeremoquai** [comment]
Thanks but that's unfortunately not what I want to achieve.   :'(

I want basically a filter WHERE on all the database : it's a shame that what's so easy with SQL cannot be performed with GraphQL, no ?

Any dev from sorare to help us with this ? @such ? @spinach ? @descovi I know you were working on something similar, have you found a convenient way to do it ?

Last question : how does https://www.soraredata.com/cardFinder (even if it doesn't work for me at the present time : clicking on the "search" button does absolutely nothing) do ?

Thanks.

**Comment by jeremoquai** [comment]
well it's really a shame not to have more support...

poke @such @spinach @descovi
