### ISSUE TITLE
Get all offers from player

### ISSUE THREAD

**Issue by big-javascript-fan** [sorare/api#10]
I am trying to get offer list (current open offers and past offers) from player by using graphql API.

Is this possible to get those information by using current graphql API?

For example. I wanna get such information like this page.
https://www.soraredata.com/player/18538159439778858180151631836955205896581446882697419836141511765132905497677

![image](https://user-images.githubusercontent.com/48204519/111627631-a1ee7b00-87c5-11eb-86ba-fcdcc93923c7.png)

**Comment by Vinedine** [comment]
The only way I found a way to do this using the Sorare API was the following;
- Create a list of all the card slugs for that player
- Query each of those cards slugs to see if it is currently on sale

**Comment by big-javascript-fan** [comment]
@Vinedine  thanks for your reply.
But to perform that, it needs to have many API calls and in such case, it's really delay and not much useful to get.

Is GraphQL API still on development now?

**Comment by Vinedine** [comment]
Once you make a list of card slugs you can get all the information in one call;

![image](https://user-images.githubusercontent.com/19403380/111809255-13691f00-88d5-11eb-817f-353e0f8c5fce.png)

Performance wise it is not ideal but it works.

**Comment by Beatles-without-tea** [comment]
Hi, does anyone know where you can find all of the card slugs for one player?

**Comment by redox** [comment]
Thank you @Vinedine , yes this works; but I'm also willing to make sure we improve this. Hopefully with extra filters on the `cards` query. Will do in #64 

> Hi, does anyone know where you can find all of the card slugs for one player?

@Beatles-without-tea you can generate them as there are of form `<playerslug>-<season>-<rarity>-<serial>`, but the filters will help avoid the brute-force approach. Please follow #64 for this.

**Comment by breeze90** [comment]
Hey guys, any update to filtering cards for a certain player so that only onsale:true are shown?
