### ISSUE TITLE
New 400 BadRequest error type on acceptOffer mutation 

### ISSUE THREAD

**Issue by arctcpk** [sorare/api#101]
Hi all,

For the last few days, I've been receiving a new error on the `acceptOffer` mutation. The error occurs, I think, when the offer has been accepted by someone else before my request gets processed. The API returns a 400 BadRequest: 
`Bad Request: 859: unexpected token at '{"created":"@1643744223.199344743","description":"Error received from peer ipv4:172.20.191.222:50051","file":"src/core/lib/surface/call.cc","file_line":1069,"grpc_message":"Couldn't find Offer with [WHERE (start_date <= '2022-02-01 19:37:03' AND end_date >= '2022-02-01 19:37:03') AND "offers"."aasm_state" = $1 AND "offers"."blockchain_id" = $2]","grpc_status":5}'`

I'm assuming that this error occurs for singleSaleOffers that have already been purchased (I can see someone else having acquired the card). However, it seems inconsistent. In many other cases in the past, I got a 404 when the card has already been sold, which makes more sense to me.

Can you clarify what errors we should expect with the `acceptOffer` mutation? 

Thanks in advance for your support. It's really great to see how responsive you are with developers here. I appreciate your support! 🙌

**Comment by redox** [comment]
This is a recent regression due to some internal testing; we'll fix the error message and ensure it 404s instead of 400.
