### ISSUE TITLE
list of clubs and players 

### ISSUE THREAD

**Issue by kortvelik** [sorare/api#102]
hello everyone..I'm just starting to figure it out, please tell me how to get a list of all the clubs, and then how to get a list of players of each club through the playground? thanks

**Comment by Floh89** [comment]
Hello kortvelik, I am looking for the same solution and I would like to have all the player data. I've heard that you can't just pull all player data. You have to do it per club, but unfortunately no solution has been found yet. If you happen to have gotten any further here, if you want you can also contact me by telegram (oTTo1005), then we can exchange ideas if necessary.

**Comment by redox** [comment]
Hey @kortvelik & @Floh89 

You can easily retrieve all released clubs with:

```gql
{
  clubsReady {
    name
    slug
  }
}
```

And then for each club (get their `slug` with the call before), you can get all players (paginated, you'll need to use the `endCursor`):

```gql
{
  club(slug: "psg-paris") {
    players {
      nodes {
        displayName
        position
        shirtNumber
        age
      }
      pageInfo {
        endCursor
      }
    }
  }
}
```

> You have to do it per club, but unfortunately no solution has been found yet.

Yes correct, but that shouldn't be a big deal. It's designed like this to ensure we're not extracting too much data (and doing too many DB queries under the hood).

Cheers!

**Comment by IDunnoSure** [comment]
Any way to find players that are no longer in active teams? Using AllCards query seems like overkill
