### ISSUE TITLE
HTTP 429 Error 

### ISSUE THREAD

**Issue by KS-Root** [sorare/api#103]
Hi, 

I use sorare API as a loged user, with JWT-AUD and an Authorization token.
So I should have the right to do 60 api calls per minute. 
But when I run a test, I can not go beyond 20 calls per minute. 

Is that an issue or did i missunderstood the documentation ?

**Comment by redox** [comment]
> Hi,
> 
> I use sorare API as a loged user, with JWT-AUD and an Authorization token. So I should have the right to do 60 api calls per minute. But when I run a test, I can not go beyond 20 calls per minute.
> 
> Is that an issue or did i missunderstood the documentation ?

That's weird; because indeed it should be 60. 20 is the limit for non-authenticated calls. Could you confirm the tokens are working by querying `currentUser { slug email }`?

**Comment by KS-Root** [comment]
Hi, 

I just tried your request,

It retrive my email and a concat of my firstname and mylast name. 
So apparently it work prety fine. 

In the same run i set in a loop  :
     -an api call then 
     -a 1 second sleep 

and after 65 call and it give me a http error 429 {"error": "Too many requests, please retry later."}
The first call started at 2022-02-04 15:52:00.874333
The last call strated at 2022-02-04 15:53:44.356935

**Comment by redox** [comment]
> Hi,
> 
> I just tried your request,
> 
> It retrive my email and a concat of my firstname and mylast name. So apparently it work prety fine.
> 
> In the same run i set in a loop : -an api call then -a 1 second sleep
> 
> and after 65 call and it give me a http error 429 {"error": "Too many requests, please retry later."} The first call started at 2022-02-04 15:52:00.874333 The last call strated at 2022-02-04 15:53:44.356935

I can investigate this. Do you mind sharing the first digits of your IP address so I can drill down our logs?

**Comment by KS-Root** [comment]
hi, 

here is the fist digits of my ip when i run ipconfig in command line IPV4 192.168.XXX.XXX

Is that good for you ?

**Comment by redox** [comment]
> hi,
> 
> here is the fist digits of my ip when i run ipconfig in command line IPV4 192.168.XXX.XXX
> 
> Is that good for you ?

Arg this is your local network IP address. You can get your public one on services like https://whatismyipaddress.com/

**Comment by KS-Root** [comment]
Hi, 

So my public ip4 start by 195.200

Here are the log of a test i just ran. 
The date time is in the centrale european time zone 
hope it will help

[LOG.csv](https://github.com/sorare/api/files/8013220/LOG.csv)

**Comment by redox** [comment]
> So my public ip4 start by 195.200
> 
> Here are the log of a test i just ran. The date time is in the centrale european time zone hope it will help

I confirm I see it in our logs. That being said, the call seems to have been done **anonymously**. Can you double-check how you pass the `Authorization` header or share with us your code?

**Comment by redox** [comment]
Hey @KS-Root, we've found a corner case where the rate-limiter wouldn't consider the JWT tokens to consider the call authenticated. This should now be fixed. Let me know if you now experience the 60 QPM limit (300 per 5 min window).

**Comment by KS-Root** [comment]
hi @redox 
i just ran my previous test and everything seem fine. 
Thank you a lot ! 

best regards 
KS-root
