### ISSUE TITLE
Line Up

### ISSUE THREAD

**Issue by ZozoozoZ** [sorare/api#105]
Hello,

I would expected that there is a way to retrieve the submitted line-up for the current GW onced signed it. But I can not figure it out... Could you point me to the correct scheme/request in the API ?

Also, it would be nice to have a documentation in order to use the lineup mutations (createOrUpdateSo5Lineup/deleteSo5Lineup etc..).

Thanks,
Zozo

**Comment by redox** [comment]
> I would expected that there is a way to retrieve the submitted line-up for the current GW onced signed it. But I can not figure it out... Could you point me to the correct scheme/request in the API ?

Yes, this is something you can do with this; would that work?

```gql
query {
  so5Fixture {
    slug
    mySo5Lineups {
      so5Appearances {
      	card {
        	name
          position
        }
      }
    }
  }
}
```

> Also, it would be nice to have a documentation in order to use the lineup mutations (createOrUpdateSo5Lineup/deleteSo5Lineup etc..).

I'll keep this in our backlog, but will definitely work on documenting those mutations more precisely.

**Comment by ZozoozoZ** [comment]
> Yes, this is something you can do with this; would that work?

Worked like a charm, thanks.

> I'll keep this in our backlog, but will definitely work on documenting those mutations more precisely.

Cool !
