### ISSUE TITLE
Bid at an auction and sell card

### ISSUE THREAD

**Issue by AlessandroCordella** [sorare/api#106]
I wrote this query in order to get the list of all the current auctions for a player:
```
query {
  transferMarket {
    englishAuctions(playerSlugs: ["charles-de-ketelaere"]) {
      nodes {
        cards {
          slug
        }
        currentPrice
      }
    }
  }
}
```
What are the queries/mutation that have to be used in order to bid at an auction and then sell a card?

**Comment by redox** [comment]
Hey @AlessandroCordella,

you should be able to bid on those cards following our [Bidding on auction](https://github.com/sorare/api#bidding-on-auction) documentation. As well as the [Creating Offers](https://github.com/sorare/api#creating-offers) documentation to sell cards.

Hope this helps!
