### ISSUE TITLE
All cards caped?

### ISSUE THREAD

**Issue by xachigami** [sorare/api#11]
Hello,

When I request all cards using your API I only get 50 cards is it normal?

```
import requests
import json

with open('logged.json') as json_file:
    data = json.load(json_file)

headers = {
  "x-csrf-token" : data['csrf-token']
}

cookies = {
    '_sorare_session_id' : data['_sorare_session_id']
    }

file_object = open('queries/all_cards.graphql','r')
query = file_object.read()
file_object.close()

request = requests.post('https://api.sorare.com/graphql', json={'query': query}, headers=headers, cookies=cookies)

print(len(request.json()['data']['allCards']['nodes']))
```

**Comment by Vinedine** [comment]
Yes that is normal by default it returns the first 50.

You need to include the following parameters and implement pagination functionality

![image](https://user-images.githubusercontent.com/19403380/111806824-ab193e00-88d2-11eb-8060-e29a172a6cde.png)

Please look at this issue for more information; https://github.com/sorare/api/issues/1

**Comment by MarkOSullivan94** [comment]
By default does `allCards` return the latest created 50 cards if no arguments are passed?

**Comment by Vinedine** [comment]
I do not know what the ordering is.  If you look at example below it is hard to figure out what it could be.

![image](https://user-images.githubusercontent.com/19403380/112743009-ed5a1380-8f93-11eb-8fad-2a75e605cdad.png)

**Comment by MarkOSullivan94** [comment]
Yeah seems to have no order which makes it difficult to work with. Hopefully someone from the team can communicate 🤞

**Comment by cmenetrier** [comment]
The order actually seems to be by id - making new cards appearing randomly along the pages.
@such / @spinach  : Wouldn't it make sense to have the cards paginated by createdAt or any other attribute that would make it possible to query new cards from a previous saved cursor ?

**Comment by redox** [comment]
Merging with #71

**Comment by safwen1** [comment]
@redox Order is still an issue here, it makes it impossible to fetch new fresh data without having to go through all pages.
