### ISSUE TITLE
starkSignatures 

### ISSUE THREAD

**Issue by kortvelik** [sorare/api#110]
which library would you recommend using in python?

`data: JSON.stringify(signLimitOrder(privateKey, limitOrder)),`

**Comment by redox** [comment]
Starkware has a python implementation here: https://github.com/starkware-libs/starkex-resources/blob/master/crypto/starkware/crypto/signature/signature.py

will document it

**Comment by nachoroncero** [comment]
> which library would you recommend using in python?
> 
> `data: JSON.stringify(signLimitOrder(privateKey, limitOrder)),`

Hello, did you get to code the function? I am frustrated... thanks in advance
