### ISSUE TITLE
Login OK but not authenticated - PHP

### ISSUE THREAD

**Issue by gisernia** [sorare/api#114]
Hi,
I correctly obtain the access.

```
$query = 'mutation SignInMutation($input: signInInput!) {
    signIn(input: $input) {
      currentUser {
        slug
		id
		nickname
		email
      }
      #otpSessionChallenge
      errors {
        message
        code
		path
      }
    }
  }';

$data = [ 'OperationName' => "SignInMutation", 'query' => $query, 'variables' => [ 'input' => [ 'email' => $user, 'password' => $hashed_pass]] ];
$data = json_encode($data);

$options = array(
  'http' => array(
	'header' => "Content-Type: application/json\r\nUser-Agent: my test PHP\r\nX-CSRF-TOKEN: ".$csrf_token."\r\nCookie: _sorare_session_id=".$session_id."\r\n",
    'method'  => 'POST',
    'content' => $data
  )
);

$context  = stream_context_create($options);
$result = file_get_contents($url.'graphql', false, $context);


$jsonObject = json_decode($result);
//$sessionSor = $jsonObject->data->signIn->otpSessionChallenge;
//$otpCode = '402151';

if ($result === FALSE) { /* TO DO error */ }
var_dump($result);
$myVars = (get_headers($url.'graphql', false, $context));
```

response is OK:

`string(165) "{"data":{"signIn":{"currentUser":{"slug":"xxxxx","id":"User:1xxxx","nickname":"xxxx","email":"xxxx@gmail.com"},"errors":[]}}}"`

So after that I have retrieved the headers with 
$myVars = (get_headers($url.'graphql', false, $context));

Token and _sorare_session_id seems ok

$SessionOK  from [13] => Set-Cookie: _sorare_session_id= xxxxx
$CSRFToken from [10] => CSRF-TOKEN:  xxxxxx

now I try to make another call

```

$query3 = 'query CurrentUserQuery {
  currentUser {
    email
  }
}';

$data = [ 'OperationName' => "CurrentUserQuery", 'query' => $query3];
$data = json_encode($data);

$options = array(
  'http' => array(
  'header' => "Content-Type: application/json\r\nUser-Agent: my test PHP\r\nX-CSRF-TOKEN: ".$CSRFToken."\r\nCookie: _sorare_session_id=".$SessionOK."\r\n",
    'method'  => 'POST',
    'content' => $data
  )
);
/*

$context  = stream_context_create($options);
$result = file_get_contents($url.'graphql', false, $context);
$jsonObject = json_decode($result);

if ($result === FALSE) { /* Handle error */ }

var_dump($result);
```

I always receive

`string(29) "{"data":{"currentUser":null}}"
`

**Comment by redox** [comment]
Well, you're using the cookies-based (non documented & restricted to our sorare.com website usage) and therefore need to deal with `X-CSRF-TOKEN` and various session-based limitations, this is why.

Instead of relying on Cookies/X-CSRF-TOKEN/sessions; I would recommend you rather use the `jwtToken` as documented in https://github.com/sorare/api#graphql-signin-mutation : it is way easier to use and you won't need to deal with cookies and CSRF, also has a default expiration time of 1y.

Good luck implementing this in PHP, as all of our examples are in cURL it shouldn't be too complex!

**Comment by gisernia** [comment]
Thanks Sylvain,
just done using `jwtToken`. Very Easy!

response:
`string(90) "{"data":{"currentUser":{"bankBalance":"x","cardsCount":x15,"email":"xxxxx@gmail.com"}}}"`

**Comment by redox** [comment]
NOICE \o/
