### ISSUE TITLE
Bid at an auction Python

### ISSUE THREAD

**Issue by AlessandroCordella** [sorare/api#116]
Following the documentation, I was able to get:

- starkKey
- id
- minNextBid
- limitOrders

I am not understanding this part of the documentation:
```
const starkSignatures = limitOrders.map((limitOrder) => ({
  data: JSON.stringify(signLimitOrder(privateKey, limitOrder)),
  nonce: limitOrder.nonce,
  expirationTimestamp: limitOrder.expirationTimestamp,
  starkKey,
}));

const bidInput = {
  starkSignatures,
  auctionId: englishAuctionId,
  amount: bidAmountInWei,
  clientMutationId: crypto.randomBytes(8).join(""),
};
```

Considering a limitOrders list, like the following:
```
[
{
   "data":{
      "englishAuction":{
         "limitOrders":[
            {
               "vaultIdSell":3662317,
               "vaultIdBuy":3756365,
               "amountSell":"200",
               "amountBuy":"1",
               "tokenSell":"0xb333e3142fe16b78628f19bb15afddaef437e72d6d7f5c6c20c6801a27fba6",
               "tokenBuy":"0x0400f73146b26bcbfcdaaf9f99c13f20be5abbc22925f81adc5f5025bd6ad325",
               "nonce":518,
               "expirationTimestamp":457632
            }
         ]
      }
   }
}
]
```

How can I implement that logic in Python? 
In particular, how can I implement the signLimitOrder function that seems to come only with a nodejs module?
Could someone provide me the definition of those variables in Python?

**Comment by redox** [comment]
> In particular, how can I implement the signLimitOrder function that seems to come only with a nodejs module?

Yes correct, from https://github.com/sorare/crypto that makes the usage of https://github.com/starkware-libs/starkex-resources/blob/master/crypto/starkware/crypto/signature/signature.js slightly more specific to Sorare by exposing a simple `signLimitOrder` helper.

> Could someone provide me the definition of those variables in Python?

We might add some python examples (and helpers) in the future. In the meantime, you can inspire from https://github.com/sorare/crypto/blob/66706b3285dca54c11c577d10c2aca124ec5843a/src/index.ts#L160-L167 and rely on https://github.com/starkware-libs/starkex-resources/blob/master/crypto/starkware/crypto/signature/signature.py to `hashMsg` and `sign`.

**Comment by ercole89** [comment]
Hi. 

I use the `hashMsg` and `sign` of the link that you have posted: https://github.com/starkware-libs/starkex-resources/blob/master/crypto/starkware/crypto/signature/signature.py.

However, it appears the following error:

**{'data': {'createSingleSaleOffer': {'offer': None, 'errors': [{'message': 'invalid limit order signature'}]}}}**

the signature of the limit Order is not correct.
I have tested the function using the following script:

```
from starkware.crypto.signature import sign
from starkware.crypto.signature import get_limit_order_msg

def sign_limit_order(private_key,limitOrder):
    '''
    The sign_limit_order(private_key,limit_order) function is used to sign
     a Limit_order object with a Sorare private key.
    :param private_key: Your Sorare private key
    :param limit_order: The LimitOrder object you get from GraphQL
    :return: r,s
    '''

    vault_sell = int(limitOrder['vaultIdSell'])
    vault_buy = int(limitOrder['vaultIdBuy'])
    amount_sell = int(limitOrder['amountSell'])
    amount_buy = int(limitOrder['amountBuy'])
    token_sell = (int(limitOrder['tokenSell'], 16))
    token_buy = (int(limitOrder['tokenBuy'], 16))
    nonce = int(limitOrder['nonce'])
    expiration_timestamp = (limitOrder['expirationTimestamp'])
    private_key = int(private_key, 16)

    message = get_limit_order_msg(vault_sell, vault_buy, amount_sell, amount_buy, token_sell, token_buy, nonce,
                                  expiration_timestamp)
    return sign(message,private_key)

def test_sign_limit_order():
    # https://github.com/sorare/crypto/blob/03f5f34e1699b75b04545f9ee0edac4a30abcc8c/src/index.test.ts#L97

    limitOrder = {
    'vaultIdSell': 21,
    'vaultIdBuy': 27,
    'amountSell': '2154686749748910716',
    'amountBuy': '1470242115489520459',
    'tokenSell': '0x5fa3383597691ea9d827a79e1a4f0f7989c35ced18ca9619de8ab97e661020',
    'tokenBuy': '0x774961c824a3b0fb3d2965f01471c9c7734bf8dbde659e0c08dca2ef18d56a',
    'nonce': 0,
    'expirationTimestamp': 438953,
    }
    public_key = "0x77a3b314db07c45076d11f62b6f9e748a39790441823307743cf00d6597ea43"
    privateKey ='0x03c1e9550e66958296d11b60f8e8e7a7ad990d07fa65d5f7652c4a6c87d4e3cc'

    r, s = sign_limit_order(privateKey, limitOrder)
    r = hex(r)
    s = hex(s)
    if r == '0x173fd03d8b008ee7432977ac27d1e9d1a1f6c98b1a2f05fa84a21c84c44e882':
        print("BRAVO",r)
    if s == '0x4b6d75385aed025aa222f28a0adc6d58db78ff17e51c3f59e259b131cd5a1cc':
        print("BRAVO",s)
```

And the test is passed correctly, but when I use on SORARE to sign an offer or an auction, the "invalid limit order signature" appears.

How can I solve it?
Thanks.

**Comment by ercole89** [comment]
this is the print of Parameters for createSingleSaleOffer (starkKey is obfuscated):

```
{'input': 
	{'starkSignatures': 
		[{
		'data': '{"r": "0x445f034687e402c05435eb51f387bb493442e746f2fd2e0718b962d8e88b689", "s": "0x29e57ccddde60f1dbbf037fc4e29f8cb407b3a0cf2ef3897be65fd9242284e"}',
		'nonce': 744,
		'expirationTimestamp': 458362,
		'starkKey': '0x0000000000000000000000000000000000000000000000000000000000000000'
		}],
	 'dealId': 'd5cb5293',
	 'cardSlug': 'cristian-gamboa-luna-2021-limited-117',
	 'price': 500000000000000000,
	 'clientMutationId': '6d600a53fc8064b8'
	 }
 }
```

**Comment by redox** [comment]
Closing for now.

**Comment by nachoroncero** [comment]
> Following the documentation, I was able to get:
> 
> * starkKey
> * id
> * minNextBid
> * limitOrders
> 
> I am not understanding this part of the documentation:
> 
> ```
> const starkSignatures = limitOrders.map((limitOrder) => ({
>   data: JSON.stringify(signLimitOrder(privateKey, limitOrder)),
>   nonce: limitOrder.nonce,
>   expirationTimestamp: limitOrder.expirationTimestamp,
>   starkKey,
> }));
> 
> const bidInput = {
>   starkSignatures,
>   auctionId: englishAuctionId,
>   amount: bidAmountInWei,
>   clientMutationId: crypto.randomBytes(8).join(""),
> };
> ```
> 
> Considering a limitOrders list, like the following:
> 
> ```
> [
> {
>    "data":{
>       "englishAuction":{
>          "limitOrders":[
>             {
>                "vaultIdSell":3662317,
>                "vaultIdBuy":3756365,
>                "amountSell":"200",
>                "amountBuy":"1",
>                "tokenSell":"0xb333e3142fe16b78628f19bb15afddaef437e72d6d7f5c6c20c6801a27fba6",
>                "tokenBuy":"0x0400f73146b26bcbfcdaaf9f99c13f20be5abbc22925f81adc5f5025bd6ad325",
>                "nonce":518,
>                "expirationTimestamp":457632
>             }
>          ]
>       }
>    }
> }
> ]
> ```
> 
> How can I implement that logic in Python? In particular, how can I implement the signLimitOrder function that seems to come only with a nodejs module? Could someone provide me the definition of those variables in Python?

Hello, could you implement this in Python...? I am so frustrated, thanks in advance for your help

**Comment by AlessandroCordella** [comment]
@nachoroncero The solution thaht I am using for the moment is to use a javascript function through python
