### ISSUE TITLE
invalid limit order signature - CreateSingleSaleOffer

### ISSUE THREAD

**Issue by ercole89** [sorare/api#119]
Hello to everybody.

After reading all the issues on SORARE/API, I have tried to write the code in js using the starkware library instead of @sorare/crypto because initially I have tried to implement the code using python. 

Both python and js return me the same error:

python:
**{'data': {'createSingleSaleOffer': {'offer': None, 'errors': [{'message': 'invalid limit order signature'}]}}}**

Js:
**{ createSingleSaleOffer: { offer: null, errors: [ [Object] ] } } invalid limit order signature**

I believe that the problem is about the signLimitOrder function in @sorare/crypto, maybe it is slightly different from the starkware library.

how can I solve it?

Best regards

JS CODE:
```
const { GraphQLClient, gql } = require("graphql-request");
const { getLimitOrderMsg } = require("starkware-crypto");
const { sign } = require("starkware-crypto");
const { getKeyPair } = require("starkware-crypto");

const crypto = require("crypto");

const CurrentUser = gql`
  query CurentUserQuery {
    currentUser {
      starkKey
    }
  }
`;

const NewOfferLimitOrders = gql`
  mutation NewOfferLimitOrders($input: prepareOfferInput!) {
    prepareOffer(input: $input) {
      limitOrders {
        amountBuy
        amountSell
        expirationTimestamp
        nonce
        tokenBuy
        tokenSell
        vaultIdBuy
        vaultIdSell
      }
      errors {
        message
      }
    }
  }
`;

const CreateSingleSaleOffer = gql`
  mutation CreateSingleSaleOffer($input: createSingleSaleOfferInput!) {
    createSingleSaleOffer(input: $input) {
      offer {
        id
      }
      errors {
        message
      }
    }
  }
`;

function signLimitOrder(privateKey,limitOrder){
  console.log("Siamo qua ");
  console.log(limitOrder);
  console.log(limitOrder.vaultIdSell);
  keyPair = getKeyPair(privateKey);
  console.log("keyPair",privateKey);
  const message = getLimitOrderMsg(limitOrder.vaultIdSell,limitOrder.vaultIdBuy,limitOrder.amountSell,limitOrder.amountBuy,limitOrder.tokenSell,limitOrder.tokenBuy,limitOrder.nonce,limitOrder.expirationTimestamp);
    return sign(keyPair, message);
  };


async function main() {
  token='jwtToken';
  jwtAud='appname'; //appname

  const graphQLClient = new GraphQLClient("https://api.sorare.com/graphql", {
    headers: {
      Authorization: `Bearer ${token}`,
      "JWT-AUD": jwtAud,
    },
  });

  const currentUserData = await graphQLClient.request(CurrentUser);
  const starkKey = currentUserData["currentUser"]["starkKey"];
  console.log("Your starkKey is", starkKey);

  //sendCard = 'wilker-jose-angel-romero-2021-limited-45';
  //receiveWei='500000000000000000'; //0.5 eth

  const prepareOfferInput = {
    type: "SINGLE_SALE_OFFER",
    sendCardsSlugs: ['wilker-jose-angel-romero-2021-limited-45'],
    receiveCardsSlugs: [],
    sendWeiAmount: 0,
    receiveWeiAmount: '500000000000000000',
    receiverSlug: null,
    clientMutationId: crypto.randomBytes(8).join(""),
  };
  console.log(prepareOfferInput);

  const newOfferData = await graphQLClient.request(NewOfferLimitOrders, {
    input: prepareOfferInput,
  });
  console.log(newOfferData);

  const prepareOffer = newOfferData["prepareOffer"];
  if (prepareOffer["errors"].length > 0) {
    prepareOffer["errors"].forEach((error) => {
      console.error(error["message"]);
    });
    process.exit(2);
  }

  const limitOrders = prepareOffer["limitOrders"];
  if (!limitOrders) {
    console.error("You need to be authenticated to get LimitOrders.");
    process.exit(1);
  }
  console.log("limitOrders:");
  console.log(limitOrders);
  
  //sendCard = 'wilker-jose-angel-romero-2021-limited-45';
  //receiveWei='500000000000000000'; //0.5 eth
  privateKey = '0x00000000000000000000000000000000000000000000000000000';

  const starkSignatures = limitOrders.map((limitOrder) => ({
    data: JSON.stringify(signLimitOrder(privateKey, limitOrder)),
    nonce: limitOrder.nonce,
    expirationTimestamp: limitOrder.expirationTimestamp,
    starkKey,
  }));
  console.log(starkSignatures);

  //sendCard = 'wilker-jose-angel-romero-2021-limited-45';
  //receiveWei='500000000000000000'; //0.5 eth
  
  const createSingleSaleOfferInput = {
    starkSignatures,
    dealId: crypto.randomBytes(8).join(""),
    cardSlug: 'wilker-jose-angel-romero-2021-limited-45',
    price: '500000000000000000',
    clientMutationId: crypto.randomBytes(8).join(""),
  };
  console.log(createSingleSaleOfferInput);
  const createSingleSaleOfferData = await graphQLClient.request(
    CreateSingleSaleOffer,
    { input: createSingleSaleOfferInput }
  );
  console.log(createSingleSaleOfferData);
  const createSingleSaleOffer =
    createSingleSaleOfferData["createSingleSaleOffer"];

  if (createSingleSaleOffer["errors"].length > 0) {
    createSingleSaleOffer["errors"].forEach((error) => {
      console.error(error["message"]);
    });
    process.exit(2);
  }

  console.log("Success!");
}

main().catch((error) => console.error(error));
```const { GraphQLClient, gql } = require("graphql-request");
const { getLimitOrderMsg } = require("starkware-crypto");
const { sign } = require("starkware-crypto");
const { getKeyPair } = require("starkware-crypto");

const crypto = require("crypto");

const CurrentUser = gql`
  query CurentUserQuery {
    currentUser {
      starkKey
    }
  }
`;

const NewOfferLimitOrders = gql`
  mutation NewOfferLimitOrders($input: prepareOfferInput!) {
    prepareOffer(input: $input) {
      limitOrders {
        amountBuy
        amountSell
        expirationTimestamp
        nonce
        tokenBuy
        tokenSell
        vaultIdBuy
        vaultIdSell
      }
      errors {
        message
      }
    }
  }
`;

const CreateSingleSaleOffer = gql`
  mutation CreateSingleSaleOffer($input: createSingleSaleOfferInput!) {
    createSingleSaleOffer(input: $input) {
      offer {
        id
      }
      errors {
        message
      }
    }
  }
`;

function signLimitOrder(privateKey,limitOrder){
  console.log("Siamo qua ");
  console.log(limitOrder);
  console.log(limitOrder.vaultIdSell);
  keyPair = getKeyPair(privateKey);
  console.log("keyPair",privateKey);
  const message = getLimitOrderMsg(limitOrder.vaultIdSell,limitOrder.vaultIdBuy,limitOrder.amountSell,limitOrder.amountBuy,limitOrder.tokenSell,limitOrder.tokenBuy,limitOrder.nonce,limitOrder.expirationTimestamp);
    return sign(keyPair, message);
  };


async function main() {
  token='jwtToken';
  jwtAud='appname'; //appname

  const graphQLClient = new GraphQLClient("https://api.sorare.com/graphql", {
    headers: {
      Authorization: `Bearer ${token}`,
      "JWT-AUD": jwtAud,
    },
  });

  const currentUserData = await graphQLClient.request(CurrentUser);
  const starkKey = currentUserData["currentUser"]["starkKey"];
  console.log("Your starkKey is", starkKey);

  //sendCard = 'wilker-jose-angel-romero-2021-limited-45';
  //receiveWei='500000000000000000'; //0.5 eth

  const prepareOfferInput = {
    type: "SINGLE_SALE_OFFER",
    sendCardsSlugs: ['wilker-jose-angel-romero-2021-limited-45'],
    receiveCardsSlugs: [],
    sendWeiAmount: 0,
    receiveWeiAmount: '500000000000000000',
    receiverSlug: null,
    clientMutationId: crypto.randomBytes(8).join(""),
  };
  console.log(prepareOfferInput);

  const newOfferData = await graphQLClient.request(NewOfferLimitOrders, {
    input: prepareOfferInput,
  });
  console.log(newOfferData);

  const prepareOffer = newOfferData["prepareOffer"];
  if (prepareOffer["errors"].length > 0) {
    prepareOffer["errors"].forEach((error) => {
      console.error(error["message"]);
    });
    process.exit(2);
  }

  const limitOrders = prepareOffer["limitOrders"];
  if (!limitOrders) {
    console.error("You need to be authenticated to get LimitOrders.");
    process.exit(1);
  }
  console.log("limitOrders:");
  console.log(limitOrders);
  
  //sendCard = 'wilker-jose-angel-romero-2021-limited-45';
  //receiveWei='500000000000000000'; //0.5 eth
  privateKey = '0x00000000000000000000000000000000000000000000000000000';

  const starkSignatures = limitOrders.map((limitOrder) => ({
    data: JSON.stringify(signLimitOrder(privateKey, limitOrder)),
    nonce: limitOrder.nonce,
    expirationTimestamp: limitOrder.expirationTimestamp,
    starkKey,
  }));
  console.log(starkSignatures);

  //sendCard = 'wilker-jose-angel-romero-2021-limited-45';
  //receiveWei='500000000000000000'; //0.5 eth
  
  const createSingleSaleOfferInput = {
    starkSignatures,
    dealId: crypto.randomBytes(8).join(""),
    cardSlug: 'wilker-jose-angel-romero-2021-limited-45',
    price: '500000000000000000',
    clientMutationId: crypto.randomBytes(8).join(""),
  };
  console.log(createSingleSaleOfferInput);
  const createSingleSaleOfferData = await graphQLClient.request(
    CreateSingleSaleOffer,
    { input: createSingleSaleOfferInput }
  );
  console.log(createSingleSaleOfferData);
  const createSingleSaleOffer =
    createSingleSaleOfferData["createSingleSaleOffer"];

  if (createSingleSaleOffer["errors"].length > 0) {
    createSingleSaleOffer["errors"].forEach((error) => {
      console.error(error["message"]);
    });
    process.exit(2);
  }

  console.log("Success!");
}

main().catch((error) => console.error(error));

**Comment by ercole89** [comment]
these are the print of various object:

PrepareOfferInput:
```
{
  type: 'SINGLE_SALE_OFFER',
  sendCardsSlugs: [ 'wilker-jose-angel-romero-2021-limited-45' ],
  receiveCardsSlugs: [],
  sendWeiAmount: '0',
  receiveWeiAmount: '500000000000000000',
  receiverSlug: null,
  clientMutationId: '0489204153117261'
}
```

LimitOrder:
```
limitOrders:
[
  {
    amountBuy: '50000000',
    amountSell: '1',
    expirationTimestamp: 458385,
    nonce: 920,
    tokenBuy: '0xb333e3142fe16b78628f19bb15afddaef437e72d6d7f5c6c20c6801a27fba6',
    tokenSell: '0x04006ad4e5410300905cb84136fadf3b3d630c6a5ff828a12d7d649eca379417',
    vaultIdBuy: 1746594,
    vaultIdSell: 3046972
  }
]
```

StarkSignature:
```
{
  starkSignatures: [
    {
      data: '{"r":"0x3ca31d6ed2c318a9cf6c152d8f53ec6f8e3740112551017f17dd3c394a3fa9e","s":"0x70a779f7cabc50fc28348972a775d0d65451f0b0f6ece2986edd7004b4d2f11"}',
      nonce: 920,
      expirationTimestamp: 458385,
      starkKey: '0x00000000000000000000000000000000000000000000000000000000'
    }
  ],
  dealId: '418314783',
  cardSlug: 'wilker-jose-angel-romero-2021-limited-45',
  price: '500000000000000000',
  clientMutationId: '228205246231341574537'
}
```

**Comment by ercole89** [comment]
any answer?

what does it mean "invalid Limit Order Signature?"

**Comment by davelaffi** [comment]
I had the same problem, I solved using 
privateKeyStarkWare as "Private key" instead of private key ETH

**Comment by asilbalaban** [comment]
can i see your python code

**Comment by rdelgado7** [comment]
I have the same problem, i tried with eth private key and Starkware private key,
any solutions?

**Comment by asilbalaban** [comment]
how we can help without seeing your code?
how do you sign with python? 
which libraries do you use.

**Comment by rdelgado7** [comment]
`

    const SorareApi = require('./sorare');
    const Login = require('./login');
    const CardController = require('./card_controller');
    const models = require("./models");
    const web3 = require('web3');
    const crypto = require('crypto');
    const constants = require('./constants');
    const {
        GraphQLClient,
        gql
    } = require("graphql-request");
    const {
        getLimitOrderMsg
    } = require("starkware-crypto");
    const {
        sign
    } = require("starkware-crypto");
    const {
        getKeyPair
    } = require("starkware-crypto");

    function signLimitOrder(privateKey, limitOrder) {
        console.log("Siamo qua ");
        console.log(limitOrder);
        console.log(limitOrder.vaultIdSell);
        keyPair = getKeyPair(privateKey);
        console.log("keyPair", privateKey);
        const message = getLimitOrderMsg(limitOrder.vaultIdSell, limitOrder.vaultIdBuy, limitOrder.amountSell, limitOrder.amountBuy, limitOrder.tokenSell, limitOrder.tokenBuy, limitOrder.nonce, limitOrder.expirationTimestamp);
        return sign(keyPair, message);
    };
    
    updateAllcardFromUserEmail = async (email) => {
        let user = await Login.getUserFromEmail(email);
        let token = await Login.getActiveTokenByUserId(user.id);
        CardController.getAllCardInSaleExpired(email);
    }
    
    sellCallSorare = async (slug, email) => {
        let user = await Login.getUserFromEmail(email);
        let token = await Login.getActiveTokenByUserId(user.id);
    
        const graphQLClient = new GraphQLClient("https://api.sorare.com/graphql", {
            headers: {
                Authorization: `Bearer ${token}`,
                "JWT-AUD": '<YourAud>',
                // 'APIKEY': '<YourOptionalAPIKey>'
            },
        });
        const currentUserData = await graphQLClient.request(`query CurentUserQuery {
            currentUser {
              starkKey
            }
          }`);
        console.log(currentUserData);
        const starkKey = currentUserData["currentUser"]["starkKey"];
        console.log("Your starkKey is", starkKey);
        let card = await models.Card.findOne({
            where: {
                slug: slug,
            }
        });
        let receiveWei = web3.utils.toWei("" + card.dataValues.eth, 'ether');
        const prepareOfferInput = {
            type: "SINGLE_SALE_OFFER",
            sendCardsSlugs: card.slug,
            receiveCardsSlugs: [],
            sendWeiAmount: 0,
            receiveWeiAmount: receiveWei,
            receiverSlug: null,
            clientMutationId: crypto.randomBytes(8).join(""),
        };
        const newOfferData = await graphQLClient.request(`mutation NewOfferLimitOrders($input: prepareOfferInput!) {
            prepareOffer(input: $input) {
              limitOrders {
                amountBuy
                amountSell
                expirationTimestamp
                nonce
                tokenBuy
                tokenSell
                vaultIdBuy
                vaultIdSell
              }
              errors {
                message
              }
            }
          }`, {
            input: prepareOfferInput,
        });
        const prepareOffer = newOfferData["prepareOffer"];
        if (prepareOffer["errors"].length > 0) {
            prepareOffer["errors"].forEach((error) => {
                console.error(error["message"]);
            });
            process.exit(2);
        }
    
        const limitOrders = prepareOffer["limitOrders"];
        if (!limitOrders) {
            console.error("You need to be authenticated to get LimitOrders.");
            process.exit(1);
        }
        const privateKey = constants.key_eth;
        console.log("privateKey", privateKey);
        const starkSignatures = limitOrders.map((limitOrder) => ({
            data: JSON.stringify(signLimitOrder(privateKey, limitOrder)),
            nonce: limitOrder.nonce,
            expirationTimestamp: limitOrder.expirationTimestamp,
            starkKey,
        }));
        console.log(starkSignatures);
        const createSingleSaleOfferInput = {
            starkSignatures,
            dealId: crypto.randomBytes(8).join(""),
            cardSlug: card.slug,
            price: receiveWei,
            clientMutationId: crypto.randomBytes(8).join(""),
          };
          console.log(createSingleSaleOfferInput);
          const createSingleSaleOfferData = await graphQLClient.request(
            `mutation CreateSingleSaleOffer($input: createSingleSaleOfferInput!) {
                createSingleSaleOffer(input: $input) {
                  offer {
                    id
                  }
                  errors {
                    message
                  }
                }
              }`,
            { input: createSingleSaleOfferInput }
          );
          console.log(createSingleSaleOfferData);
          const createSingleSaleOffer =
            createSingleSaleOfferData["createSingleSaleOffer"];
        
          if (createSingleSaleOffer["errors"].length > 0) {
            createSingleSaleOffer["errors"].forEach((error) => {
              console.error("error: ", error["message"]);
            });
            process.exit(2);
          }
        
          console.log("Success!");
    }
    
    sellCallSorare('XXXX, 'XXXXX');

`

`
    Siamo qua {
            amountBuy: '100000000',
            amountSell: '1',
            expirationTimestamp: 459999,
            nonce: 1325,
            tokenBuy: 'XXXX',
            tokenSell: 'XXX',
            vaultIdBuy: 1098077,
            vaultIdSell: 1125940
        }
        1125940
        keyPair a
            [{
                data: '{"r":"XXX","s":"XXX","recoveryParam":1}',
                nonce: 1325,
                expirationTimestamp: 459999,
                starkKey: 'XXXX'
            }] {
                starkSignatures: [{
                    data: '{"r":"XXX","s":"XXXX","recoveryParam":1}',
                    nonce: 1325,
                    expirationTimestamp: 459999,
                    starkKey: 'XXXX'
                }],
                dealId: '14470103110149184137202',
                cardSlug: 'XXXXX',
                price: '1000000000000000000',
                clientMutationId: '1882468216920025252177'
            } {
                createSingleSaleOffer: {
                    offer: null,
                    errors: [
                        [Object]
                    ]
                }
            }
        error: invalid limit order signature
`

**Comment by asilbalaban** [comment]
did you try to send price without quotes.

**Comment by rdelgado7** [comment]
Same result:
```
    dealId: '2501931271001093664201',
    cardSlug: 'XXXXX',
    price: 1000000000000000000,
    clientMutationId: '23911724524420617120'
    error:  invalid limit order signature

```
Thanks you a lot for trying to help me!

**Comment by rdelgado7** [comment]
Im trying use @sorare/crypto to signature, but I cant either

`const { signLimitOrder } = require("@sorare/crypto");`
```
node:internal/modules/cjs/loader:361
      throw err;
      ^

Error: Cannot find module 'XXXX/node_modules/@sorare/crypto/index.js'. Please verify that the package.json has a valid "main" entry
    at tryPackage (node:internal/modules/cjs/loader:353:19)
    at Function.Module._findPath (node:internal/modules/cjs/loader:566:18)
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:919:27)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/XXX/sell_repeat.js:8:28)
    at Module._compile (node:internal/modules/cjs/loader:1099:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at node:internal/main/run_main_module:17:47 {
  code: 'MODULE_NOT_FOUND',
  path: '/XXX/node_modules/@sorare/crypto/package.json',
  requestPath: '@sorare/crypto'
}
```

**Comment by asilbalaban** [comment]
This is the working code block, try to insert this and check if it's works. If not i can send you to full script. 


`

  const prepareOfferInput = {
    type: "SINGLE_SALE_OFFER",
    sendCardsSlugs: sendCard,
    receiveCardsSlugs: [],
    sendWeiAmount: sendWei,
    receiveWeiAmount: receiveWei,
    receiverSlug: null,
    clientMutationId: crypto.randomBytes(8).join(""),
  };
  console.log(prepareOfferInput);

  const newOfferData = await graphQLClient.request(NewOfferLimitOrders, {
    input: prepareOfferInput,
  });
  console.log(newOfferData);

  const prepareOffer = newOfferData["prepareOffer"];
  if (prepareOffer["errors"].length > 0) {
    prepareOffer["errors"].forEach((error) => {
      console.error(error["message"]);
    });
    process.exit(2);
  }

  const limitOrders = prepareOffer["limitOrders"];
  if (!limitOrders) {
    console.error("You need to be authenticated to get LimitOrders.");
    process.exit(1);
  }
  console.log(limitOrders);

  const starkSignatures = limitOrders.map((limitOrder) => ({
    data: JSON.stringify(signLimitOrder(privateKey, limitOrder)),
    nonce: limitOrder.nonce,
    expirationTimestamp: limitOrder.expirationTimestamp,
    starkKey,
  }));
  console.log(starkSignatures);

  const createSingleSaleOfferInput = {
    starkSignatures,
    dealId: crypto.randomBytes(8).join(""),
    cardSlug: sendCard,
    price: receiveWei,
    clientMutationId: crypto.randomBytes(8).join(""),
  };
  console.log(createSingleSaleOfferInput);
  const createSingleSaleOfferData = await graphQLClient.request(
    CreateSingleSaleOffer,
    { input: createSingleSaleOfferInput }
  );
  console.log(createSingleSaleOfferData);

`

I send parameters on cli
The error says invalid limit order signature but it's not true. 
I think it's definitely a variable type or format issue.

**Comment by asilbalaban** [comment]
SendWei must be defined like this '0'

**Comment by asilbalaban** [comment]
add @sorare/crypto to your package.json and run npm install

**Comment by rdelgado7** [comment]
Same result, im trying with eth key and starkware key and I can't get it to work
can you give the full code please? thanks a lot!
and I already installed @sorare/crypto but didn't work

```
node --version
v17.9.0
```

**Comment by asilbalaban** [comment]
use nvm 17.4.0 

```
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh | bash

source ~/.bashrc

nvm list-remote

nvm install v17.4.0

cd /your path/ && npm install
```

I see code: 'MODULE_NOT_FOUND', in your error. So delete node_modules and reinstall maybe it will fix.

this is my package.json you can delete unnecessary packages
```
{
    "name": "buy-cards",
    "version": "1.0.0",
    "description": "buy cards from sorare",
    "main": "bot.js",
    "scripts": {
        "test": "echo \"Error: no test specified\" && exit 1"
    },
    "author": "",
    "license": "ISC",
    "dependencies": {
        "@sorare/actioncable": "^1.0.3",
        "@sorare/crypto": "^1.0.0",
        "child_process": "^1.0.2",
        "crypto": "^1.0.1",
        "discord-webhook-node": "^1.1.8",
        "graphql-request": "^4.0.0",
        "node-async-exec": "^1.2.0",
        "yargs": "^17.3.1"
    }
}
```

here is the full script. 
```
const { GraphQLClient, gql } = require("graphql-request");
const { signLimitOrder } = require("@sorare/crypto");
const crypto = require("crypto");
const yargs = require("yargs");

const {
  sendCard,
  sendWei,
  receiveCards,
  receiveWei,
  receiverSlug,
  token,
  jwtAud,
  privateKey,
} = yargs
  .command("createSingleSaleOffer", "Create a single sale offer.")
  .option("send-card", {
    description: "The card slug to send.",
    type: "string",
    required: true,
  })
  .option("send-wei", {
    description: "The amount of ETH to send, in wei.",
    type: "string",
    default: "0",
  })
  .option("receive-cards", {
    description: "The comma-separated list of card slugs to receive.",
    type: "string",
  })
  .option("receive-wei", {
    description: "The amount of ETH to receive, in wei.",
    type: "string",
    default: "0",
  })
  .option("receiver-slug", {
    description: "The receiver slug.",
    type: "string",
  })
  .option("token", {
    description: "The JWT or OAuth token.",
    type: "string",
    required: true,
  })
  .option("private-key", {
    description: "Your Sorare private key",
    type: "string",
    required: true,
  })
  .option("jwt-aud", {
    description: "The JWT audience (required if using a JWT token).",
    type: "string",
  })
  .help()
  .alias("help", "h").argv;

const CurrentUser = gql`
  query CurentUserQuery {
    currentUser {
      starkKey
    }
  }
`;

const NewOfferLimitOrders = gql`
  mutation NewOfferLimitOrders($input: prepareOfferInput!) {
    prepareOffer(input: $input) {
      limitOrders {
        amountBuy
        amountSell
        expirationTimestamp
        nonce
        tokenBuy
        tokenSell
        vaultIdBuy
        vaultIdSell
      }
      errors {
        message
      }
    }
  }
`;

const CreateSingleSaleOffer = gql`
  mutation CreateSingleSaleOffer($input: createSingleSaleOfferInput!) {
    createSingleSaleOffer(input: $input) {
      offer {
        id
      }
      errors {
        message
      }
    }
  }
`;

async function main() {
  const graphQLClient = new GraphQLClient("https://api.sorare.com/graphql", {
    headers: {
      Authorization: `Bearer ${token}`,
      "JWT-AUD": jwtAud,
      // 'APIKEY': '<YourOptionalAPIKey>'
    },
  });

  const currentUserData = await graphQLClient.request(CurrentUser);
  console.log(currentUserData);
  const starkKey = currentUserData["currentUser"]["starkKey"];
  console.log("Your starkKey is", starkKey);

  const prepareOfferInput = {
    type: "SINGLE_SALE_OFFER",
    sendCardsSlugs: sendCard,
    receiveCardsSlugs: [],
    sendWeiAmount: sendWei,
    receiveWeiAmount: receiveWei,
    receiverSlug: null,
    clientMutationId: crypto.randomBytes(8).join(""),
  };
  console.log(prepareOfferInput);

  const newOfferData = await graphQLClient.request(NewOfferLimitOrders, {
    input: prepareOfferInput,
  });
  console.log(newOfferData);

  const prepareOffer = newOfferData["prepareOffer"];
  if (prepareOffer["errors"].length > 0) {
    prepareOffer["errors"].forEach((error) => {
      console.error(error["message"]);
    });
    process.exit(2);
  }

  const limitOrders = prepareOffer["limitOrders"];
  if (!limitOrders) {
    console.error("You need to be authenticated to get LimitOrders.");
    process.exit(1);
  }
  console.log(limitOrders);

  const starkSignatures = limitOrders.map((limitOrder) => ({
    data: JSON.stringify(signLimitOrder(privateKey, limitOrder)),
    nonce: limitOrder.nonce,
    expirationTimestamp: limitOrder.expirationTimestamp,
    starkKey,
  }));
  console.log(starkSignatures);

  const createSingleSaleOfferInput = {
    starkSignatures,
    dealId: crypto.randomBytes(8).join(""),
    cardSlug: sendCard,
    price: receiveWei,
    clientMutationId: crypto.randomBytes(8).join(""),
  };
  console.log(createSingleSaleOfferInput);
  const createSingleSaleOfferData = await graphQLClient.request(
    CreateSingleSaleOffer,
    { input: createSingleSaleOfferInput }
  );
  console.log(createSingleSaleOfferData);
  const createSingleSaleOffer =
    createSingleSaleOfferData["createSingleSaleOffer"];

  if (createSingleSaleOffer["errors"].length > 0) {
    createSingleSaleOffer["errors"].forEach((error) => {
      console.error(error["message"]);
    });
    process.exit(2);
  }

  console.log("Success!");
}

main().catch((error) => console.error(error));
```

this is working. 
i call this script with php and python3 both of them works. 
the most important part is to send the variables with the correct types

**Comment by rdelgado7** [comment]
I don't know what I'm doing wrong, but I can't get it to work.node:internal/modules/cjs/loader:361
```
      throw err;
      ^

Error: Cannot find module '/home/xxx/sorareapi/node_modules/@sorare/crypto/index.js'. Please verify that the package.json has a valid "main" entry
    at tryPackage (node:internal/modules/cjs/loader:353:19)
    at Function.Module._findPath (node:internal/modules/cjs/loader:566:18)
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:919:27)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/home/xxxx/sorareapi/example.js:2:28)
    at Module._compile (node:internal/modules/cjs/loader:1097:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1149:10)
    at Module.load (node:internal/modules/cjs/loader:975:32) {
  code: 'MODULE_NOT_FOUND',
  path: '/home/xxx/sorareapi/node_modules/@sorare/crypto/package.json',
  requestPath: '@sorare/crypto'
}

Node.js v17.4.0
```

library installed:
[https://ibb.co/NWgg34y](url)

**Comment by asilbalaban** [comment]
did you copy my package json?
i see Please verify that the package.json  has a valid "main" entry on your error.

**Comment by rdelgado7** [comment]
Yes, i copied it.

`Error: Cannot find module '/home/XXXX/sorareapi/node_modules/@sorare/crypto/index.js'`

The library dont have this file, Could this be the problem?

**Comment by rdelgado7** [comment]
I JUST created other folder with your files and it works!
I dont understand it but thanks a lot!

**Comment by rdelgado7** [comment]
the library "@sorare/crypto" installed in bot folders are different , I move the right folder to my project and its work!
Thanks a lot!!!

**Comment by asilbalaban** [comment]
Have a nice sales.

**Comment by redox** [comment]
Thanks @asilbalaban 👌🏻

**Comment by Luby1993** [comment]
@rdelgado7 @asilbalaban can you help me please ? I have the same issue in python...the library **const { signLimitOrder } = require("@sorare/crypto");** does not exists for python, so I can't invoke the function **signLimitOrder**. Do you have any suggestions ? Thanks

**Comment by asilbalaban** [comment]
I also try implement it but i couldn't make it work.

**Comment by jos123456** [comment]
I'm having the same error:

"{ createSingleSaleOffer: { offer: null, errors: [ [Object] ] } } invalid limit order signature"

I launch the script (https://github.com/sorare/api/blob/master/examples/createSingleSaleOffer.js) from shell:

node createSingleSaleOffer.js --send-asset-id XXXX  --receive-wei 20000000000000000 --private-key XXXX  --token XXXXX  --jwt-aud "XXXX" --receiver-slug  MyUserSlug

My package.json is:
{
  "dependencies": {
    "@sorare/actioncable": "^1.0.3",
    "@sorare/crypto": "^1.1.0",
    "graphql": "^16.5.0",
    "graphql-request": "^4.3.0",
    "mysql2": "^2.3.3",
    "yargs": "^17.5.1"
  }
}
node v17.4.0, 

Everything seems ok, all green colors, but at the end  "invalid limit order signature" keeps showing.

(I also tried the shared script from this issue receiving the same error message).
