### ISSUE TITLE
Python requests authentication

### ISSUE THREAD

**Issue by fgirbal** [sorare/api#12]
I can't seem to authenticate properly using Python's `requests` library; I might be making a stupid mistake, not sure. Here's the code I'm using:
```
base_url = "https://api.sorare.com"
email = "EMAIL"
password = b"PASSWORD"

s = requests.Session()

# get salt to hash password and session cookies
salt_req = s.get(f"{base_url}/api/v1/users/{email}")

salt = salt_req.json()["salt"]
hashed_password = bcrypt.hashpw(password, salt.encode("utf-8")).decode("utf-8")

payload = {"user": {"email": email, "password": hashed_password}}
cookies = {"_sorare_session_id": salt_req.cookies["_sorare_session_id"]}
headers = {"x-csrf-token": salt_req.headers["CSRF-TOKEN"]}

sign_in_url = f"{base_url}/users/sign_in.json"

r = s.post(sign_in_url, data=payload, cookies=cookies, headers=headers)
print(r.json())
```
which gets me a response of `{'error': 'invalid'}`. 

Am I making a mistake somewhere?

**Comment by Ethamoto** [comment]
I have the exact same problem you do using very similar code, I get the same json response and a 401 status code (if I ask for the status code) suggesting I haven't passed the correct details.

```
import requests
from requests import get as get
from requests import post as post
import json
import bcrypt


# Initial get request
r = get('https://api.sorare.com/api/v1/users/user@mail')
response = json.loads(r.content)

# get salt and hash with password
salt = response['salt'].encode('utf8')
pwrd = "seecret".encode('utf8')
hashed = bcrypt.hashpw(pwrd, salt).decode('utf8')

# get session_id cookie
session = r.cookies['_sorare_session_id']

cookies = {
    "_sorare_session_id": session
}

# gest csfr
csrf = r.headers["CSRF-TOKEN"]
headers = {
    "x-csrf-token": csrf
}

p = post('https://api.sorare.com/users/sign_in.json',
         {"user": {"email": "user@mail", "password": hashed}}, headers=headers, cookies=cookies)

print(p.json())
```

**Comment by Vinedine** [comment]
I recommend you try the SignIn mutation instead I had better luck with that; https://github.com/sorare/api/issues/2

**Comment by Ethamoto** [comment]
Thanks Vinedine but I can't code in Javascript that well and I am hoping for a pythonic solution. I have noticed others have been authenticating successfully via python so I hope they may be able to help.

**Comment by Ethamoto** [comment]
I think I've solved it (with your help Vinedine).

I haven't actually had a chance to send any requests for data yet. I will report back and confirm once I have had the time but the code below returns a 200 status so I reckon it's is all good. 

Did I understand the readme correctly in that I am supposed to now capture the session cookie from the authentication response and use that cookie (instead of the session cookie retrieved from the salt) when sending additional requests?

```
import requests
from requests import get as get
from requests import post as post
import json
import bcrypt

# Initial get request
r = get('https://api.sorare.com/api/v1/users/ user@mail.com')
response = json.loads(r.content)

# get salt and hash with password
salt = response['salt'].encode('utf8')
pwrd = "seecret".encode('utf8')
hashed = bcrypt.hashpw(pwrd, salt).decode('utf8')

# get session_id cookie
session = r.cookies['_sorare_session_id']

cookies = {
    "_sorare_session_id": session
}

# gest csfr
csrf = r.headers["CSRF-TOKEN"]
headers = {

    "x-csrf-token": csrf
}

# Sign in Creds
sign_in_creds = '''
(
    email = user@mail.com,
    password = ''' + hashed + ''',
)
'''

# Payload
payload = '''
mutation{signIn(input:''' + sign_in_creds + '''){
  clientMutationId:
  errors{
    code
    message
    path
  }
  currentUser{
    id
    nickname
    email
  }
}}


'''

p = post('https://api.sorare.com/graphql', data=payload, headers=headers, cookies=cookies)

print(p.status_code)

```

**Comment by fgirbal** [comment]
Thanks for sharing @Ethamoto and @Vinedine! 

Your code @Ethamoto still doesn't seem to work for me. I believe the return code `200` at the request level means only that the GraphQL server has received and responded to the request; if you print the `json()` you get a missing query error (`{'errors': [{'message': 'No query string was present'}]}`). I've changed the request to pass `data={'query': payload}`, and that fixes that issue, but the query isn't successful, maybe it's down to the GQL mutation though.

@Vinedine is this what the query should look like:
```
mutation{signIn(input:
  {
      email: "EMAIL",
      password: "HASHED_PASSWORD",
  }
  ){
    clientMutationId:
    errors{
      code
      message
      path
    }
    currentUser{
      id
      nickname
      email
    }
  }
}
```

It doesn't seem to work for me in Sorare's GQL playground.

**Comment by Ethamoto** [comment]
Yea your right its not solved. I have a different error to you. If I use that code and call the json I get the following.

```
{'data': {'signIn': None}, 'errors': [{'message': 'Cannot return null for non-nullable field UserError.message'}]}
```
I'm at a loss now.

**Comment by Vinedine** [comment]
I am not a Python export so it is hard for me to see what could be wrong.  The code I posted in #2 is in C#.

What does look odd in your request is the _:_ after _clienMutationId_.  I would remove that and try again.

Also I never had any luck getting the mutations to work in Sorare's GQL playground.  I only used the GQL playground for the documentation and testing Query requests.

It did take me ages to get this to work correctly (a lot of trial and error).

**Comment by AsmalTaariq** [comment]
After much trial and error I managed to get the log in working by doing the following:

```
from requests import get as get
from requests import post as post
import json
import bcrypt

email = "my@email.com"

r = get(f'https://api.sorare.com/api/v1/users/{email}')
response = json.loads(r.content)

# get salt and hash with password
salt = response['salt'].encode('utf8')
pwrd = "mypassword".encode('utf8')
hashed = bcrypt.hashpw(pwrd, salt).decode('utf8')

# get csfr
csrf = r.headers["CSRF-TOKEN"]
headers = {
    "x-csrf-token": csrf
}

# login
url = 'https://api.sorare.com/graphql'
login_query = """
mutation SignInMutation($input: signInInput!) {
  signIn(input: $input) {
    currentUser {
      slug
      __typename
    }
    otpSessionChallenge
    errors {
      path
      message
      __typename
    }
    __typename
  }
}
"""

variables = {
  "input": {
    "email": email,
    "password": hashed
  }
}

p = post(url, json={'query': login_query, 'OperationName': 'SignInMutation', 'variables': variables}, headers=headers)
```

It is worth noting that the request failed when I tried to add the email and hashed password directly into the request instead of using them as variables. This issue could be replicated in the playground as well.

Keep in mind that if you have 2FA active on your account, then this is just the first half of the solution. The next is to provide the 2FA code as well.

The response I got was:

`'{"data":{"signIn":{"currentUser":null,"otpSessionChallenge": <otpSessionCode>,"errors":[],"__typename":"signInPayload"}}}'`

**Comment by fgirbal** [comment]
Yeah, that solved it! Thanks @AsmalTaariq.

**Comment by jeremoquai** [comment]
Hello.

Sorry, quite new to Python and GraphQL... :-/

Your code doesn't work for me as it returns :

```
Traceback (most recent call last):
  File "C:\Users\Jeremie\Dropbox\perso\projects\python\sorare\test.py", line 9, in <module>
    response = json.loads(r.content)
  File "C:\Users\Jeremie\AppData\Local\Programs\Python\Python38-32\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "C:\Users\Jeremie\AppData\Local\Programs\Python\Python38-32\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\Jeremie\AppData\Local\Programs\Python\Python38-32\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

Any idea ? Many thanks in advance !
