### ISSUE TITLE
Not all the cards shows up in ACardWasUpdated

### ISSUE THREAD

**Issue by c3-Luca-Canensi** [sorare/api#125]
let's check this thread in discord https://discord.com/channels/474213294421573632/664837984134365184/945717576082784306
@redox @such

**Comment by redox** [comment]
For the record, we've been discussing this issue on Discord. Well, from the server logs's POV the specific card )`george-acosta-2021-limited-178`) triggered the expected graphql notifications/events. There must be something else, we'll continue the investigation with the help of the community eventually providing more details through this thread (preferred way @c3-Luca-Canensi) or on discord.

Closing until we reproduce/understand more.
