### ISSUE TITLE
Subscription to new public offers

### ISSUE THREAD

**Issue by AlessandroCordella** [sorare/api#127]
What is the right subscription query to use in order to get all the new public offers for all players?
I tried this the following one, but only auctions are listed, not public offers:
```
subscription_query = {
    "query": "subscription { publicMarketWasUpdated { "
             "slug,"
             "id,"
             "onSale,"
             " } }",
    "variables": {},
    "action": "execute"
}
```
Furtheremore, why can't I use the canBuy parameter in this type of query?

**Comment by redox** [comment]
Hello @AlessandroCordella,

> What is the right subscription query to use in order to get all the new public offers for all players?
> I tried this the following one, but only auctions are listed, not public offers:

The right subscription to go for is `aCardWasUpdated`, which triggers every time a card (or an attached auction/offer) is updated.


> Furtheremore, why can't I use the canBuy parameter in this type of query?

It's a current limitation of the API. We'll continue working on adding more filters but no ETA.
