### ISSUE TITLE
public API Rate Limited

### ISSUE THREAD

**Issue by jasadams-imtbl** [sorare/api#13]
I am trying to extract the card metadata from the API using the tokenURI returned by the Ethereum smart contract. I seem to be getting rate limited. The documentation mentions that I can request an API Key but doesn't mention how to make that request. How can I get an API Key

**Comment by Vinedine** [comment]
To request an API Key you need to contact Sorare directly at contact@sorare.com.

Without an API key the limit is 300 requests per 5 minutes, if you have an API key it is raised to 3000 requests per 5 mins.

My understanding is that you can only get an API key if you are doing a project that will help the community.

**Comment by jasadams-imtbl** [comment]
thanks, thats all the info I need
