### ISSUE TITLE
Card missing shirtNumber

### ISSUE THREAD

**Issue by juliusdanek** [sorare/api#130]
Check the following card. Missing the shirt number, even though it pretty clearly says it on the card. 

```graphql
query {
  card(slug: "jae-moon-ryu-2020-rare-14") {
    slug
    blockchainId
    position    
    rarity
    id
    serialNumber
    player {
      slug
      id
    }
    season {
      startYear
    }
    cardEdition {
      displayName
    }
    serialNumber
    shirtNumber
  }
}

```

**Comment by juliusdanek** [comment]
A few more examples:

alexander-ring-2020-rare-22
przemyslaw-frankowski-2020-rare-26
kazuyoshi-miura-2020-rare-36
stanislav-lobotka-2019-super_rare-2
jens-toornstra-2020-rare-1

**Comment by redox** [comment]
Interesting, investigating.

**Comment by juliusdanek** [comment]
Seems like the issue persists? @redox

**Comment by redox** [comment]
This is now fixed.

**Comment by juliusdanek** [comment]
Thank you!
