### ISSUE TITLE
websocket ping latency ?

### ISSUE THREAD

**Issue by MichaelBornand** [sorare/api#134]
Hello,

I am having a strange behavior with the ping message sent by the websocket server.
WHen receiving a ping message, I always have a huge latency before receiving next messages. Sometimes I even receive two ping messages before getting newly subscribed message.

Is that a normal behavior ? Can I do something about that ? I can see that there is a ping message sent every 3/4 secondes, is it necessary ?

Here is a small exemple of what i'm receiving

`{"identifier":"{\"channel\":\"GraphqlChannel\"}","message":{"more":true,"result":{"data":{"aCardWasUpdated":{"liveSingleSaleOffer":null,"onSale":false,"openForGameStats":true,"player":{"slug":"1996-06-28"},"rarity":"rare","slug":"1996-06-28-2021-rare-35","tradeableStatus":"YES"}}}}}

{"identifier":"{\"channel\":\"GraphqlChannel\"}","message":{"more":true,"result":{"data":{"aCardWasUpdated":{"liveSingleSaleOffer":null,"onSale":false,"openForGameStats":true,"player":{"slug":"adnan-januzaj"},"rarity":"limited","slug":"adnan-januzaj-2021-limited-293","tradeableStatus":"NOT_YET"}}}}}

{"type":"ping","message":1645668482}

{"type":"ping","message":1645668485}

{"identifier":"{\"channel\":\"GraphqlChannel\"}","message":{"more":true,"result":{"data":{"aCardWasUpdated":{"liveSingleSaleOffer":{"acceptedAt":null,"createdAt":"2022-02-24T02:06:12Z","id":"SingleSaleOffer:a868d014-2ec2-4ea6-b5e0-d786a5f8f3ca","price":"7000000000000000"},"onSale":true,"openForGameStats":true,"player":{"slug":"edgar-games-gonzalez"},"rarity":"limited","slug":"edgar-games-gonzalez-2021-limited-243","tradeableStatus":"YES"}}}}}

{"identifier":"{\"channel\":\"GraphqlChannel\"}","message":{"more":true,"result":{"data":{"aCardWasUpdated":{"liveSingleSaleOffer":{"acceptedAt":null,"createdAt":"2022-02-23T11:13:11Z","id":"SingleSaleOffer:6a67791f-4dfb-43e5-874b-941399bc1be4","price":"417100000000000000"},"onSale":true,"openForGameStats":true,"player":{"slug":"matheus-fernando-cavichioli"},"rarity":"rare","slug":"matheus-fernando-cavichioli-2021-rare-8","tradeableStatus":"YES"}}}}}

{"identifier":"{\"channel\":\"GraphqlChannel\"}","message":{"more":true,"result":{"data":{"aCardWasUpdated":{"liveSingleSaleOffer":null,"onSale":false,"openForGameStats":true,"player":{"slug":"miha-zajc"},"rarity":"limited","slug":"miha-zajc-2021-limited-191","tradeableStatus":"YES"}}}}}

{"identifier":"{\"channel\":\"GraphqlChannel\"}","message":{"more":true,"result":{"data":{"aCardWasUpdated":{"liveSingleSaleOffer":{"acceptedAt":null,"createdAt":"2022-02-24T02:06:07Z","id":"SingleSaleOffer:b4137553-1a0d-4278-a856-5a40a1a4b5c9","price":"19700000000000000"},"onSale":true,"openForGameStats":true,"player":{"slug":"alexis-de-sart"},"rarity":"rare","slug":"alexis-de-sart-2020-rare-16","tradeableStatus":"YES"}}}}}
`

Regards,

**Comment by redox** [comment]
> WHen receiving a ping message, I always have a huge latency before receiving next messages. Sometimes I even receive two ping messages before getting newly subscribed message.

Interesting.

> Is that a normal behavior ? Can I do something about that ? I can see that there is a ping message sent every 3/4 secondes, is it necessary ?

It's [default behavior of the Rails framework](https://github.com/rails/rails/blob/7-0-stable/actioncable/lib/action_cable/server/connections.rb#L25-L29) and doesn't look like something we can change.

Unfortunately, I'm not sure we'll be able to do much. Closing this for now as we won't work on addressing the underlying framework limitations.
