### ISSUE TITLE
onSale returns true on some cards not for sell

### ISSUE THREAD

**Issue by madrigo2** [sorare/api#135]
Example :

```
{
  card(slug: "jacob-shaffelburg-2021-super_rare-5") {
    slug
    onSale
  }
}

{
  "data": {
    "card": {
      "slug": "jacob-shaffelburg-2021-super_rare-5",
      "onSale": true
    }
  }
}
```
When I check the card on the website, I can see it's not for sale

**Comment by madrigo2** [comment]
Update : the card is now for sale

You can reproduce the described behaviour by running the same query on this card : juan-guillermo-cuadrado-bello-2020-rare-83

**Comment by redox** [comment]
> Update : the card is now for sale
> 
> You can reproduce the described behaviour by running the same query on this card : juan-guillermo-cuadrado-bello-2020-rare-83

OK, I think the `onSale` boolean is not considering the `startDate` of the `SingleSaleOffer` and therefore is `true` before `now() >= start_date`:

```gql
{
  card(slug: "jacob-shaffelburg-2021-super_rare-5") {
    slug
    onSale
    liveSingleSaleOffer {
      startDate
    }
  }
}
```

@madrigo2 what do you think about my hypothesis?

**Comment by madrigo2** [comment]
That's what I thought too. But as far as I know, you can only put a card on sale from the moment you clic the "sell my card" button.
As related in #133, a better description for API fields would be really helpful.

**Comment by madrigo2** [comment]
This one returns onSale: true and liveSingleSaleOffers is null (so no startDate)
```
{
  card(slug: "juan-guillermo-cuadrado-bello-2020-rare-83") {
    slug
    onSale
    liveSingleSaleOffer {
      startDate
    }
  }
}
```

**Comment by redox** [comment]
OK, I ultimately found the issue. Not yet sure it's a bug or a feature. It's because the `onSale` boolean reflects whether the card has an opened auction OR has a live single sale offer OR has a live direct offer.

In this case, the owner of this card received a direct offer. I'll check whether we want to document this, or whether we'll change the behavior and stop considering direct offers for this.
