### ISSUE TITLE
Missing Players in activePlayers() ?

### ISSUE THREAD

**Issue by tankard6666** [sorare/api#136]
I'm currently trying to get all active players of the club with slug "mainz-05-mainz":

`{
  club(slug: "mainz-05-mainz") {
    activePlayers {
      nodes {
        slug
      }
    }
  }
}`

in the response, i'm missing the players(slugs) 'alexander-hack' and 'stefan-bell'. Both players are currently playing actively for that team. 

When i try: 

`{
  player(slug: "stefan-bell") {
    activeClub {
      slug
    }
  }
}`

The response also is "mainz-05-mainz". 

if i query this club for all players with:

`{
  club(slug: "liverpool-liverpool") {
    players {
      nodes {
        slug
      }
      pageInfo {
        endCursor
      }
    }
  }
}`

They also appear in the response. 

My question: 
Why are these players not in the response of activePlayers(), and what  data does this function actually respond? How can i get all players that play at the moment for a team?

**Comment by redox** [comment]
Hey @tankard6666 , thanks for raising this issue. I could confirm there was a bug in the handling of a player<>team membership for some edge-case situations. This has now been fixed and `{ club(slug: "mainz-05-mainz") { activePlayers { nodes { slug } } } }` now returns `stefan-bell`
