### ISSUE TITLE
Missing player offer

### ISSUE THREAD

**Issue by AlessandroCordella** [sorare/api#137]
I am using the following query in order to obtain all the active offers for a player (I am interested only in offers from players, not auctions):
```
query findPlayer($player: String!){
  player(slug: $player) {
    cards(rarities: [limited]) {
      nodes {
        slug
        onSale
        liveSingleSaleOffer {
          price
          priceInFiat {
            eur
          }
        }
      }
    }
  }
}
```

```
query_variables = {
  "player": "ryogo-yamasaki"
}
```

I noticed that not all the offers displayed in Sorare are contained in the output of the query.

What am I doing wrong?

**Comment by redox** [comment]
The `cards` are paginated, so you need to play with the cursors to iterate over the pages. Ultimately, you will get something like this:

```gql
query findPlayer($slug: String!, $after: String) {
  player(slug: $slug) {
    cards(rarities: [limited], after: $after) {
      nodes {
        slug
        onSale
        liveSingleSaleOffer {
          price
          priceInFiat {
            eur
          }
        }
      }
      pageInfo {
        endCursor
      }
    }
  }
}
```

**Comment by redox** [comment]
Null and endCursor, check our docs here: https://github.com/sorare/api#pagination
