### ISSUE TITLE
Unable to authenticate due to 2FA enabled

### ISSUE THREAD

**Issue by MarkOSullivan94** [sorare/api#14]
Whenever trying to authenticate my account with the API I get the following response

```
{
  "otp_session_challenge": "c4afba209abd4fb6931a3917cc931a48",
  "error": "2fa_missing"
}
```

I noticed there's nothing in the README about this, would appreciate some guidance 🤞

**Comment by feikede** [comment]
You need to send another SignIn with your otpAttempt like so:

`"variables":{"input":{"otpAttempt":"194680","otpSessionChallenge":"c4afba209abd4fb6931a3917cc931a48","gaClientId":"1378987190.1617237638"}
`
And use the same clientId for this like in your email/pwd call.

**Comment by maxmax96** [comment]
What exactly goes in "gaClientId"?

**Comment by feikede** [comment]
@maxmax96 I use the number that my firefox used on a manual login. That works. Use the firefox (or chrome) dev tools to trace the network traffic on SignIn mutation.

**Comment by redox** [comment]
I've added some documentation about 2FA: https://github.com/sorare/api#2fa

Closing this issue.
