### ISSUE TITLE
logout after using api

### ISSUE THREAD

**Issue by MaWicK** [sorare/api#140]
Hello everytime i use the playground with my slug i got the data but Im disconnected from Sorare.
And if I use currentUser i got disconnected and no result on the playground cause i got currentUser: null
why ? :'(

**Comment by HadrienPierart** [comment]
Did you find any workaround to that @MaWicK ?
Im having the same issue starting today (for some reason, everything was fine yesterday), and I cant get any query to work in the playground...

**Comment by redox** [comment]
The work-around consist in using the Playground in an incognito window.

**Comment by HadrienPierart** [comment]
This does not seem to work either...
