### ISSUE TITLE
Issue with priceInFiat in aCardWasUpdated subscription

### ISSUE THREAD

**Issue by JGense** [sorare/api#143]
Hello,

Here is my issue:
When I subscribe with this request:

`aCardWasUpdated(rarities: [limited]) {
    slug
    onSale
    liveSingleSaleOffer {
      id
      card {
        slug
        rarity
      }
      price
    }
  }`

Everything is going well, I actually receive the triggers.

But if I add this:

`priceInFiat {
    eur
}`

below "price" , nothing happens.

I don't get any errors either, just nothing happens.

Has anyone had this problem before?

**Comment by kortvelik** [comment]
priceInFiat  is not available in the Card type, you probably need to use a wei converter

**Comment by faridmovsumov** [comment]
I have the same problem reported here so probably duplicate but can help with debugging https://github.com/sorare/api/issues/149

**Comment by faridmovsumov** [comment]
Based on documentation it should be possible 
<img width="1198" alt="image" src="https://user-images.githubusercontent.com/1541412/158062319-dff0f78d-c659-46dd-aa2b-b479558a1422.png">

**Comment by redox** [comment]
> priceInFiat is not available in the Card type, you probably need to use a wei converter

That's correct, this is why. I'll update the code snippets to display the error.

**Comment by faridmovsumov** [comment]
Displaying errors will save a lot of time thanks @redox, do you think it also can be helpful to update documentation as it gives wrong information.
