### ISSUE TITLE
aCardWasUpdated  Min Price Offer

### ISSUE THREAD

**Issue by satruxag** [sorare/api#146]
I am using the WS with the **aCardWasUpdated** method, I am able to extract all the information, but I am having difficulty in finding the minimum and average price of the limited both open and closed offers.

I'm using the active bidding method

```
nodes {
liveSingleSaleOffer {
       price
     }
}
```

however the data is limited to the first 50 cards only.

would it be possible to filter the search for cards for sale only?
alternatively, would it be possible to sort the search by price or date?

is there another method that allows me to quickly find the minimum price of open offers without where to use the cursor?

**Comment by redox** [comment]
> is there another method that allows me to quickly find the minimum price of open offers without where to use the cursor?

No there isn't really such thing.

What you could do however is rely on the `userOwnersWithRate` field in order to get the history of all owners of a card, which the price.

```
{
  card(slug:"kylian-mbappe-lottin-2021-rare-1") {
    slug
    userOwnersWithRate {
      id
      from
      ownerable {
        ... on User {
          slug
        }
      }
      price
      priceInFiat {
        eur
      }
    }
  }
}
```

I assume that would work right? You would need to do it for each serialNumber of a rarity.

**Comment by satruxag** [comment]
ok but so I have information on a card, instead I am interested in information about the player.
having to perform a query for each player multiplied by the number of pages, especially for the limited, causes a large consumption of API.

using the WS what would you advise me to do to quickly get the minimum price and the last 5 historical prices?

**Comment by redox** [comment]
> ok but so I have information on a card, instead I am interested in information about the player.
> having to perform a query for each player multiplied by the number of pages, especially for the limited, causes a large consumption of API.

That's correct; as of today we won't be able to offer more endpoints for this.

> using the WS what would you advise me to do to quickly get the minimum price and the last 5 historical prices?

You cannot go back in time/history with the WS; but what you can do is continuously listen to the updates and store everything; then in a few weeks you'll be able to compute some stats per player.
