### ISSUE TITLE
subscription.publicMarketWasUpdated

### ISSUE THREAD

**Issue by satruxag** [sorare/api#147]
through the ws i am trying to read all the sales or bits for single card

I'm using the **publicMarketWasUpdated** method but inside it I can't find a way to distinguish a "transfer in progress" from a "direct offer"

```
the query I launch is
     subscription {
   publicMarketWasUpdated {
     slug
     onSale
     rarity
     latestEnglishAuction {
       currentPrice
     }
     ownerSince
     liveSingleSaleOffer {
       price
     }
    
   }
}
```

**Comment by redox** [comment]
You resolved your issue @satruxag ?
