### ISSUE TITLE
soldSingleSaleOffers price mismatch on the website and API

### ISSUE THREAD

**Issue by faridmovsumov** [sorare/api#152]
I am trying to fetch the price user sold card but I noticed a small mismatch in amounts I see on the website and API could you please help understand what is the reason? ETH prices are correct, I have this problem with fiat currency.

Price From API: 33.13359
Price On The Website: 33.82

<img width="1138" alt="image" src="https://user-images.githubusercontent.com/1541412/158322526-5010efe9-943b-4fe6-ae0a-a2dc56d3e4a5.png">

<img width="1353" alt="image" src="https://user-images.githubusercontent.com/1541412/158322600-60db8ebd-570a-4078-ada7-5f776beda196.png">

Query which I use to get the price which user sold the card.

```graphql
query {
  user(slug: "tacticso") {
    nickname
    soldSingleSaleOffers {
      nodes {
        deal {
          minReceiveAmountInWei
        }
        card {
          slug
        }
        price
        priceInFiat {
          eur
        }
      }
      pageInfo {
        endCursor
      }
    }
  }
}
```

**Comment by eulbat** [comment]
@faridmovsumov The exchange rate of the owner object (what we show on the website) is taken at creation date of the owner (so when the offer is settled), whereas the exchange rate for an offer is taken at creation date of the offer.

Hope that clears it up
