### ISSUE TITLE
PreapareAccpetOffer and AcceptOffer in single query mutation

### ISSUE THREAD

**Issue by satruxag** [sorare/api#153]
Hello,
to buy a card on offer do I have to execute 2 different mutation queries (PreapareAccpetOffer and AcceptOffer) or can I nest the two mutations on a single call?

**Comment by redox** [comment]
> Hello,
> to buy a card on offer do I have to execute 2 different mutation queries (PreapareAccpetOffer and AcceptOffer) or can I nest the two mutations on a single call?

You indeed need to do 2 different mutations because you need to sign the result of `prepareAcceptOffer` and pass it to `acceptOffer`. See https://github.com/sorare/api#accepting-offers
