### ISSUE TITLE
Subscription, card was sold

### ISSUE THREAD

**Issue by davelaffi** [sorare/api#157]
Hello everyone,

With a subscription connection (either aCardWasUpdated or publicMarketWasUpdated) how can I understand if a card was bought? And if it was a Single Sale or a Direct offer?

Thanks!

**Comment by Styrian95** [comment]
Hello,
also struggling to understand if a card was bought. Did you manage to figure it out?
Would be nice if you can tell me your solution. 
Thx

**Comment by oelov** [comment]
Hello.
With publicMarketWasUpdated you can check "onSale" status of a card.
If onSale is False - card was sold.
