### ISSUE TITLE
bug: invalid schemas

### ISSUE THREAD

**Issue by doublesavonette** [sorare/api#167]
@redox 

Hi, I am wondering if the schemas fetched using https://api.sorare.com/graphql are deprecated as they lead to the following errors on my end. 

`TypeError: Interface field Node.id expects type ID! but LimitOrder.id is type String.`
`Interface field Node.id expects type ID! but PaymentIntent.id is type String!.`
`Interface field Node.id expects type ID! but PaymentMethod.id is type String!.`
`Interface field Node.id expects type ID! but ReferralPaginated.id is type String!.`
`Interface field Node.id expects type ID! but So5RankingsPaginated.id is type String!.`
`Interface field Node.id expects type ID! but So5RewardConfig.id is type String.`

Side note: it seems that a lot of changes are happening at the api level and those change are not added to the change logs (eg fields becoming deprecated). Would it be possible to add those to the change log ahead of time? 

Many thanks.

**Comment by redox** [comment]
Thanks for reporting it through GitHub, we're working on it and we should have a fix by later today.

**Comment by doublesavonette** [comment]
Awesome! Thanks for the very quick reply

**Comment by juliusdanek** [comment]
Seeing the same issue. Thank you!

**Comment by GiulianoTorregrossa** [comment]
Hello,
I found a similar error in your api playground, at : [https://api.sorare.com/graphql/playground](url)

`Invalid schema Error:
Interface field Node.id expects type ID! but LimitOrder.id is type String.
Interface field Node.id expects type ID! but PaymentIntent.id is type String!.
Interface field Node.id expects type ID! but PaymentMethod.id is type String!.
Interface field Node.id expects type ID! but ReferralPaginated.id is type String!.
Interface field Node.id expects type ID! but So5RankingsPaginated.id is type String!.
Interface field Node.id expects type ID! but So5RewardConfig.id is type String.
Interface field Node.id expects type ID! but Stats.id is type String!.
Interface field Node.id expects type ID! but TransferMarket.id is type String!.`

Docs and Schema tabs open but the content keep loading.

**Comment by GiulianoTorregrossa** [comment]
Now it works fine. Thanks!

**Comment by redox** [comment]
This has been fixed! Sorry about that everyone.
