### ISSUE TITLE
How to fetch all cards owned by a specific user in the past?

### ISSUE THREAD

**Issue by faridmovsumov** [sorare/api#168]
Is there a feature or maybe plans in the future to implement an endpoint that will allow users to fetch all cards owned by a specific user in the past?

**Comment by faridmovsumov** [comment]
I solved this problem by fetching all cards and keeping purchase history on a database of my app. However, would be nice to have a one function which will provide all these from single endpoint.

**Comment by redox** [comment]
Thanks for sharing your solution @faridmovsumov . I agree this could be improved with additional endpoints. As of today, our focus is to only add endpoints required for the actual Sorare.com website and let the community build around it, but I’m sure we will get there at some point.

**Comment by faridmovsumov** [comment]
Yes makes sense @redox 👍
