### ISSUE TITLE
question about user/users & slug/slugs

### ISSUE THREAD

**Issue by jeremoquai** [sorare/api#17]
Hello.

Sorry for the newbie question...   :-/

If I do :

```
query {
  users(slugs: "jeremtol") {
    nickname
    cards {
      slug
    }
  }
}

```
and 

```
query {
  user(slug: "jeremtol") {
    nickname
    cards {
      slug
    }
  }
}

```
both are working and returning the same result, but I really don't get how to ask for **MULTIPLE** slugs in the first case (does it work with a separator ? or am I missing something here ?)

Thanks !

**Comment by Vinedine** [comment]
You need to use the users call;

![image](https://user-images.githubusercontent.com/19403380/114037401-3f971080-9881-11eb-86cc-001d55c835e3.png)

Make the list of slugs separated by a comma

**Comment by jeremoquai** [comment]
Hi again @Vinedine, and thanks for your help.

Unfortunately I already tried :

```
query {
  users(slugs: "jeremtol","Mikamaz") {
    nickname
    cards {
      slug
    }
  }
}

```
and I have an error "Syntax Error: Expected Name found String"

and also :

```
query {
  users(slugs: "jeremtol,Mikamaz") {
    nickname
    cards {
      slug
    }
  }
}

```
which returns the empty

{
  "data": {
    "users": []
  }
}

**Comment by thom-desgrippes** [comment]
Hi @jeremoquai 

You need to provide it as an array : 
```
{
  users(slugs: ["jeremtol", "mikamaz"]) {
    nickname
  }
}
```

**Comment by jeremoquai** [comment]
thanks lot for this info I will test it tomorrow 

curiously it was nowhere to be found in the dozens of pages I read
