### ISSUE TITLE
change log

### ISSUE THREAD

**Issue by doublesavonette** [sorare/api#174]
Hi @redox,

I was keen to raise a friendly complain about the lack of (maintained) change log. 

I appreciate that your team is brushing up the api, but deprecating/renaming fields without notice and without preserving the old names for some time (to allow third parties to undergo a refactoring of their code) is quite annoying. 

Probably folks like sorare data have big enough teams to cope with these unexpected changes quickly, but for the small fishes it involves a lot of time spent on maintenance.

If at all possible, could these changes be communicated with the rest of us before they are pushed? Could you open source parts of the api source code ?

Many thanks.

**Comment by redox** [comment]
Hey @doublesavonette and @juliusdanek,

thank you for raising such concern. Definitely something we need to continue to improve on.

We introduced a [Changelog](https://github.com/sorare/api/blob/master/CHANGELOG.md) a few months ago but definitely need to get better at keeping this updated in a timely manner. For sure it's important for us to be able to remove deprecated fields after some time, but we also need to ensure this doesn't impact too much our third-party users by providing them enough time to update their code.

I'll circle back with the team.

**Comment by juliusdanek** [comment]
Thank you Sylvain. Since some of us are completely dependent on the API for production level delivery to clients, it would be great to be kept in the loop here. It was great when you bundled the changes recently and informed us ahead of time so we could mitigate on our end.
