### ISSUE TITLE
lastFiveSo5AverageScore meaning

### ISSUE THREAD

**Issue by jeremoquai** [sorare/api#18]
Hi.

I thought that lastFiveSo5AverageScore was what's displayed here :

![image](https://user-images.githubusercontent.com/15834082/114047096-1763dd80-9892-11eb-90ba-1101a3a461dd.png)

but when I make this query I get 61,9

```
{
  card(slug: "cristiano-ronaldo-dos-santos-aveiro-2020-rare-29") {
    player {
      status {
        lastFiveSo5AverageScore
      }
    }
  }
}

```
I don't find any "average" field in the documentation except "So5Rules.averageScore" (which I don't think is the info I'm looking for) : does this mean that it's not what I guess it is and that I am obliged to recalculate it myself ???

Thanks.

**Comment by feikede** [comment]
From my experience that value displayed on UI is the average of the last five games - but DNPs don't count here. While the lastFiveSo5AverageScore in the API is the average of the last 5 games with DNPs counting as 0 points. That's why the lastFiveSo5AverageScore is always below the displayed bubble score.

Imo there's no field in the API for the displayed score. I am calculating it myself for my trading app.

**Comment by jeremoquai** [comment]
hi @feikede 
thanks LOT for your comment
I must admit that I gave up a little bit, considering the very lack of support from the dev team
in which language are you coding ? if you don't mind I would use some of your help to crack down several topics I was stucked on
thanks

**Comment by feikede** [comment]
Sure, when I have solutions, I'd love to share. I am programming for my sorare needs in PHP, Java Spring Boot, Typescript and Javascript.

**Comment by redox** [comment]
> hi @feikede
> thanks LOT for your comment
> I must admit that I gave up a little bit, considering the very lack of support from the dev team
> in which language are you coding ? if you don't mind I would use some of your help to crack down several topics I was stucked on
> thanks

Hopefully we can get this fixed now, we're better equipped to answer those questions; and document everything. We started and revamped our README as well as some of our Playground docs.

Thank you a lot for your help @feikede , much appreciated.

@jeremoquai I'm closing this issue as it's very old; but happy to support should you need more help.
