### ISSUE TITLE
New error with ownerable on UserOwnersWithRates

### ISSUE THREAD

**Issue by juliusdanek** [sorare/api#180]
Encountering a new error. I tried this query with a user access token that I obviously cannot share here. I have never seen this error before. Seems to be an issue on your backend?

@redox can this be prioritized? It's failing my production as I rely on the results in that ownerable field (the ethereum address) and it worked flawlessly before.

**error:**

```json
{
  "data": null,
  "errors": [
    {
      "message": "Cannot return null for non-nullable field UserOwnerWithRates.ownerable"
    }
  ]
}
```

Query:

```graphql
# Write your query or mutation here
query {
  so5Fixture(slug: "1-5-oct") {
    endDate
    id
    slug
    mySo5Rewards {
      slug
      so5Ranking {
        so5Lineup {
          so5Appearances {
            card {
              name
            }
            so5Score {
              score
            }
          }
        }
        score
      }
      rewardCards {
        quality
        card {
          player {
            slug
          }
          userOwnersWithRate {
            from
            userNonce
            transferType
            ownerable {
              ethereumAddress
            }
          }
          slug
          rarity
          season {
            startYear
          }
          name
        }
      }
      weiAmount
    }
  }
}
```

**Comment by asilbalaban** [comment]
I was using the same relation. They removed this without notice developers.

**Comment by redox** [comment]
Can you try with the non-deprecated fields (`userOwnersWithRate` and `ownerable`)?

```gql
query {
  so5Fixture(slug: "1-5-oct") {
    endDate
    id
    slug
    mySo5Rewards {
      slug
      so5Ranking {
        so5Lineup {
          so5Appearances {
            card {
              name
            }
            so5Score {
              score
            }
          }
        }
        score
      }
      rewardCards {
        quality
        card {
          player {
            slug
          }
          notContractOwners {
            from
            transferType
            account {
              owner {
                ... on User {
                  ethereumAddress
                }
              }
            }
          }
          slug
          rarity
          season {
            startYear
          }
          name
        }
      }
      weiAmount
    }
  }
}
```

**Comment by juliusdanek** [comment]
This should work. @redox your recent changes broke my entire production. This is really difficult. I would expect these deprecations to be announced beforehand so we can adjust. And at least not deprecate immediately but give a transition period of a few days. It's not just you dependent on the API anymore :-)

**Comment by redox** [comment]
> This should work.

Great to hear!

> @redox your recent changes broke my entire production. This is really difficult. I would expect these deprecations to be announced beforehand so we can adjust. And at least not deprecate immediately but give a transition period of a few days. It's not just you dependent on the API anymore :-)

Sorry to hear that @juliusdanek ; we just discussed this exact topic with the team internally: definitely a miss on our end and we'll make sure in the future that no fields get deprecated AND (removed or always 0/nil) at the same time to provide 3rd-party apps the time they need to move to the new fields.
