### ISSUE TITLE
Accept SingleSaleOffer Id vs blockchainId

### ISSUE THREAD

**Issue by justinpariente** [sorare/api#181]
Hello, 

My code to accept a singleSaleOffer based on the examples used to work but now I have a problem with the Id of the SingleSaleOffer.

I am trying to get the SingleSaleOffer Id from the card query.

For example : 
query getCardOfferId {
  card (slug: "armand-lauriente-2021-limited-320") {
  liveSingleSaleOffer {
    id
    blockchainId
  }
}
}

The answer is 
{
  "data": {
    "card": {
      "liveSingleSaleOffer": {
        "id": "SingleSaleOffer:2623563719132893640823022422623181893407",
        "blockchainId": "2623563719132893640823022422623181893407"
      }
    }
  }
}

I used to use the second part of "id" to get the offer with TransferMarket query as below but I am getting a not found error if i use the id from above request : 

  query GetOffer {    
    transferMarket {
      offer (id: " 2623563719132893640823022422623181893407 " ){
        blockchainId
        sender {
          __typename ...
            on User {
              id
              }
          }}
      }
    }

Hope this is clear !

Thanks for your help
Regards

**Comment by MichaelBornand** [comment]
Hello, I have the same issue.

**Comment by eulbat** [comment]
Hey,

Thanks for your report, I'll look into it and keep you posted

**Comment by eulbat** [comment]
Hi @justinpariente @MichaelBornand 

This is now fixed
