### ISSUE TITLE
Who can help me?

### ISSUE THREAD

**Issue by Samsuma86** [sorare/api#183]
Hello Guys,

I´am searching somebody who can do work for me with the API. Just contact me if you are interested.

**Comment by redox** [comment]
Hey @Samsuma86 , I'm not sure Github is the best place for those requests; you should try https://www.upwork.com/ or any kind of freelancing platform.

**Comment by Vinedine** [comment]
@Samsuma86 I may be able to help. How can I contact you?

**Comment by Samsuma86** [comment]
> @Samsuma86 I may be able to help. How can I contact you?

xSaminhox#1871 on discord
