### ISSUE TITLE
awayTeam & homeTeam inside Game is empty

### ISSUE THREAD

**Issue by MichaelBornand** [sorare/api#185]
Hello,

I'm trying to find which team is away/home on a specific game, but the value of this specific field seems to always be empty. Here is a quick exemple :

Query :

`{
  game(id: "092ba065-46b2-4153-a9e0-a33129068cf4") {
    awayTeam
    homeTeam
  }
}
`

result :

`{
  "data": {
    "game": {
      "awayTeam": {},
      "homeTeam": {}
    }
  }
}`

Am I doing something wrong ?

**Comment by lucasolinas** [comment]
Hi,

you need something like this

`homeTeam{
__typename
... on Club {
		name
}
... on NationalTeam {
		name
}
	}
awayTeam{
__typename
... on Club {
		name
}
... on NationalTeam {
		name
}
	}`

**Comment by lucasolinas** [comment]
Hi,

you need something like this

`homeTeam{
__typename
... on Club {
		name
}
... on NationalTeam {
		name
}
	}
awayTeam{
__typename
... on Club {
		name
}
... on NationalTeam {
		name
}
	}`
