### ISSUE TITLE
No access to GraphQL playground

### ISSUE THREAD

**Issue by Samsuma86** [sorare/api#189]
Hello guys,

I can´t open the GraphQL Website https://api.sorare.com/graphql/playground anymore. How can I fix that. Don´t no what happend.

Thanks in advance

**Comment by redox** [comment]
It works from here, did you try another browser? Also, close all opened Sorare tab to make sure there is no cookie messup.

**Comment by Samsuma86** [comment]
![image](https://user-images.githubusercontent.com/103194693/163628489-8b6b471a-b15e-4c93-ac6f-470d2331153f.png)

It doesn´t work as well. I get this message

**Comment by redox** [comment]
@Samsuma86 this very much looks like a restriction either from your network/wifi.
