### ISSUE TITLE
Don't Login

### ISSUE THREAD

**Issue by satruxag** [sorare/api#195]
Simple login don't work
       r = requests.get(f'https://api.sorare.com/api/v1/users/{email}')

but it no longer returns the CSRF-Token this is the answer.

what happened?

RESULT
`{'Date': 'Mon, 25 Apr 2022 22:37:35 GMT', 'Content-Type': 'application/json; charset=utf-8', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'x-frame-options': 'SAMEORIGIN', 'x-xss-protection': '1; mode=block', 'x-content-type-options': 'nosniff', 'x-download-options': 'noopen', 'x-permitted-cross-domain-policies': 'none', 'referrer-policy': 'strict-origin-when-cross-origin', 'vary': 'Accept, Origin', 'etag': 'W/"b67b26e7903647808daa45ae2759591f"', 'cache-control': 'max-age=0, private, must-revalidate', 'x-request-id': '6bd0835d-7fa3-4e53-91c6-abf4565d7ad5', 'x-runtime': '0.160037', 'strict-transport-security': 'max-age=63072000; includeSubDomains', 'CF-Cache-Status': 'DYNAMIC', 'Expect-CT': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"', 'Server': 'cloudflare', 'CF-RAY': '701a9069eb01a321-FCO', 'Content-Encoding': 'gzip'}`

**Comment by redox** [comment]
You shouldn’t need the CSRF token, this is only for the Sorare.com frontend. Why is it a problem?

**Comment by satruxag** [comment]
perchè quando avviare una semplice mutazione per l'inserimento a mercato di una carta ottengo questo errore. (fino a giovediva funziona regolarmente)

{'data': {'prepareOffer': {'limitOrders': Nessuno, 'errors': [{'message': 'Dovresti accedere'}]}}}

**Comment by satruxag** [comment]
the problem is simply that I can't extract the JWT Token needed for mutations anymore (it worked correctly before)

    JWT = (bb ['data'] ['signIn'] ['currentUser'] ['jwtToken'] ['token'])

JWT is blank for not logging in as cloudflare responds

**Comment by redox** [comment]
> JWT is blank for not logging in as cloudflare responds

Could you provide the code you're using to perform the `signIn` mutation and get the JWT token? Are you sure you didn't enable 2FA in the meantime and now need to patch your `signIn` code to answer the challenge?
