### ISSUE TITLE
liveSingleSaleOffer in aCardWasUpdated subscription always shows 'open': False

### ISSUE THREAD

**Issue by arctcpk** [sorare/api#196]
Since the market issue this morning, it seems like almost all `liveSingleSaleOffer` in the `aCardWasUpdated` subscription are being sent with `'open': False`, even though the offer is actually live. 

Random example: I just got card `pieter-bos-2021-rare-43` with the following `liveSingleSaleOffer`:

```
{'blockchainId': '352830533430700144843844766323986414384', 'endDate': '2022-04-28T10:57:09Z', 'id': 'SingleSaleOffer:5290d94c-f0fa-479d-9bfb-0e2a06899ec0', 'open': False, 'price': '145000000000000000', 'startDate': '2022-04-26T10:59:08Z'}
```

Per the website https://sorare.com/cards/pieter-bos-2021-rare-43?tab=cards it's a live offer though.

Is this a bug or am I missing something?

**Comment by eulbat** [comment]
Hey @arctcpk 

This is a bug, I'll work on a fix, thanks for reporting

**Comment by eulbat** [comment]
@arctcpk the issue should now be fixed, apologies for the inconvenience!
