### ISSUE TITLE
How can i get data

### ISSUE THREAD

**Issue by Brodkov** [sorare/api#198]
Hey! Tell me please. Can I get this data from the API and how. Thanks a lot!
![1](https://user-images.githubusercontent.com/104528935/165620313-58364cdf-e359-4ee8-80c4-66bbedc4514f.jpg)

**Comment by redox** [comment]
Hi @Brodkov , this is unfortunately not something our API provides. You'll need to log all the `aCardWasUpdated` event and computed it on your end: https://github.com/sorare/api/issues/80#issuecomment-1004821777
