### ISSUE TITLE
using aCardWasUpdated subscription

### ISSUE THREAD

**Issue by agiradam** [sorare/api#201]
Hey, i have two problems/questions;

When I try the code block below in the playground (https://api.sorare.com/graphql/playground) I get no results. Is this normal? I can't get results because I tried in the playground?

`subscription{
  aCardWasUpdated(owned: true, rarities: [limited]){
    slug player{
      slug
    }
    onSale
    liveSingleSaleOffer{
      price
    }
  }
}`

Second question is; how can i get latest sales with only made with direct offers? I assume i should use "aCardWasUpdated" action but i cant find exact solution. Can you write the code block should i use to? 

Thx.. take care..

**Comment by doublesavonette** [comment]
@agiradam . 
1) Check out the closed issues it is documented. 
2) Yea stream
