### ISSUE TITLE
aCardWasUpdated subscription stopped working

### ISSUE THREAD

**Issue by faridmovsumov** [sorare/api#205]
aCardWasUpdated stopped sending data this morning. Can someone please check what is wrong?

**Comment by utay** [comment]
Hi @faridmovsumov, apologies for the inconvenience. This is now resolved.

**Comment by agiradam** [comment]
aCardWasUpdated stopped sending data again? right now it is not working.

It stopped working today 08:30utc either.. then it worked again a half hour later..

**Comment by faridmovsumov** [comment]
@utay thanks for the update, do you have any plans to implement a status page where we can see updates regarding service statuses and issues.

**Comment by faridmovsumov** [comment]
Indeed as @agiradam said it is stopped again.

**Comment by utay** [comment]
Hi @agiradam @faridmovsumov, sorry again for the trouble.
The aCardWasUpdated subscription is stable again. We made several improvements since yesterday to make our websockets system more reliable.
Also, we plan to add a status page in the following weeks to share updates regarding service issues!

**Comment by faridmovsumov** [comment]
Thanks a lot, @utay 🙏 Great to hear the team is working on it.
