### ISSUE TITLE
BUG: createdAt now invalid field in Card

### ISSUE THREAD

**Issue by doublesavonette** [sorare/api#208]
Hi @redox,

Did you guys silently removed createdAt from Card? or is this a bug?

``` Caught exception: Invalid field for <DSLField Subscription::aCardWasUpdated>: <DSLField Card::createdAt>```

Cheers

**Comment by doublesavonette** [comment]
Thanks for the reply @eulbat

It is only on the subscription. I have code which pulls your schema and validate my queries/subscription against it and it throws this error at the moment. Queries work fine, subscription does not anymore.

Was wondering if you made any change to the aCardWasUpdated subscription code today on your end. Since everything was running fine for me till 4.46pm (French time) today

**Comment by doublesavonette** [comment]
Actually quite a few fields raise an issue. Card.slug, Card.canBuy, Card.grade to name only a few. Suprisingly Card.age works. If it's of any help.

**Comment by eulbat** [comment]
@doublesavonette would you mind sharing a code sample of the mutation and the validation you are performing?
I'm not able to get the error in the playground

**Comment by doublesavonette** [comment]
Hi @eulbat

I had to modify the python-gql library transport to get their dynamic query module be compatible with sorare ws. So unfortunately sharing a code sample is not straightforward as i'd need to also publish my modified transport.

The error is indeed rather strange. If I run things without the validation (that is pass a string query) things work fine. Queries and mutations also using the Card object work fine. 

Only the subscription is messed up. I'm very much puzzled as what could be the root of the problem.
