### ISSUE TITLE
Adding a new field "transferId" to notContractOwners

### ISSUE THREAD

**Issue by juliusdanek** [sorare/api#209]
Hey there,

would you be able to add a field like "transferId" to the notContractOwners? That would make life a lot easier. The transferId would be the Id of the transfer (e.g. SingleSaleOffer:8adba1b7-13e9-4697-a774-02ff5f28e756 or EnglishAuction:9c9da6d4-63f4-4952-ae52-6899d82c3fa4).

Thanks!

Julius

**Comment by eulbat** [comment]
Hey @juliusdanek 
You now have a `referenceId` field on the `OwnerType` representing the auction of offer id related to the transfer.
Let me know if that works for you!
