### ISSUE TITLE
subscription  aCardWasUpdated events: [offer_event_cancelled,offer_event_ended] - no notifications

### ISSUE THREAD

**Issue by Moreas** [sorare/api#210]
When working with the subscription aCardWasUpdated, the events offer_event_cancelled (When an offer is cancelled) and offer_event_ended (When an offer expires) are never triggered.

I have even tested a real-case scenario by creating and then cancelling an offer, nothing came up.

**Comment by Moreas** [comment]
Thank you @eulbat 
I want to compute on real time what is the best offer to purchase a player card for each rarity. If the current best offer is cancelled or expired, I need to catch that in order to update accordingly.

**Comment by eulbat** [comment]
Hello @Moreas 

The `offer_event_cancelled` should be back.

I did clean a bit more the `CardWasUpdatedEvent` list to remove the offer events that we decided to not send in the end:
- `offer_event_ended`: the `end_date` of an offer does not change, so you can schedule whatever workflow you need at that date when you receive the `opened` event
- `offer_event_rejected`: those are for direct offers which are not exposed
- `offer_event_tentatively_accepted` and `offer_event_marked_as_settlable`: those are internal events which were not very usable, you should rely on `offer_event_accepted` events.

Hope that clears things up, let me know what you think

**Comment by Moreas** [comment]
Thank you @eulbat 
I just tested it and it looks like we get the canceled offers indeed which is great!
Your solution for ended offers is fine too.

A little note though: when filtering on offer_event_cancelled I still get some offers where OnSale is true. I am not sure that it is the expected behavior.

**Comment by rbdm-qnt** [comment]
Im subscribing to this field in aCardWasUpdated subscription, but still when someone trades cards for cards and 1 or more of those cards were listed for sale, I don't get the cancel event for that sale. Did it work for you?

> Thank you @eulbat I just tested it and it looks like we get the canceled offers indeed which is great! Your solution for ended offers is fine too.
> 
> A little note though: when filtering on offer_event_cancelled I still get some offers where OnSale is true. I am not sure that it is the expected behavior.
