### ISSUE TITLE
allCards : impossible to filter => block

### ISSUE THREAD

**Issue by jeremoquai** [sorare/api#22]
Hi.

As it seems impossoble to filter directly in the query over/under a given price, or some other similar conditions, I tried to retrieve all the cards slugs and the only attributes that I need in order to perform the filter locally and then call again the API for details on the desired cards...

Unfortunately, after an undertermined amount of call, my IP has been temporarily blocked !!!

So what is the solution to perform such an action ? Is there something I am missing in the GraphQL query (as I didn't found how to add arguments to a node) ?

It would be great to have a bit of support here : you have an interesting platform, please let your users play with it.   ;-)

Thanks,

J.

poke @such @spinach (I don't know guys if you're working for sorare but you were the only ones pingable LOL)

**Comment by jeremoquai** [comment]
hi @thom-des 
thanks for your reply
as stated, the API limit makes it **impossible** to do it
any trick to bypass the limit ? it's indeed too bad that you provide an API that cannot be fully used 
thanks for letting us know
regards

**Comment by jeremoquai** [comment]
@thom-des ?

**Comment by redox** [comment]
Merging with https://github.com/sorare/api/issues/35 and will most probably work on it in the near future.
