### ISSUE TITLE
subscription aCardWasUpdated events: [offer_event_accepted] - no notifications

### ISSUE THREAD

**Issue by Moreas** [sorare/api#221]
When working with the subscription aCardWasUpdated, the event offer_event_accepted (when an offer is accepted) is never triggered. It used to work fine not long ago

Here is my code:
`subscription { aCardWasUpdated(events:[offer_event_accepted]) { slug owner { ownerable { ... on User { nickname } } from price transferType } } }`

**Comment by MichaelBornand** [comment]
Hey,

Same thing with the offer_event_minted as well. I'll assume all the events filters are not working anymore.

**Comment by Moreas** [comment]
As far as I know:
- **auction_event_successfull** works well
- **offer_event_cancelled** seems to be working pretty well (except that the feed contains some offers that have still OnSale=true)
- still big issue with **offer_event_accepted** where nothing comes up
@eulbat @redox , any chance to look at it?

**Comment by eulbat** [comment]
Hi @Moreas 

I just tried the sample code you provided and I'm able to get `offer_event_accepted` events.
Do you reproduce consistently?
