### ISSUE TITLE
subscription in line fragment bug

### ISSUE THREAD

**Issue by doublesavonette** [sorare/api#225]
Hi @eulbat 

In line fragment for Team stopped working on my end. Also tested with the template subscription code, same problem. Here is a minimal example:

```
subscription onAnyCardUpdated { aCardWasUpdated {
  team {
  	... on Club {
      id
      slug
  	}
  	... on NationalTeam {
      id
      slug
  	}
  }
}
}
```

error returned:
```{'result': {'data': None, 'errors': [{'message': 'Duplicated field: id', 'locations': [{'line': 1, 'column': 74}]}, {'message': 'Duplicated field: slug', 'locations': [{'line': 1, 'column': 77}]}]}, 'more': True}```

However running the subscription below works:
```
subscription onAnyCardUpdated { aCardWasUpdated {
  team {
  	... on Club {
      id
      slug
  	}
  }
}
}
```

I am wondering if I am doing something blatantly wrong or if there is indeed a problem.

Cheers

**Comment by eulbat** [comment]
Hi @doublesavonette 

thanks for reporting, we'll work on fixing that as it should indeed be valid

**Comment by doublesavonette** [comment]
np. If at all possible could you drop a line here when the issue is solved?

Many thanks.

**Comment by eulbat** [comment]
will do!

**Comment by eulbat** [comment]
@doublesavonette it should now be solved, could you please confirm everything is ok on your end?

**Comment by doublesavonette** [comment]
@eulbat Thanks for the heads up!

All working now. Good stuff.
