### ISSUE TITLE
subscription aCardWasUpdated in Playground not responding

### ISSUE THREAD

**Issue by jeremoquai** [sorare/api#23]
Hi.

Was simply testing the subscription aCardWasUpdated in Playground :

```
subscription {
  aCardWasUpdated {
    slug
  }
}

```
I get the "Listening …" and the wheel, but nothing ever appears in the right frame : why ?

Thanks !

**Comment by thom-des** [comment]
Hi,

Subscriptions are not available on the playground because the WS endpoint is not on the default /graphql path used by the playground.
The right endpoint is wss://ws.sorare.com/cable.

**Comment by jeremoquai** [comment]
ok @thom-des thanks for the info i will try to make it work

**Comment by cmenetrier** [comment]
Hi @thom-des,
I've also issue while trying to subscribe to the aCardWasUpdated endpoint.
I can reach the WSS server correctly but when sending the following message :

`{"query":"subscription{aCardWasUpdated{slug __typename}}","variables":null,"operationName":null}`

The reply is : `{"type":"disconnect","reason":"invalid_request","reconnect":false}`

Could you assist in what I'm doing wrong ?

**Comment by rustvalve** [comment]
Hi guys, i have the same issue with aCardWasUpdated. What is the right WS endpoint? When i'm trying to connect 'wss://ws.sorare.com/cable' as @thom-des said it told me "Refused to connect to 'wss://ws.sorare.com/cable' because it violates the following Content Security Policy directive: "connect-src 'self' ..."

**Comment by Luca286** [comment]
I'm trying to subscribe to a aCardWasUpdated using the WS endpoint provided in the message above but it seems to not work properly. Are the subscriptions available?

**Comment by Eranud** [comment]
> I'm trying to subscribe to a aCardWasUpdated using the WS endpoint provided in the message above but it seems to not work properly. Are the subscriptions available?

same question :)

**Comment by SegPro** [comment]
Same question I don't understand how use the WS endpoint provided ?
Replace in URL field ? But it doesn't work

**Comment by Saifer707** [comment]
Hi, same question by me.

I can call WS endpoint, but i receive only a dict (i'm using Python) with key-value pair like `"type":"welcome"`.

How can i check for card update or offer update? Is there a channel or something for specifying subscription?

**Comment by rbdm-qnt** [comment]
Were you ever able to solve this issue? Whatever I try I only get "Auth Error" and the following JSON:

{'reason': 'invalid_request', 'reconnect': False, 'type': 'disconnect'}

**Comment by mbh86** [comment]
Hi @rbdm-qnt, I encounter the same issue. Have you found a workaround ?

**Comment by redox** [comment]
@rbdm-qnt @Saifer707 @SegPro @Eranud @Luca286 https://github.com/sorare/api/pull/84 should help, I'll work on making the Playground work with subscriptions; but the answer from @thom-des is still valid:



> Subscriptions are not available on the playground because the WS endpoint is not on the default /graphql path used by the playground.
> The right endpoint is wss://ws.sorare.com/cable.

**Comment by redox** [comment]
@utay introduced a new playground and subscriptions are now working there.
