### ISSUE TITLE
Query has complexity of X which exceeds max complexity

### ISSUE THREAD

**Issue by faridmovsumov** [sorare/api#231]
I am using APIKEY to send my query but it still gives me the following error. 2805 < 5000 so I assume something wrong here.

<img width="888" alt="image" src="https://user-images.githubusercontent.com/1541412/172993970-e4538130-1fb3-4b08-b014-83035fbacf7f.png">

**Comment by doublesavonette** [comment]
@eulbat 

Hey,

I am getting similar issues with the websocket using either the TypeScript or Python scripts.

Could you guys help? Possibly doing something wrong but if so the error received (similar to what @faridmovsumov pointed) is not helping debug the problem.

Cheers

**Comment by faridmovsumov** [comment]
It seems like APIKEY is not being taken into account somehow.

**Comment by SorareAPIUser** [comment]
What is the syntax to add the APIKEY field in the subscription (e.g. the aCardWasUpdated one) scripts?

**Comment by faridmovsumov** [comment]
@SorareAPIUser you can find it in Readme 

https://github.com/sorare/api#javascript

<img width="860" alt="image" src="https://user-images.githubusercontent.com/1541412/173197772-0c32380c-50c2-46b1-a762-adbe771a306c.png">

**Comment by SorareAPIUser** [comment]
Thanks for the reply, but I am actually after the Python solution. Do you know where to input the APIKey in the Python subscription example given?

**Comment by feikede** [comment]
It works up to nested level 10 and complexity 5000 when you use a bearer token in your requests.

**Comment by faridmovsumov** [comment]
@SorareAPIUser no idea about how to do that in Python. 

@feikede interesting, are you using token and API key or only token?

**Comment by feikede** [comment]
@faridmovsumov  Only token and AUD

**Comment by feikede** [comment]
@faridmovsumov See here: https://github.com/sorare/api#graphql-complexity-and-depth-limits

> Authenticated calls (with a JWT Token or an API key) have the following limits:
>     depth 10    complexity: 5000
>

**Comment by faridmovsumov** [comment]
Indeed I am using only APIKEY but somehow it is not being taken into account. 

<img width="465" alt="image" src="https://user-images.githubusercontent.com/1541412/173239798-cd7d345c-06df-47bd-a991-71a5d4ad3e46.png">

**Comment by faridmovsumov** [comment]
I also shared details with @redox regarding this so they are aware of the situation.

**Comment by redox** [comment]
hey @faridmovsumov & @doublesavonette; this is surprising. I would like to make sure your API keys are actually valid. Do you mind emailing me the **first and last** 4 digits of the key? sylvain@...

**Comment by doublesavonette** [comment]
@redox thanks. Just sent

**Comment by faridmovsumov** [comment]
@redox I also sent all details in a fresh email.

**Comment by redox** [comment]
@faridmovsumov @doublesavonette we found an edge case/bug with the subscription & the depth limiter; we'll fix it.

**Comment by redox** [comment]
This should now be fixed!

**Comment by faridmovsumov** [comment]
@redox unfortunately I am still getting the error :(

**Comment by feikede** [comment]
@redox I can confirm this issue with OAuth-Bearer. While with JWT-Bearer and AUD I can request till complexity 10, I can only request up to complexity 5 with OAuth token.

So, the signIn mutation login gives me better limit than the OAuth login. Is this by design or is it a bug?

Your doc says: 
```
Anonymous calls have the following limits:

    depth: 2
    complexity: 500

Authenticated calls (with a JWT Token or an API key) have the following limits:

    depth 10
    complexity: 5000

```

But what about the OAuth Token?

**Comment by kalinasviatoslav** [comment]
[feikede](https://github.com/feikede)

Could you please send the code sample of you sending JWT-Bearer and AUD in the headers of WebSocket? I want to be able to execute query 10 depth. 

I've tried to send JWT-Bearer and AUD differently, but all I got  when executing query deeper than 5 depth is 
"an Invalid operation, authorized: subscription."

Looking forward to hearing answer from you.

**Comment by feikede** [comment]
@kalinasviatoslav It's perfectly documented here: https://github.com/sorare/api#user-authentication
