### ISSUE TITLE
Account id changed for cards

### ISSUE THREAD

**Issue by faridmovsumov** [sorare/api#238]
Hello,

I noticed today that account_id information changed for cards

Example card slug: "vincenzo-grifo-2021-rare-16" 

Before: Account:starkware_0x072b594713a7e025e309fe53362fc7fedb3d95715d8811950727c9c24745cb37
Now: Account:45bdc775-b6f8-4107-aa7c-77c0a650cfee

Previously I was detecting card owners by matching account id with the user's starkKey but now this logic is broken. 

<img width="1162" alt="image" src="https://user-images.githubusercontent.com/1541412/177615227-d0ae8853-e3a2-47a9-be7c-d22e5ed6fba9.png">

I am wondering if this is a permanent change or just a bug?

If permanent change I guess it is because of Baseball data structure, could you please help me understand how can I match card address with an account of the user?

**Comment by redox** [comment]
I'm investigating; baseball isn't affecting this.

**Comment by faridmovsumov** [comment]
Thanks for sharing @eulbat meanwhile I also discovered I can build old format by combining blockchain + address information. I think it will be a more safe option in long term. 

<img width="1163" alt="image" src="https://user-images.githubusercontent.com/1541412/178009376-3e2943c6-4af6-446c-a645-ac3bfce05ebf.png">

**Comment by eulbat** [comment]
Perfect, closing this issue then!
