### ISSUE TITLE
Error when trying to login

### ISSUE THREAD

**Issue by CharlesOnAir** [sorare/api#24]
Hello,
I have an error when trying to access Sorare's API.

This is my code : 
`$cookieJar = CookieJar::fromArray([
            '_sorare_session_id' => $sorareSession
        ], 'http://127.0.0.1');

        $requests_options =
            [
                'cookies' => $cookieJar,
                'headers' =>
                [
                    'x-csrf-token' => $csrf
                ]
            ];

        $client2 = new \GuzzleHttp\Client();
        $response = $client2->request(
            'POST',
            $baseUrl . 'users/sign_in.json',
            $requests_options
        );`

And I have this error : 
`Client error: POST https://api.sorare.com/users/sign_in.json resulted in a 401 Unauthorized response:
{"error":"invalid"}`

Thank's for help

(I use Http Guzzle)

**Comment by redox** [comment]
hey @CharlesOnAir , I've revamped the authentication documentation in https://github.com/sorare/api ; let me know but I'm quite sure this will now work. Also, we've been removing this cookie-based authentication flow, really not standard.

Hope this helps!
