### ISSUE TITLE
How to fetch player thumbnail image from API?

### ISSUE THREAD

**Issue by faridmovsumov** [sorare/api#241]
How can I get a square image version of player images from API?

<img width="1262" alt="image" src="https://user-images.githubusercontent.com/1541412/177981181-07f850aa-2382-4ac6-b82f-2d6bae9e5f69.png">

**Comment by thom-des** [comment]
Hi,
This is a derivative called "avatar"

```
query {
  card(slug: "kylian-mbappe-lottin-2020-rare-1") {
    slug
    pictureUrl(derivative: "avatar")
  }
}
```
