### ISSUE TITLE
removal of limitOrders breaks bidAuctionWithEth.js example.

### ISSUE THREAD

**Issue by minimumnz** [sorare/api#244]
am now seeing this error with the current example: 
ClientError: Field 'limitOrders' doesn't exist on type 'BundledAuction': {"response":{"errors":[{"message":"Field 'limitOrders' doesn't exist on type 'BundledAuction'",

Is there a plan to update the example? I can't tell what the replacement is from the current documenation.

**Comment by eulbat** [comment]
Hi @minimumnz 

Thank you for pointing that out, I'll update the documentation, in the meantime you can have a look at the `prepareBid` mutation in the playground, which behaves the same.

**Comment by eulbat** [comment]
hi @minimumnz 

The documentation has now been updated to reflect the removal of `limitOrders`
