### ISSUE TITLE
Baseball Graph Playground don't work

### ISSUE THREAD

**Issue by juliusdanek** [sorare/api#249]
@redox @eulbat the playground doesn't work. https://api.sorare.com/mlb/graphq. See error below.

![Screenshot 2022-07-20 at 10 54 30](https://user-images.githubusercontent.com/9576231/179940878-89c669da-6935-446b-a385-ce3c30b46b4f.png)
l

**Comment by eulbat** [comment]
Hi @juliusdanek 

The MLB playground url is [https://api.sorare.com/mlb/graphql/playground](https://api.sorare.com/mlb/graphql/playground)

**Comment by juliusdanek** [comment]
Ok. I took the link from the documentation in this repo :)

**Comment by juliusdanek** [comment]
@eulbat the most important one for me is the `allCards` endpoint. There is no `allToken` endpoint in either of those two.

**Comment by juliusdanek** [comment]
I need to try them out but that should work. `allTokens` and `allCards` for Baseball will be the most important.

**Comment by eulbat** [comment]
Closing this one to merge with [#250](https://github.com/sorare/api/issues/250)
