### ISSUE TITLE
Signature

### ISSUE THREAD

**Issue by maxmax96** [sorare/api#25]
How do I sign an eth transaction in Python? I'm talking about a sendEth signature when sending a direct offer, but would be great to know others too. I am able to make the offer through the API but looking at the signature example here I can't figure out what is being encoded in the signature

**Comment by feikede** [comment]
I am also looking for how to create the signature in [mutation CreateSingleSaleOffer input signatures.sendInternalCards] - could you pls explain what we need to sign here and with what algo - thanks

P.S. and is the dealId in that input just a random 42-digit Integer?

Thanks, Rainer

**Comment by doublesavonette** [comment]
@maxmax96 @feikede did you get any luck with that? Thanks!

**Comment by SebastienLouis** [comment]
@feikede @doublesavonette Did you understand what is `dealId` provided in SingleSaleOffer payload ? I don't understand where I can find this data...

**Comment by redox** [comment]
We've revamped our documentation and it should be now clearer to know how/what to sign. It comes with JS examples. Should you write some python code @maxmax96 or anyone, I would love to embed those code samples in this repo.

See https://github.com/sorare/api#examples
