### ISSUE TITLE
allCards endpoint in Baseball query

### ISSUE THREAD

**Issue by juliusdanek** [sorare/api#250]
Hey @eulbat, will you add an `allCards` endpoint for Baseball? There is also no `transferMarket` endpoint and there are no subscriptions.

**Comment by redox** [comment]
Hey @juliusdanek we'll work on this shortly.

**Comment by juliusdanek** [comment]
Hi @redox , thank you. Those filter capabilities would be very important, especially the ability to filter collectionNames (Football vs. Baseball). But also rarity, serial number, position, etc.!
