### ISSUE TITLE
Missing stats in So5Score

### ISSUE THREAD

**Issue by ZozoozoZ** [sorare/api#262]
When querying for So5Score, not all stats type are returned. For instance for antonio-adan-garrido on game against Boavista, the stat 'accurate_pass' is not returned by the query while he obviously made some pass during the game (35 actually per soradata). 

Is it normal ?

```
query so5Score($id: ID!) {
    node(id:$id) {
        ... on So5Score {
            __typename
            id
            position
            score
            scoringVersion
            detailedScore {
                __typename
                category
                points
                stat
                statValue
                totalScore
            }
        }
    }
}
```
{
"id":"So5Score:2793b6aa-0086-4b06-be4a-8470b20d86f3"
}
![image](https://user-images.githubusercontent.com/92556242/181916515-b15da698-811a-4cd6-b734-1f580d811034.png)

**Comment by juliusdanek** [comment]
@eulbat @redox I have noticed the same. I assume the `detailedScores` only returns those scores that are relevant to the scoring matrix at that point in time. 

Would you be able to start returning all the stats for all the players? That way we can more easily adjust to changes in the scoring matrix (such as new stats being used or stats being dropped).

The way it's currently designed, only SorareData can accurately access the points of the new scoring matrix.

Thanks!

Julius

**Comment by ZozoozoZ** [comment]
@redox @eulbat is it possible to have the full scoring history available throughout the graphql API in order to avoid being dependent on SorareData when there is a scoring matrix change ?

**Comment by such** [comment]
This should already be available on so5Score.playerGameStats

**Comment by juliusdanek** [comment]
Hey @such, they actually aren't. For example, the successful last third passes are not in the `playerGameStats`. Do you want me to list all the stats needed?

**Comment by ZozoozoZ** [comment]
@such : any workaround, idea regarding @juliusdanek last comment ?
