### ISSUE TITLE
Cannot return null for non-nullable field SingleSaleOffer.card

### ISSUE THREAD

**Issue by ottopic** [sorare/api#266]
Why I get error with this request?

`

     query ListLastSingleSaleOffers {
      transferMarket {
        singleSaleOffers(last: 100) {
          nodes {
            id
            card {
              slug
              age
              name
              rarity
              pictureUrl
              cardEdition {
                name
                displayName
              }
            }
            price
          }
        }
      }    
    } `

**Comment by using-system** [comment]
There is another open issue for that : https://github.com/sorare/api/issues/253
