### ISSUE TITLE
Get So5Scores with specific position

### ISSUE THREAD

**Issue by Hadevmin** [sorare/api#267]
Hi,

I post this issue because I don't find how get the so5scores for a player which have change position.
For my example I use this request:

```
query score($slug: String!) {
  card(slug: $slug) {
    player {
      allSo5Scores {
        nodes {
          position
          score
        }
      }
    }
  }
}
```

I have this return: 
```
{
  "data": {
    "card": {
      "player": {
        "allSo5Scores": {
          "nodes": [
            {
              "position": "Midfielder",
              "score": 45.9
            },
            ...
```

The problem is for this player: {"slug": "tae-hwan-kim-1989-07-24-2020-rare-67"}
He is a midfielder but he have card which are defender.

I would like to know, how can I request the api to get the score of this player, not like a midfielder but a defender.

Thanks you for your help

**Comment by aspin75** [comment]
I have the same problem, I need the points of all the positions that exist for a player.

**Comment by Hugo-Hache** [comment]
We introduced a `position` argument on `PlayerGameStats.so5Score`. With it you should be able to retrieve the score of the other position you are interested in.

**Comment by Hadevmin** [comment]
@Hugo-Hache Great work, it works perfectly! Thanks a lot!

**Comment by aspin78** [comment]
@Hugo-Hache Thanks a lot.

Are you going to calculate the L5/L15 for each position? To play "specialist" it is important.

**Comment by Hadevmin** [comment]
@aspin75 I don't understand the purpose of doing this. But you can do this on your side.

**Comment by Hadevmin** [comment]
@Hugo-Hache Do you plan to use actual card stats based on card position(not player position) to calculate L15 scores to allow the card to play in an underdog tournament?

**Comment by Hugo-Hache** [comment]
@Hadevmin It's indeed an item on our roadmap, but not a high priority one. When we'll do it we'll probably need for our clients to expose the L5/L15 of the different positions in GraphQL, so it will be accessible to you as well.

**Comment by aspin78** [comment]
Hello,
Now that you have implemented on sorare, how can we have lastFifteenSo5AverageScore by position in the api?
thx

**Comment by such** [comment]
Hello,

You can use player.averageScore field in the API that takes an optional position as argument

**Comment by aspin78** [comment]
Hello,

Thank you.

I would like to retrieve the L5/L15 of all the posts that exist in a single query.

Unfortunately if I put several lines it doesn't work. 

What can I do?

Thank you.
aspin78

**Comment by such** [comment]
what's a post?

**Comment by aspin78** [comment]
sorry for the mistake.

some players already have a card with the 3 positions, I will have to make 6 requests to get L5/L15 of each position?

It would be more efficient to have the L5/L15 in a single request for all the card positions that exist.

Thank you,
Aspin78

**Comment by juvamine7** [comment]
Hi @aspin78,
I had the same problem as you but found a workaround.
You can try something like this :

###  
        ... on Player {
          last5Avg_Mid: averageScore(position: Midfielder, type: LAST_FIVE_SO5_AVERAGE_SCORE)
          last15Avg_Mid: averageScore(position: Midfielder, type: LAST_FIFTEEN_SO5_AVERAGE_SCORE)
          last5Avg_Def: averageScore(position: Defender, type: LAST_FIVE_SO5_AVERAGE_SCORE)
          last15Avg_Def: averageScore(position: Defender, type: LAST_FIFTEEN_SO5_AVERAGE_SCORE)
        }

It will return the following : 
### 
    "last5Avg_Mid": 43,
    "last15Avg_Mid": 45,
    "last5Avg_Def": 52,
    "last15Avg_Def": 51

Best

**Comment by aspin78** [comment]
thank you very much
