### ISSUE TITLE
API KEY

### ISSUE THREAD

**Issue by oklotz** [sorare/api#271]
Hello

I would like an API KEY.
How can i do to get one please?

Regards

**Comment by using-system** [comment]
https://help.sorare.com/hc/en-us/articles/4403907337105-Can-I-get-access-to-Sorare-s-API-

**Comment by oklotz** [comment]
My projet is :
- to develop a system to help sorare user to build their teams for game weeks with the best player at a moment (depending criterias : age,....)  
- to centralize and show information in a different form to be more intuitive dashbord to sorare's users to take decision to select a player (potentialy dashbord customer per sorare's user)

It is the base line. I think and I hope the projet will be evolved with users returns.

Today it is complicate to do that because the nb of request and the complexity of request is limited.

I would like use the URL : https://api.sorare.com/graphql

Many Thanks

**Comment by utay** [comment]
@oklotz Sorry for the delay here, please send a ticket to support@sorare.com (if not done already) and we will provide you with an API key
