### ISSUE TITLE
so5 ineligible 

### ISSUE THREAD

**Issue by kykp** [sorare/api#279]
Good afternoon, could you tell me where you can find the attribute of the player's readiness to cover so5.
Thank you a lot!
![Screenshot_4](https://user-images.githubusercontent.com/53507297/187067417-ff98271e-66a1-4edd-93c9-40e9afdc5504.jpg)
?

**Comment by Tradetechnique** [comment]
To my knowledge, there is no such info in the api.
You have to check if the player's current club has at least 1 competition among the competitions covered by Sorare.

**Comment by jmaupoux** [comment]
I'm using openForGameStats for this

It seems to work pretty well so far

**Comment by kykp** [comment]
> To my knowledge, there is no such info in the api. You have to check if the player's current club has at least 1 competition among the competitions covered by Sorare.

But we have players like a https://sorare.com/players/nikos-michelis , he is a player fC [CD Mirandés](https://sorare.com/clubs/mirandes-miranda-de-ebro) , and his points count, as well as Leicester players, the club does not participate in co5, and some players do. And totenham ...
