### ISSUE TITLE
Can not get all directSentOffers on signInMutation (currentUser)

### ISSUE THREAD

**Issue by big-javascript-fan** [sorare/api#29]
Currently I am in need of getting all directSentOffers which I made before.
I have used signInMutation to sign in and try to get all directSentOffers under `currentUser` schema.
But it only return maximum 100 offers which I sent before.

Are there any way for me to get all these offers with offset and amount (first or last option)?

This is very important for me to make some calculation and analytics with my bid so hope to get any updates over this.

**Comment by thom-des** [comment]
Hi,
`directOffersSent` has been deprecated in favor or `directOffers(direction: SENT)` which support pagination.
