### ISSUE TITLE
createdAt field in the baseball API playground causes an error

### ISSUE THREAD

**Issue by jeremyallencpa** [sorare/api#293]
I have attached two screenshots: 1) the first is a query using the baseball playground which includes **createdAt** as well as the related error, and 2) the same query as the first, without createdAt (no errors on this one).

For reference, here is the query I am running which includes **createdAt**:

`{
  baseballCards(slugs: ["yonathan-daza-19940228-2022-rare-25"]) {
    id
    cardLevel
		slug
    assetId
    fullImageUrl
    serialNumber
    xp
    seasonBonus
    rarityBonus
    xpBonus
    createdAt
    player {
      id
      birthDate
      displayName
      shirtNumber
    }
    positions
    rarity
    team{
      id
      name
      market
    }
  }
}`

![F7CAD1B3-ED81-4F58-85D0-46B53EFDD8A0](https://user-images.githubusercontent.com/55819793/191728986-b742c277-5a09-432b-9f21-5681b4e50b1d.jpeg)
![11405523-AEB5-4EFF-8223-7544BEFF36EE](https://user-images.githubusercontent.com/55819793/191729040-ad6b8445-1548-449d-b93c-90dce5e6e760.jpeg)

**Comment by davidbyttow** [comment]
Hi @jeremyallencpa, thanks for the report. This field should actually never have been introduced, and so I am going to remove it, as it never worked. :)

**Comment by davidbyttow** [comment]
This has been removed
