### ISSUE TITLE
How to get all cards of a player?

### ISSUE THREAD

**Issue by nachoroncero** [sorare/api#298]
Hello,

I am trying to get all limited cards of an existing player, but I only get 50.

How could I get all of them. I guess it is using a cursor, but I do not know how to implement it

`query = gql(
        """
        query ($slug: String!, $cursor: String){ 
            player(slug: $slug){ 
                cards(rarities: limited, after:$cursor){ 
                    nodes { 
                        priceRange{
                            max
                            min
                            }
                        publicMinPrice
                        privateMinPrice
                        } 
                    } 
                } 
            }
    """
        )`

**Comment by redox** [comment]
We have some docs here: https://github.com/sorare/api#pagination and here an example to iterate over all the card of a user, which is fairly similar: https://github.com/sorare/api/blob/master/examples/allCardsFromUser.js

You should rely on `pageInfo { endCursor }`
