### ISSUE TITLE
Access with my API Key

### ISSUE THREAD

**Issue by nachoroncero** [sorare/api#299]
Hello,

I have an API Key to access, but I do not know why it seems like I am not using any key since my rate limit is low.

What is the code to access? Or how should I pass the key to the server?

Thank you!

**Comment by redox** [comment]
What does your code look like? Maybe you're not passing the header correctly? Docs is here: https://github.com/sorare/api#rate-limit

**Comment by nachoroncero** [comment]
I am working with Python.
` transport = AIOHTTPTransport(
        url="https://api.sorare.com/graphql",
        headers = {"Authorization":sorare_token}
    )

    client = Client(transport=transport)`

This is my code, where sorare_token is the api token received from Sorare.

Thank you for answering
