### ISSUE TITLE
Null card edition

### ISSUE THREAD

**Issue by ZozoozoZ** [sorare/api#300]
Hello,

Some card have a null card edition (see print screen). The graphql scheme of the property allow null values, but is it normal ?

Regards,
Zoz

![image](https://user-images.githubusercontent.com/92556242/193032960-5f7c37c9-7c0d-4b94-a850-708a77488d08.png)

**Comment by aspin78** [comment]
Yes cardEdition is @deprecated

now use : customCardEditionName

**Comment by ZozoozoZ** [comment]
Yes, clear thanks. Zoz
