### ISSUE TITLE
HTML5 based third party game:  no 'Access-Control-Allow-Origin' header when requesting Api

### ISSUE THREAD

**Issue by theaspirational** [sorare/api#31]
HI! 
How can I make requests to the Api if my the game is on html5, and now I get "No 'Access-Control-Allow-Origin' header" message.

**Comment by sirmelo** [comment]
Avez-vous trouvé une solution pour ce problème?

**Comment by theaspirational** [comment]
> Avez-vous trouvé une solution pour ce problème?

unfortunately not, I postpone the development of the game.  Are you also faced with this problem, are you also developing a third party html5 game using sorare cards?

**Comment by sirmelo** [comment]
Non, je développe un outil pour aider les managers à composer des équipes.
Le code est prêt mais je n'arrive pas à contourner le problème CORS.

Le mer. 8 déc. 2021 à 02:55, Vasyl Dovhanchyn ***@***.***> a
écrit :

**Comment by redox** [comment]
Duplicate of https://github.com/sorare/api/issues/33
