### ISSUE TITLE
how to buy a card in sale throw API?

### ISSUE THREAD

**Issue by oklotz** [sorare/api#311]
Hello,

How can I buy a card in sale throw API? Some exemple exist to send offer but I doesn't see to buy a card currently in sale.
How can i do that please?

Best regards

**Comment by redox** [comment]
This is documenting as [Accepting Offers](https://github.com/sorare/api#accepting-offers). Good luck!

**Comment by insec0x** [comment]
Hi redox,

this is working for accepting direct offer, is it possible to autobuy a card from secondary market ?
For example: buying mbappe limited if some1 list him under 400$

thank you
