### ISSUE TITLE
signLimitOrder Python

### ISSUE THREAD

**Issue by krzsqbjxes** [sorare/api#312]
Are there any public examples of someone converting the signLimitOrder function to python?

**Comment by IDunnoSure** [comment]
To my knowledge there isn't any example code for this. It would be greatly appreciated though as it appears a lot of the community are having issues doing this in Python - myself included

**Comment by utay** [comment]
Hi @krzsqbjxes @IDunnoSure, we have no written examples for this at the moment but it should be doable by using the [Starkware python library](https://github.com/starkware-libs/starkex-resources/tree/master/crypto/starkware/crypto/signature), especially [`sign`](https://github.com/starkware-libs/starkex-resources/blob/master/crypto/starkware/crypto/signature/signature.py#L120) and [`get_limit_order_msg`](https://github.com/starkware-libs/starkex-resources/blob/master/crypto/starkware/crypto/signature/starkex_messages.py#L28). You can have a look at https://github.com/sorare/crypto/blob/master/src/index.ts#L173 to see how it's done in Typescript with the equivalent functions

**Comment by djizus** [comment]
You can also use the JS library directly in python by using muterun_js, like this :
`responseJS = muterun_js('sign.js', parameters)`

Then decode the output in python :
`starkSignatures[0]["data"] = responseJS.stdout.decode("utf-8")`

**Comment by nachoroncero** [comment]
Hello @djizus ,

I am trying to code this in Python too and I do not have Javascript knowledge...
Could you explain a little bit more the solution you propose? What are the parameters and what does muterun_js do?

Thank you for your help

**Comment by djizus** [comment]
@nachoroncero Muterun_js just executes a javascript script in python and you get the output in stdout, you can get more info [here ](https://stackoverflow.com/questions/53045737/get-output-from-muterun-js-to-python)

For the parameters, let's take an example following the doc [here](https://github.com/sorare/api#accepting-offers).

In this example, the parameters for signing a limitOrders are :
```
amountBuy
amountSell
expirationTimestamp
nonce
tokenBuy
tokenSell
vaultIdBuy
vaultIdSell
```

You need to create them in python and pass them in the js script, it can be done by concatening all the fields in a string like this :
`parameters = yourprivatekey + " " + amountBuy + " "  + amountSell + " "  + expirationTimestamp + " "  + nonce " "  + tokenBuy + " "  + tokenSell + " "  + vaultIdBuy + " "  + vaultIdSell`

Then, the JS part. You have to install the package @sorare/crypto from the documentation [here](https://github.com/sorare/crypto).

Once done, you can create the JS file sign.js which should look like this if you sent the parameters in a single string like above :
```
const { signLimitOrder } = require("@sorare/crypto");
const crypto = require("crypto");

var privateKey = "";
var signature = "";
var limitOrder = {};

privateKey = process.argv[2];

var limitOrder = {
  amountBuy: process.argv[3],
  amountSell: process.argv[4],
  expirationTimestamp: process.argv[5],
  nonce: process.argv[6],
  tokenBuy: process.argv[7],
  tokenSell: process.argv[8],
  vaultIdBuy: process.argv[9],
  vaultIdSell: process.argv[10],
};

var signature = JSON.stringify(signLimitOrder(privateKey, limitOrder));
console.log(signature);
```

Back to python, you call the function and get the output like this :
```
responseJS = muterun_js('sign.js', parameters)
signatureData = responseJS.stdout.decode("utf-8")
```

Now you can build the acceptOfferInput in python and send the GQL request :
```
starkSignatures = [{}]
starkSignatures[0]["data"] = signatureData 
starkSignatures[0]["nonce"] = nonce
starkSignatures[0]["expirationTimestamp"] = expirationTimestamp
starkSignatures[0]["starkKey"] = starkKey
acceptOfferInput = CaseInsensitiveDict()
paramsAccept = {
  "input": {
  "blockchainId": dealId,
  "starkSignatures": starkSignatures
  }
}
respAccept = GQLclient.execute(AcceptOffer, variable_values=paramsAccept)
print(respAccept)
```

And it's done ! Keep in mind it'll obviously be slower than native python or native js but it works.

**Comment by nachoroncero** [comment]
@djizus wow, thank you very much for taking time for the explanation! It has been really helpful. 

It all looks great, but, sorry for the dummy question... I do not know how to install sorare/crypto since I am working with Python. I mean, do I need to download something extra to install a javascript library? Because I have been trying it, and found some info about npm, but I do not get how to do it in my case...

Thank you and sorry for the question

**Comment by badrghilani** [comment]
Hello @nachoroncero ! Can you share the bit of code in Python you used to create the signature ? 
I am facing issues using @sorare/crypto from the js file. It seems I cannot load the module using const { signLimitOrder } = require("@sorare/crypto");

Any help would be very appreciated
