### ISSUE TITLE
allNFTs not returning any data for NBA tokens

### ISSUE THREAD

**Issue by juliusdanek** [sorare/api#315]
Hey @redox / @eulbat the allNFTs endpoint isn't returning any data for NBA tokens. They are already showing up in the various subscriptions but aren't available in `allNFTs` endpoint.

Would be great to add them! 

```graphql
query {
  tokens {
    allNfts(sport: NBA) {
      edges {
        node {
          slug
        }
      }
    }
  }
}
```

**Comment by redox** [comment]
Thanks for raising this here @juliusdanek, this will be opened today.

**Comment by redox** [comment]
This just got deployed!

**Comment by juliusdanek** [comment]
Confirmed! Thank you :)
