### ISSUE TITLE
Many links in the documentation aren't working

### ISSUE THREAD

**Issue by juliusdanek** [sorare/api#316]
These links do not exist:

- https://api.sorare.com/sports/graphql
- https://api.sorare.com/graphql

Can you update them to the correct links? Might confuse new users. @eulbat

**Comment by Hadevmin** [comment]
Hi @juliusdanek 
There is no problem with these URL. They are the ones to use if you want to use the API, and it works very well. I use it daily...

**Comment by juliusdanek** [comment]
<img width="1440" alt="Screenshot 2022-10-22 at 18 19 58" src="https://user-images.githubusercontent.com/9576231/197350304-d08b86fa-fcab-4c

<img width="1552" alt="Screenshot 2022-10-22 at 18 20 14" src="https://user-images.githubusercontent.com/9576231/197350319-d20ee721-9575-49e6-8b5d-d114f4f311a4.png">
62-89bc-ddb30581c1d6.png">

This is what I get when I access them.

**Comment by Hadevmin** [comment]
@juliusdanek 
I assume you only made a classic GET request from your browser. So it's normal that it does answer 'Not found'.
You have to send a graphql request to get a correct answer. You can find various examples depending on the programming language you master.
If you want to use the online IDE, you have to access the API URL followed by '/playground'
example: https://api.sorare.com/sports/graphql/playground

**Comment by juliusdanek** [comment]
Thanks, I am using those APIs already. I just found it to be very confusing to have the endpoints as links in the documentation. I would expect to go to the API immediately (where do also show those endpoints). Will close my comment for now but might make sense to make it explicit for newcomers to the API.

**Comment by Hadevmin** [comment]
I can understand that this is confusing because they provide an online IDE. But in most API documentation, this address is given explicitly in the first lines of the documentation. This is the basis for communicating with the project and for feeding its code by reading the documentation. 
Don't be surprised to see the same thing on other projects.
