### ISSUE TITLE
Getting all so5scores: first, last, everything 

### ISSUE THREAD

**Issue by Godt99** [sorare/api#32]
I'm trying to get all so5scores for a given player but can't figure out the correct values for the filter (before/after/first/last):

I can get the all 50 first scores (strangely by using "last") with this code:

_query
{
  card(slug: "simon-mignolet-2020-rare-1") 

  {
    grade
  
    player {
     
  allSo5Scores(last:100)
      {nodes
      {score
      playerGameStats{game{date}
      minsPlayed}
      }}
      
      
      
    }
  }
}

And i can get the last 50 (which includes games still to be played) with:

_query
{
  card(slug: "simon-mignolet-2020-rare-1") 

  {
    grade
  
    player {
     
  allSo5Scores(first:100)
      {nodes
      {score
      playerGameStats{game{date}
      minsPlayed}
      }}
      
      
      
    }
  }
}

I've tried before/after, which only seems to accept dates in the form yyyymmdd but doesn't appear to have any impact on the end results :s

Any ideas on how to get the remaining games?

**Comment by thom-des** [comment]
Hi,
`allSo5Scores` is paginated, you need to use the cursor to navigate between pages, checkout https://graphql.org/learn/pagination/ for more about that.
