### ISSUE TITLE
Action Cable for NBA

### ISSUE THREAD

**Issue by M3NGO** [sorare/api#328]
What is the websocket URL to use for actionCable for NBA? If not already existing when are you going to create and serve it?

**Comment by 0xsShady** [comment]
I would like to suscribe to aCardWasUpdated but just for nba players...is there any way to do that at this moment?

**Comment by utay** [comment]
Hi @M3NGO @0xsShady,

> What is the websocket URL to use for actionCable for NBA? If not already existing when are you going to create and serve it?

There's no websocket URL for NBA for now.

> is there any way to do that at this moment?

Subscriptions are sport-agnostic as explained in https://github.com/sorare/api#nfts--cards. You can listen to `tokenAuctionWasUpdated` or `tokenOfferWasUpdated`
