### ISSUE TITLE
Unauthorized: wrong aud

### ISSUE THREAD

**Issue by MarkOSullivan94** [sorare/api#329]
Ran into this issue and thought I'd share the solution for anyone else who may run into it.

#### Steps taken

1. Execute `signIn.js` from examples directory to generate JWT
2. Execute `createSingleSaleOffer.js` with appropriate arguments passed
3. Error message appears below

<img width="730" alt="error" src="https://user-images.githubusercontent.com/6950843/198839239-3abc2b7d-be7c-4b2c-83f0-d6d2d3740f3a.png">

#### Cause

This error was caused as I had used a different AUD for `signIn.js` then the one I used for `createSingleSaleOffer.js`

#### Solution

Make sure to use the same JWT-AUD value for both files

**Comment by utay** [comment]
Thank you @MarkOSullivan94 ! Closing it as there's no follow-up needed, the issue will remain searchable
