### ISSUE TITLE
allNfts won't return more than 50 nodes, despite being below the complexity limit

### ISSUE THREAD

**Issue by mrprince87** [sorare/api#338]
I've been trying to run this query, with a 500 limit (if I put > 500 it returns a complexity error, which is fine), but it would still return a maximum of 50 nodes; putting the `first:` parameter to less than 50 will work as expected.

Any idea?

Thanks!

```
query getAllTokensNBA{
  tokens{
    allNfts(sport:NBA, first:500){
      pageInfo{
        endCursor
        hasNextPage
      }
      nodes{
        slug
        metadata{
          ... on TokenBaseballMetadata{
          playerSlug
          }
        }
      }
    }
  }
}
```

**Comment by stathamos** [comment]
Did you succeed in getting the price for each NFT?

**Comment by jmaupoux** [comment]
Use pagination 
allNfts takes an "after" parameter. Combine it with pageInfo.endCursor

Examples are availables in this repo

**Comment by utay** [comment]
As @jmaupoux mentioned, you can use the `after` parameter for pagination
