### ISSUE TITLE
problem so5Rewards (International Special)

### ISSUE THREAD

**Issue by aspin78** [sorare/api#344]
there is a problem with the rewards for "International Special"

I have the message : "message": "Cannot return null for non-nullable field RewardCard.card"

`query {
  so5Leaderboard(slug:"20-24-nov-2022-special-weekly-division-3") {
    so5Rewards(after: "") {
      nodes {
        so5Ranking {
          ranking
        }
        rewardCards {
          card {
            ownerSince
            id
          }
        }
      }
    }
  }
}`

**Comment by Hugo-Hache** [comment]
Error was caused by cancelled so5Rewards (it happens where a lineup scores zero point) from which rewardCards were removed the card. We filtered those cancelled so5Rewards so it shouldn't happen anymore.
