### ISSUE TITLE
Query basketball card from API 

### ISSUE THREAD

**Issue by Francescodotta** [sorare/api#349]
I tried to transform the code present in java into Python using the gql python package, taking also into account the other python examples.
However it didn't work, i would like to ask if it's possible to know the structure of the NBA card inside the GraphQL schema
thanks

**Comment by jmaupoux** [comment]
You ve got everything you need in the graphQL API documentation :

[https://api.sorare.com/sports/graphql/playground](https://api.sorare.com/sports/graphql/playground)

**Comment by utay** [comment]
Thanks @jmaupoux for answering this! 

@Francescodotta you can also have a look at https://github.com/sorare/api/blob/master/examples/getNBACard.js, it's javascript but the idea is the same
