### ISSUE TITLE
filtering allCards (and everything else...)

### ISSUE THREAD

**Issue by Maaaarko** [sorare/api#35]
I see there's an open issue regarding this, but hasn't been answered for quite some time...

From what I understand, there is no option for filtering all cards apart from making thousands of queries and filtering them locally. That's of course, highly inefective and not something I want to do.

Is there something I'm missing? And will the functionality be added in forseeable future. I think that's a major feature that this API is lacking.

**Comment by redox** [comment]
Merging with https://github.com/sorare/api/issues/35 and will most probably work on it in the near future.
