### ISSUE TITLE
ownerWithRates for NBACard and MLBCard

### ISSUE THREAD

**Issue by Magnienc** [sorare/api#351]
Is it possible to implement the function "ownerWithRates " for NBACard and MLBCard as with the API used for football ? 

thank you 

Cédric

**Comment by redox** [comment]
Unfortunately, this is not something we'll be able to implement in the near short term. You can however rely on the NBA & MLB card `assetId` to query the sport-agnostic `tokens { nft(...) { ownershipHistory } }` field:

Example for https://sorare.com/nba/cards/luka-doncic-19990228-2022-limited-6 with assetId `0x040045c39eb7a6e8a45c872099611c74a5052bac1ff4f2784f3825a361fe08b6`

```
{
  tokens {
    nft(assetId: "0x040045c39eb7a6e8a45c872099611c74a5052bac1ff4f2784f3825a361fe08b6") {
      ownershipHistory {
        from
        priceWei
        priceFiat {
          eur
          gbp
          usd
        }
      }
    }
  }
}
```
