### ISSUE TITLE
Use of currentSportsUser query via Apps Scrips

### ISSUE THREAD

**Issue by PacoASBH** [sorare/api#355]
Hello,

I am sending successfully Graphql queries from my Apps Script (Google Sheets) to NBA Sorare API (nbaPlayer, nbaCard).

But when I want to use **currentSportsUser** query, I got the following error message (even when I am correctly logged in Sorare) :
{   "errors": [     {       "message": "_**sign in required**_",       "path": [         "currentSportsUser"       ]     }   ],
  "data": {     "currentSportsUser": null   } }

It is maybe related to my HEADER ?
{ 	"Content-Type": "application/json", }

Thanks for your help.

Paco

**Comment by jmaupoux** [comment]
Hi,

You need to signup and then send a JWT as part of the query.
Everything is explained in the documentation.

**Comment by PacoASBH** [comment]
Thanks !

**Comment by utay** [comment]
Thanks @jmaupoux :)
