### ISSUE TITLE
Some games missing in query nbaPlayer / latestFixtureStats

### ISSUE THREAD

**Issue by PacoASBH** [sorare/api#356]
Hello,

My goal is to list all scores of a NBA Player.

But my Graphql query didn't return games in which my player is out the squad. It's normal but I want to know that he missed this game and it doesn't appear in the query result. Someone have idea to help me please. 

![Screenshot4](https://user-images.githubusercontent.com/121180654/209253655-f44f159c-33eb-4cd1-8b8f-eb7e604e129d.PNG)

Missing games (where Thomson was out the squad) on the 15/12/2022.

![Screenshot5](https://user-images.githubusercontent.com/121180654/209253792-1ba1a5b6-6800-48b0-9273-9a85162415b6.PNG)

Thanks

Pascal

**Comment by jmaupoux** [comment]
Hi,

Use nbaPastFixtures to fetch all passed fixtures - with nested games and teams participating.
Then mix with your player data to complete missing fixtures for his team, assuming he was out and scored 0.

**Comment by PacoASBH** [comment]
Again thanks ! :)

**Comment by utay** [comment]
Thanks @jmaupoux for answering this, again!
