### ISSUE TITLE
AcceptOffer : signatures and starkSignatures?

### ISSUE THREAD

**Issue by Iv3li0s** [sorare/api#36]
I try to use AcceptOffer
But how can I fill signatures or starkSignatures ?

"starkSignatures":[{
   "nonce":00,
   "expirationTimestamp"0000:,
   "data":{\"r\":\"0x?????????????\",\"s\":\"????????????????\"}",
   "starkKey":"0x???????????????"
}]}

Thx

**Comment by flowtra** [comment]
@Iv3li0s Did you manage to get this working?
