### ISSUE TITLE
How list NBA/MLB auctions in specific https://api.sorare.com/sports graphql

### ISSUE THREAD

**Issue by PacoASBH** [sorare/api#361]
Hello,

What's the NBA/MLB keyword to list auctions please ?

I understtod it's the following for football :
transferMarket { englishAuctions(first: 10) {...}]

Thanks.

Paco

**Comment by jmaupoux** [comment]
Hi,

You can't. NBA and MLB API are quite poor at the moment.

Listen to tokenAuction subscription instead.

**Comment by utay** [comment]
Thanks @jmaupoux for answering this! 

@PacoASBH you can do something similar to https://github.com/sorare/api/blob/master/examples/getNBACardPrice.js or use subscriptions indeed
