### ISSUE TITLE
{ AssitID} Is not owned by {StackKey} in layer 2

### ISSUE THREAD

**Issue by oklotz** [sorare/api#369]
Hello,

Since 1 week, when I made an offer With script in exemple,  i have an errer "assetid is not owned by starkkey ".

Before, the same script works fine.

Any idea?

**Comment by eulbat** [comment]
Hi @oklotz 
Could you please detail which mutation you are using?

**Comment by oklotz** [comment]
I am using the mutation createDirectOffer . And in the error message  "assetid is not owned by starkkey **in layer 2**".
Maybe something change in that mutation

**Comment by oklotz** [comment]
`const { GraphQLClient, gql } = require("graphql-request");
const { signLimitOrder } = require("@sorare/crypto");
const crypto = require("crypto");
const yargs = require("yargs");

const {
  sendAssetId,
  sendWei,
  receiveAssetIds,
  receiveWei,
  receiverSlug,
  token,
  jwtAud,
  privateKey,
} = yargs
  .command("createDirectOffer", "Create a direct buy offer.")
  .option("send-asset-id", {
    description: "The assetId to send.",
    type: "string",
  })
  .option("send-wei", {
    description: "The amount of ETH to send, in wei.",
    type: "string",
    default: "0",
  })
  .option("receive-asset-ids", {
    description: "The comma-separated list of assetIds to receive.",
    type: "string",
  })
  .option("receive-wei", {
    description: "The amount of ETH to receive, in wei.",
    type: "string",
    default: "0",
  })
  .option("receiver-slug", {
    description: "The receiver slug.",
    type: "string",
  })
  .option("token", {
    description: "The JWT or OAuth token.",
    type: "string",
    required: true,
  })
  .option("private-key", {
    description: "Your Sorare private key",
    type: "string",
    required: true,
  })
  .option("jwt-aud", {
    description: "The JWT audience (required if using a JWT token).",
    type: "string",
  })
  .help()
  .alias("help", "h").argv;

const CurrentUser = gql`
  query CurentUserQuery {
    currentUser {
      starkKey
    }
  }
`;

const NewOfferLimitOrders = gql`
  mutation NewOfferLimitOrders($input: prepareOfferInput!) {
    prepareOffer(input: $input) {
      limitOrders {
        amountBuy
        amountSell
        expirationTimestamp
        nonce
        tokenBuy
        tokenSell
        vaultIdBuy
        vaultIdSell
      }
      errors {
        message
      }
    }
  }
`;

const CreateDirectOffer = gql`
  mutation CreateDirectOffer($input: createDirectOfferInput!) {
    createDirectOffer(input: $input) {
      offer {
        id
      }
      errors {
        message
      }
    }
  }
`;

async function main() {
  const graphQLClient = new GraphQLClient("https://api.sorare.com/graphql", {
    headers: {
      Authorization: `Bearer ${token}`,
      "JWT-AUD": jwtAud,
      // 'APIKEY': '<YourOptionalAPIKey>'
    },
  });

  const currentUserData = await graphQLClient.request(CurrentUser);
//  console.log(currentUserData);
  const starkKey = currentUserData["currentUser"]["starkKey"];
//  console.log("Your starkKey is", starkKey);
//  console.log ("Your public key is",privateKey); 
  const prepareOfferInput = {
    type: "DIRECT_OFFER",
    sendAssetIds: [],
    receiveAssetIds: receiveAssetIds?.split(",") || [],
    sendWeiAmount: sendWei,
    receiveWeiAmount: receiveWei,
    receiverSlug: receiverSlug,
    clientMutationId: crypto.randomBytes(8).join(""),
  };
  console.log(prepareOfferInput);

  const newOfferData = await graphQLClient.request(NewOfferLimitOrders, {
    input: prepareOfferInput,
  });
  console.log(newOfferData);

  const prepareOffer = newOfferData["prepareOffer"];
  if (prepareOffer["errors"].length > 0) {
    prepareOffer["errors"].forEach((error) => {
      console.error(error["message"]);
    });
    process.exit(2);
  }

  const limitOrders = prepareOffer["limitOrders"];
  if (!limitOrders) {
    console.error("You need to be authenticated to get LimitOrders.");
    process.exit(1);
  }
  console.log(limitOrders);

  const starkSignatures = limitOrders.map((limitOrder) => ({
    data: JSON.stringify(signLimitOrder(privateKey, limitOrder)),
    nonce: limitOrder.nonce,
    expirationTimestamp: limitOrder.expirationTimestamp,
    starkKey,
  }));
  console.log(starkSignatures);

  const createDirectOfferInput = {
    starkSignatures,
    dealId: crypto.randomBytes(8).join(""),
    sendAssetIds: [sendAssetId],
    receiveAssetIds: receiveAssetIds?.split(",") || [],
    sendWeiAmount: sendWei,
    receiveWeiAmount: receiveWei,
    duration: 14400,
    receiverSlug: receiverSlug,
    clientMutationId: crypto.randomBytes(8).join(""),
  };
  console.log(createDirectOfferInput);
  const createDirectOfferData = await graphQLClient.request(
    CreateDirectOffer,
    { input: createDirectOfferInput }
  );
  console.log("#########################")
  console.log(createDirectOfferData);
  const createDirectOffer =
    createDirectOfferData["createDirectOffer"];

  if (createDirectOffer["errors"].length > 0) {
    createDirectOffer["errors"].forEach((error) => {
      console.error(error["message"]);
    });
    process.exit(2);
  }

  console.log("Success!");
}

main().catch((error) => console.error(error));
`

This is my code. It is based on js in exemple

**Comment by oklotz** [comment]
maybe something change in the layer 2?

**Comment by eulbat** [comment]
Hi @oklotz 
Usually that means you are trying to create an offer where you are sending a card that does not belong to you.
Could you double check you haven't inverted the send/receive asset ids?

**Comment by oklotz** [comment]
In my case, I send an eth offer to receive a card. 
In receiveAssetId, I have well an ID and nothing in the sending assetid.
Effectively, i try to receive a card that is not my. It is the objectif :)

**Comment by oklotz** [comment]
@eulbat 
For example, the receiverSlug used is : kloklo-e692323f-b477-43ab-afb9-1e5d7df806eb
assetId could be : 
0x04008788cd2ef0b84ea251eca8e41fff652cb14b8f8b630d774b17b87b1e414e 
0x0400c547da6869c9dc809ff458135a807962252e1ef47ee96bdf293fe6630288

or other.
I have this pb with all assetId

**Comment by eulbat** [comment]
Those 2 asset ids do not belong to kloklo-e692323f-b477-43ab-afb9-1e5d7df806eb

**Comment by oklotz** [comment]
of course. For me the receiverSlug is typically my slug because I made the offer and I am the receiver of the card. The assetId are in receiveAssetId and it is not my card. The objective is the send eth to receive card. The same script worked end of the year.

**Comment by eulbat** [comment]
The `receiverSlug` is the slug of the user receiving the offer.
It is inferred from the assetId if you use the `createSingleBuyOffer` mutation
