### ISSUE TITLE
How to get ETH involved in a trade ?

### ISSUE THREAD

**Issue by jamindoStar** [sorare/api#37]
Hi All,
I got a lot of datas from Sorare API, but there's one data I'm not able to find :
The amount of ETH involved in a trade.
For example , Neymar card trade for 1 ETH and a Lewandowski card.
Where can I find in the API informations about the1 ETH and the Lewandowki card?

I know those data are exposed on SorareData so I guess that it will be on the API.

Thanks in advance for your answer

**Comment by redox** [comment]
Hey @jamindoStar and @rbdm-qnt , I've added more documention about how to create sales offers, including how to send/receive ETH with a card. You can read more about it here: https://github.com/sorare/api#examples

Let me know if that works, closing the issue for now.
