### ISSUE TITLE
How to get direct offer that I accepted ? 

### ISSUE THREAD

**Issue by SorareFinance** [sorare/api#380]
Hello, 

I try to retrieve all the sales I've made on my account with this query : 
`query($slug: String!, $cursor: String) {
  user(slug: $slug) {
    soldSingleSaleOffers(after: $cursor) {
      nodes {
        card {
          slug
        }
      }
    }
  }
}`
It returns me some data, but it's incomplete, it doesn't have the directs offers that I accepted. 
Is there something I must add in my query to have them ?

Best regards.

**Comment by TyRappal** [comment]
Hello
`endedTokenOffersReceived(states: ACCEPTED)`

**Comment by SorareFinance** [comment]
Thank you, it seems returning the data I was looking for !
