### ISSUE TITLE
How can i get a users (slug or id) nba cards or mlb cards

### ISSUE THREAD

**Issue by raymondflores** [sorare/api#381]
For example i want to be able to do something like
`sportsUser(id: '123') {
  nbaCards {
    name
    ...otherdata
  }
  mlbCards {
    name
    ...otherdata
  }
}`

it doesnt seem possible with current api

**Comment by karancan** [comment]
Has there been any update on this?

**Comment by utay** [comment]
@raymondflores @karancan Yes you can now use:
```
sportsUser(id: '123') { nbaCards { ... } baseballCards { ... } }
```
