### ISSUE TITLE
No 'TokenNBAMetadata' for 'Token' type for the NBA

### ISSUE THREAD

**Issue by jeremyallencpa** [sorare/api#386]
It appears that two endpoints `endedDirectOffersSent` and `endedDirectOffersReceived` are going to be deprecated soon.

In preparation, I am migrating to the two new endpoints `endedTokenOffersSent` and `endedTokenOffersReceived` for my application.

However, it appears that there is no metadata available for the NBA yet on the `Token` object - there is only `TokenBaseballMetadata` and `TokenFootballMetadata`.

When will support be added for `TokenNBAMetadata`?

**Comment by jmallot21** [comment]
NBA tokens use the same structure as TokenBaseballMetadata.

**Comment by utay** [comment]
Indeed, thank you @jmallot21 for the update! We will update the [CHANGELOG](https://github.com/sorare/api/blob/master/CHANGELOG.md) if we plan to create a dedicated `TokenNBAMetadata` for NBA
