### ISSUE TITLE
Request Limit Problem

### ISSUE THREAD

**Issue by satruxag** [sorare/api#39]
i run a query every 30 seconds but i get blocked, what is the request limit?

**Comment by doublesavonette** [comment]
@satruxag it is been documented in past issues. It is 600/5mins

**Comment by satruxag** [comment]
then there is an error, because 300 requests in 5 minutes are 1 per second, so 60 per minute ... cloudflare blocks the ip with 5 requests per minute

**Comment by redox** [comment]
We've documented the rate-limits in the updated [README](https://github.com/sorare/api).
