### ISSUE TITLE
bid signature

### ISSUE THREAD

**Issue by doublesavonette** [sorare/api#40]
Hi all,

Did anyone know how to generate the starkSignatures attribute of the bidInput object? Especially the StarkSignatureInput.data ? I have been trying to follow the doc and adapt it to python but it is honestly quite slim.

Cheers!

**Comment by nachoroncero** [comment]
> Hi all,
> 
> Did anyone know how to generate the starkSignatures attribute of the bidInput object? Especially the StarkSignatureInput.data ? I have been trying to follow the doc and adapt it to python but it is honestly quite slim.
> 
> Cheers!

Hello, did you get to implement it in Python? Thank you
