### ISSUE TITLE
Retrieve last sells and current floor price information through the API for a current player and scarcity

### ISSUE THREAD

**Issue by fmeziere** [sorare/api#408]
Hi
I have been searching everywhere but I can't find this information:
Now that Sorare website is displaying the last sales for a given player and scarcity, can we retrieve this information through the API?
I am talking to these data with the example of Aaron Judge limited:
<img width="849" alt="Capture d’écran 2023-04-12 120340" src="https://user-images.githubusercontent.com/44086114/231425497-ec70491e-f1aa-4197-bb38-1f737f13d2c4.png">

I would be also interested to retrieve floor price, and did not find any efficient way to get it (I can do it by scrolling all the existing cards to see if they are currently on sale and their price but that is really not efficient)

Thanks in advance!

**Comment by djizus** [comment]
You need to use the following query :
![image](https://user-images.githubusercontent.com/4562236/231984933-2a1273e9-44a3-4748-97e8-231acef65587.png)

   query TokenRoot($playerSlug: String!, $collection: Collection!, $rarity: Rarity!){
    tokens
    {
      tokenPrices(playerSlug: $playerSlug, collection: $collection, rarity: $rarity)
      {
        amount amountInFiat {eur gbp usd}
      }
    }
  }
  
  Regarding the floor, you can retrieve it through the attribute publicMinPrice of a token : 
  
![image](https://user-images.githubusercontent.com/4562236/231985477-96514aef-5d4b-4ff6-8701-4aee2d2f123f.png)

**Comment by fmeziere** [comment]
Thank you for your very clear answer, I am good now!
