### ISSUE TITLE
publicMinPrice is null

### ISSUE THREAD

**Issue by Tongziqi** [sorare/api#410]
Hello, when I tried to search for the floor price of jorge-resurreccion-merodio in the current market using an API, I noticed that there is a token field containing publicMinPrice. However, when I printed it out, all publicMinPrice values were empty. So, do you think I am doing something wrong and should instead iterate through all liveSingleSaleOffer to obtain the floor price?

`
query GetPlayerMinPrice($slug: String!, $cursor: String) {
  player(slug: $slug) {
    cards(rarities: rare, after: $cursor) {
      nodes {
        token {
          privateMinPrice
          publicMinPrice
          owner {
            __typename
          }
          liveSingleSaleOffer {
            priceWei
          }
        }
      }
      pageInfo {
        endCursor
      }
    }
  }
}
`

{
  "slug": "jorge-resurreccion-merodio"
}

result:
<img width="794" alt="image" src="https://user-images.githubusercontent.com/7666830/232558880-d037832a-7fe2-430e-87fa-7d61423e0758.png">

**Comment by mbh86** [comment]
Same issue here. Any way to get the floor price in an easy manner than looping on all the cards on sale ? (or storing from subscription).
Thank you :)

**Comment by sfriquet** [comment]
A token min price (that can either be public or private to the token owner) is a settings the owner of the token can set so they don't receive offer below that price for this token. it's not an indication of the token value in any way.

**Comment by benshotx** [comment]
did you find out how to get the floorprice?

**Comment by Diglee147** [comment]
> 

i have to know it too.
