### ISSUE TITLE
`lastFiveSo5AverageScore` and `lastFifteenSo5AverageScore` no longer accessible

### ISSUE THREAD

**Issue by jamb0ree** [sorare/api#411]
Hi,

in the Football API, the `lastFiveSo5AverageScore` and `lastFifteenSo5AverageScore` were available via the `player > status` field.
It is now indicated that this is deprecated and we should "Use fields on player directly".

Some of the old fields are indeed directly accessible (`id`, `lastFifteenSo5Appearances`, ...), but not the scores on last 5 and 15 games.

Unless these fields have been placed somewhere else, could you please restore them?
Thanks

**Comment by ivan79** [comment]
I found averageScore(type:LAST_FIVE_SO5_AVERAGE_SCORE) inside player

**Comment by jamb0ree** [comment]
great, thanks a lot for this!
