### ISSUE TITLE
How to get national teams involved in an international competition?

### ISSUE THREAD

**Issue by BenGermanPro** [sorare/api#416]
Hi,
When I use the following query to get national teams involved in Euro qualifiers, I have no teams as result.

```
query {
	  competition(slug:"ec-qualification"){
	    clubs{
	      nodes{
	    		pictureUrl
	        code
	        id
	    		slug
	      }
	    }
	  }
	}
```

Looks normal as I use the "clubs" tag. But as there's no "nationalTeams" tag in competition object, How can I get national teams involved in an international competition ?

Thanks in advance
Benjamin

**Comment by ithawa** [comment]
Hello,
what you need to do is use the contestants. That needs a season and for the qualification it is also the year of the tournament itself, so 2024. 

Here is the correct query:

{
  competition(
    slug: "ec-qualification"
  ) {
    name
    pictureUrl
    contestants(
      seasonStartYear: 2024
    ) {
      id
      matchesDrawn
      matchesLost
      matchesPlayed
      matchesWon
      points
      rank
      team {
        ... on NationalTeam {
          name
          slug
          pictureUrl
          
        }
      }
    }
  }
}

Hope that helps. 

Greetings, Noah.

**Comment by BenGermanPro** [comment]
Thanks for your reply ! it works well 👍
