### ISSUE TITLE
aCardWasUpdated subscription owned filter issue

### ISSUE THREAD

**Issue by miroshnik** [sorare/api#417]
Hello,
When subscribing to updates for my cards, I receive updates for all cards instead of only my own.

```
const cable = new ActionCable({
  headers: {
    'Authorization': `Bearer ${token}`,
  }
})

cable.subscribe(`aCardWasUpdated(owned: true) { slug }`, {...})
```

Is this a bug or am I doing something incorrectly?

**Comment by redox** [comment]
No this is indeed the correct behavior. You need to filter out what you don't care about.
