### ISSUE TITLE
OAuth process

### ISSUE THREAD

**Issue by quentin-maison** [sorare/api#42]
Hi,

On the OAuth documentation you mention I need to request the OAuth Application for myself first. I would have liked to know how to perform this request?

Thanks,
Have a great day

**Comment by ziadghalleb** [comment]
Same here. It doesn't look their tech team is very responsive however.

**Comment by davidbyttow** [comment]
Hello, I'm going to close this due to inactivity, however we also are in the process of revamping this documentation which should hopefully help answer these questions. https://github.com/sorare/api/pull/63
