### ISSUE TITLE
CreateDirectOffer.js : invalid limit order signature

### ISSUE THREAD

**Issue by oklotz** [sorare/api#422]
Hello,
I've a problem with my script since 2 days. Before that, same script was operational without problem.
when i launch it, i've the error "invalid limit order signature".
Maybe an update from the system was done.

The script is :
`const { GraphQLClient, gql } = require("graphql-request");
const { signLimitOrder } = require("@sorare/crypto");
const crypto = require("crypto");
const yargs = require("yargs");

const {
  sendAssetId,
  sendWei,
  receiveAssetIds,
  receiveWei,
  receiverSlug,
  token,
  jwtAud,
  privateKey,
} = yargs
  .command("createDirectOffer", "Create a direct buy offer.")
  .option("send-asset-id", {
    description: "The assetId to send.",
    type: "string",
  })
  .option("send-wei", {
    description: "The amount of ETH to send, in wei.",
    type: "string",
    default: "0",
  })
  .option("receive-asset-ids", {
    description: "The comma-separated list of assetIds to receive.",
    type: "string",
  })
  .option("receive-wei", {
    description: "The amount of ETH to receive, in wei.",
    type: "string",
    default: "0",
  })
  .option("receiver-slug", {
    description: "The receiver slug.",
    type: "string",
  })
  .option("token", {
    description: "The JWT or OAuth token.",
    type: "string",
    required: true,
  })
  .option("private-key", {
    description: "Your Sorare private key",
    type: "string",
    required: true,
  })
  .option("jwt-aud", {
    description: "The JWT audience (required if using a JWT token).",
    type: "string",
  })
  .help()
  .alias("help", "h").argv;

const CurrentUser = gql`
  query CurentUserQuery {
    currentUser {
      starkKey
    }
  }
`;

const NewOfferLimitOrders = gql`
  mutation NewOfferLimitOrders($input: prepareOfferInput!) {
    prepareOffer(input: $input) {
      limitOrders {
        amountBuy
        amountSell
        expirationTimestamp
        nonce
        tokenBuy
        tokenSell
        vaultIdBuy
        vaultIdSell
      }
      errors {
        message
      }
    }
  }
`;

const CreateDirectOffer = gql`
  mutation CreateDirectOffer($input: createDirectOfferInput!) {
    createDirectOffer(input: $input) {
      offer {
        id
      }
      errors {
        message
      }
    }
  }
`;

async function main() {
  const graphQLClient = new GraphQLClient("https://api.sorare.com/graphql", {
    headers: {
      Authorization: `Bearer ${token}`,
      "JWT-AUD": jwtAud,
      // 'APIKEY': '<YourOptionalAPIKey>'
    },
  });

  const currentUserData = await graphQLClient.request(CurrentUser);
//  console.log(currentUserData);
  const starkKey = currentUserData["currentUser"]["starkKey"];
//  console.log("Your starkKey is", starkKey);
//  console.log ("Your public key is",privateKey); 
  const prepareOfferInput = {
    type: "DIRECT_OFFER",
    sendAssetIds: [sendAssetId],
    receiveAssetIds: receiveAssetIds?.split(",") || [],
    sendWeiAmount: sendWei,
    receiveWeiAmount: '0',
    receiverSlug: receiverSlug,
    clientMutationId: crypto.randomBytes(8).join(""),
  };
 // console.log(prepareOfferInput);

  const newOfferData = await graphQLClient.request(NewOfferLimitOrders, {
    input: prepareOfferInput,
  });
//  console.log(newOfferData);

  const prepareOffer = newOfferData["prepareOffer"];
  if (prepareOffer["errors"].length > 0) {
    prepareOffer["errors"].forEach((error) => {
      console.error(error["message"]);
    });
    process.exit(2);
  }

  const limitOrders = prepareOffer["limitOrders"];
  if (!limitOrders) {
    console.error("You need to be authenticated to get LimitOrders.");
    process.exit(1);
  }
//  console.log(limitOrders);

  const starkSignatures = limitOrders.map((limitOrder) => ({
    data: JSON.stringify(signLimitOrder(privateKey, limitOrder)),
    nonce: limitOrder.nonce,
    expirationTimestamp: limitOrder.expirationTimestamp,
    starkKey,
  }));
//  console.log(starkSignatures);

  const createDirectOfferInput = {
    starkSignatures,
    dealId: crypto.randomBytes(8).join(""),
    sendAssetIds: [sendAssetId],
    receiveAssetIds: receiveAssetIds?.split(",") || [],
    sendWeiAmount: sendWei,
    duration: 14400,
    receiverSlug: receiverSlug,
    clientMutationId: crypto.randomBytes(8).join(""),
  };
//  console.log(createDirectOfferInput);
  const createDirectOfferData = await graphQLClient.request(
    CreateDirectOffer,
    { input: createDirectOfferInput }
  );
//  console.log(createDirectOfferData);
  const createDirectOffer =
    createDirectOfferData["createDirectOffer"];

  if (createDirectOffer["errors"].length > 0) {
    createDirectOffer["errors"].forEach((error) => {
      console.error(error["message"]);
      console.log(error["message"]);
    });
    process.exit(2);
  }

  console.log("Success!");
}

main().catch((error) => console.error(error));
`

To launch the script, i execute the cli : 
`node createDirectOffer.js --token XXXX --private-key YYYY --jwt-aud AUD --receive-asset-ids 0x04003d50faae9d0c50756047565c5abb867b4410e40b1486f3c85dcb0de1ef11 --send-wei 2400000000000000 --receiver-slug bb4`

I'm using my starkware private key. I have tested with my eth private key and i've the same result.

My nodejs version is 14.21.3.

I don't understand why it's doesn't work. 

Can you help me please? :)

**Comment by redox** [comment]
This is because you don't require the `feeInfo` field of the `limitOrder` while preparing the offer. It's required since the introduction of the market fees on football (you would have already the problem before on MLB/NBA cards).

I've patched the example in 5b7c1c3 as I understand a lot of users copied this singleSaleOffer example to create their DirectOffer one.

Good luck with the implem!

**Comment by oklotz** [comment]
Thanks @redox I've just test it and it correct effectively my pb.

Many thanks
