### ISSUE TITLE
Selecting `allSo5Scores` within a list of `Player` (`players`) is not supported (anymore ???)

### ISSUE THREAD

**Issue by mbh86** [sorare/api#425]
Hello Sorare team,

It looks like you made a change and it's not anymore possible to select allSo5Scores within a list of players.
Is it intended? Did you guys alert/notify us on this removal?

Thank you.

**Comment by utay** [comment]
Indeed it is intended, sorry about that. We made a change so that `allSo5Scores` is only resolvable for a single player, not within a list of players. We'll make sure to update the changelog for such a change next time!

**Comment by mbh86** [comment]
@utay Ok, just to confirm, now there is no possibility to query all players score (even for a single GW) unless doing 10K+ calls, one per player?
Could you consider to implement a method that allows us to query scores for a game id at least? It would reduce significantly the number of calls to get scores for a GW, from 10K+ to 100+ (number of games in a GW).

**Comment by Hugo-Hache** [comment]
Player.so5Scores is nestable and you should be able to retrieve up to the last 10 scores. Would it work for your use case? (that depends if you're looking for recent or old scores)

**Comment by mbh86** [comment]
Hi @Hugo-Hache, it's perfect alternative, thank you very much !
