### ISSUE TITLE
How to use CurrentUser

### ISSUE THREAD

**Issue by MenzoGitHub** [sorare/api#43]
Hello,

I can not seem to get any CurrentUser query working. I keep getting the following response: `'{"data":{"currentUser":null}}'`.

What I am trying (in Python):

```
query = """
  {currentUser {
      email
    }
  }
  """

headers = {
     "x-csrf-token": csrf,
     "_sorare_session_id": sessionId
}

r = post('https://api.sorare.com/graphql', json={'query': query}, headers=headers)
```

Where `csrf` and `sessionId` are obtained by logging in.

Is there something wrong with the headers maybe? Or do I need to add something to the query?

Many thanks in advance!

**Comment by redox** [comment]
hey @MenzoGitHub , I've revamped our documentation and you should now be able to easily get there: https://github.com/sorare/api

Closing the issue, let us know if something is missing (yes we need to add a few python examples).
