### ISSUE TITLE
Playground headers are ignoring my APIKEY

### ISSUE THREAD

**Issue by jeremyallencpa** [sorare/api#434]
When including headers in the new playground like so:

``
{
  "APIKEY": "APIKEYHERE"
}
``

I am receiving the following error:

```
{
  "errors": [
    {
      "message": "Query has complexity of 1060, which exceeds max complexity of 500. Using an APIKEY the limit would be 30000."
    }
  ]
}
```

**Comment by redox** [comment]
Indeed, I reproduce this as well. We'll be checking this

**Comment by redox** [comment]
> Indeed, I reproduce this as well. We'll be checking this

A fix will be deployed today

**Comment by utay** [comment]
@jeremyallencpa Thanks for the report. This should be fixed now after a refresh of the playground page, please feel free to reopen if it's not the case
