### ISSUE TITLE
Using new federation API causing issues with NBACollection

### ISSUE THREAD

**Issue by Xorso** [sorare/api#440]
When trying to verify my queries against the schema by calling currentSportsUser, I get a NBACollection not found error.

**Comment by utay** [comment]
Hi @Xorso, could you please provide the query causing the error? I'm not able to repro

**Comment by Xorso** [comment]
Weird it wasn't there yesterday when I ran the generic introspection queries that come from the python [sgqlc library](https://sgqlc.readthedocs.io/). I see that it is now there:

```
class NBACollection(sgqlc.types.Type, CollectionInterface):
    __schema__ = sorare_schema
    __field_names__ = ()
```

**Comment by utay** [comment]
Indeed yesterday for some time the playground was down with an NBACollection error. Apologies for the inconvenience, it is now fixed!
