### ISSUE TITLE
Authenticated subscription error

### ISSUE THREAD

**Issue by AlexCapoen** [sorare/api#453]
Hello,

I would like to make an authenticated subscription, but I'm receiving the "Not authorized to access Subscription.currentUserWasUpdated" error. 
I have included all the necessary headers to make this authenticated subscription, and it works perfectly for authenticated requests, for example.

**Comment by redox** [comment]
I News to check this again, multiple users reported it. There must be a small issue across the various pieces involved in our web socket management.

**Comment by rbdm-qnt** [comment]
> I need to check this again, multiple users reported it. There must be a small issue across the various pieces involved in our web socket management.

Was there any update on this front?

**Comment by AlexCapoen** [comment]
Still not

**Comment by antoine-malliarakis** [comment]
@AlexCapoen would you be able to provide us with the code you are actually using to make your subscriptions ?

**Comment by AlexCapoen** [comment]
I'm using the same headers as the ones used to make the authentication requests (which are working)


```
async def subscribe_to_current_user(self):
        logging.info('Subscribing to data...')
        transport = ActionCableWebsocketsTransport(
            url="wss://ws.sorare.com/cable",
            headers = headers = {
                "content-type": "application/json",
                "APIKEY": config.API_KEY,
                "Authorization": f"Bearer {self.token}",
                "JWT-AUD": "Akaquax's APP"
            }
        )
        
        async with Client(transport=transport) as session:
            subscription = gql(SUB_USER_UPDATE)
            async for result in session.subscribe(subscription):
                logging.info('Received data')
                logging.debug(result)
                yield result
```

**Comment by rbdm-qnt** [comment]
> I'm using the same headers as the ones used to make the authentication requests (which are working)
> 
> ```
> async def subscribe_to_current_user(self):
>         logging.info('Subscribing to data...')
>         transport = ActionCableWebsocketsTransport(
>             url="wss://ws.sorare.com/cable",
>             headers = headers = {
>                 "content-type": "application/json",
>                 "APIKEY": config.API_KEY,
>                 "Authorization": f"Bearer {self.token}",
>                 "JWT-AUD": "Akaquax's APP"
>             }
>         )
>         
>         async with Client(transport=transport) as session:
>             subscription = gql(SUB_USER_UPDATE)
>             async for result in session.subscribe(subscription):
>                 logging.info('Received data')
>                 logging.debug(result)
>                 yield result
> ```

Can confirm I've tried this too and all possible combinations of it, so:
- GQL library websockets
- regular python websockets library
- set the headers to the wss class itself, or send them in when subscribing
- every possible combination of the fields in headers

Sharing in case it helps fixing the error

**Comment by antoine-malliarakis** [comment]
Hello,

This is to notify you that the issue should now be fixed. I validated manually on my side and will close this issue but don't hesitate to reopen it in case the issue arises.

In the meantime we'll be investigating on how to ensure this remains working.

Regards
