### ISSUE TITLE
About date and price

### ISSUE THREAD

**Issue by Diglee147** [sorare/api#455]
'# Retrieve the bids
        graphql_query = gql("""
        query{
          currentUser {
            pendingTokenOffersReceived {
              nodes {
                blockchainId
                id
                receiverSide {
                  wei
                  nfts {
                    assetId
                    publicMinPrice
                  }
                }
                senderSide {
                  wei
                  nfts {
                    assetId
                    publicMinPrice
                  }
                }
              }
            }
          }
        }
        """)'
        
       ' # Retrieve card details
        card_details_query = gql("""
        query CardDetails {
          football {
            cardByAssetId(assetId: "%s") {
              rarity
              openForGameStats
              u23Eligible
            }
          }
        }
        """ % card_id)'
        
I'm making a bot and I'm having trouble doing two things:
get the same floor price as the soraredata of each one, and get the information on when the last trade was for that card (if it's been more than 7 days) can someone help me?

**Comment by Diglee147** [comment]
i tryed this example:
query TokenDataAndPrices{
    tokens
    {
      tokenPrices(playerSlug: "luca-koleosho-2022-limited-102", collection: FOOTBALL, rarity: limited)
      {
        date
        amount
      }
    }
  }
 but it returns:
 {
  "data": {
    "tokens": {
      "tokenPrices": []
    }
  }
}

**Comment by Diglee147** [comment]
publicMinPrice returns [] too

**Comment by Diglee147** [comment]
priceRange{min}
returns a wrong value too

**Comment by benshotx** [comment]
I would also like to know but I think it would be necessary to make a script that resembles all the offers of a player and to take the lowest, I think it is possible.

**Comment by Diglee147** [comment]
> I would also like to know but I think it would be necessary to make a script that resembles all the offers of a player and to take the lowest, I think it is possible.

let me know if you can think of something, let's work together

**Comment by Diglee147** [comment]
query{
  football{
    allCards(playerSlugs: "luca-koleosho", rarities: limited, last: 7490){
      nodes{
        token{
          tradeableStatus
          liveSingleSaleOffer{
            priceWei
          }
        }
      }
    }
  }
}
try this

**Comment by Diglee147** [comment]
> query{ football{ allCards(playerSlugs: "luca-koleosho", rarities: limited, last: 7490){ nodes{ token{ tradeableStatus liveSingleSaleOffer{ priceWei } } } } } } try this

still a problem, it doesn't get all cards for compare.

**Comment by benshotx** [comment]
it doesn't work and how i can have all the cards put up in sales from a player?
