### ISSUE TITLE
Error: Settlement currencies is required with createSingleSaleOffer.js

### ISSUE THREAD

**Issue by jos123456** [sorare/api#457]
Hi

Since today I can't offer my cards on the market with Sorare's API.

I'm getting this error: 

"Settlement currencies is required"

To make the offer I'm using the file from examples sections: createSingleSaleOffer.js

I make an order from shell: 

node createSingleSaleOffer.js --send-asset-id xxxxx --private-key xxxxx --receive-wei xxxxxxx

And I changed anything.

This was working for me for several months until now.

Hope anyone knows the solution

**Comment by Diglee147** [comment]
i think they are doing some updates, there are some things that are not working.

**Comment by sfriquet** [comment]
Hi @jos123456. We're indeed in the process of updating the offer API and it looks like some checks weren't properly working. This should now be fixed. Thanks for reporting.
