### ISSUE TITLE
Using acceptOffer exemple generate invalid signature

### ISSUE THREAD

**Issue by KittyTools** [sorare/api#459]
Did you change anything regarding acceptingOffers ?
It used to work 100% of the time, now I got a lot of invalid signature even if I didnt change anything in the code.
I saw some new field in prepareAcceptOffer (authorizations), is it mandatory?

**Comment by sfriquet** [comment]
👋 
No new fields should be mandatory at this point.
Can you provide an example ? Which calls are you making and what responses are you seeing ?
Thanks

**Comment by KittyTools** [comment]
The calls im making are similar to the exemple provided here :
https://github.com/sorare/api/blob/master/examples/acceptSingleSaleOffer.js

Only error message I got is : "invalid signature" nothing else.

If I buy from the website, it's working. But I can see in the dev tool the additionnal approvals and settlementInfo fields.

The weird thing is that it's working for fome offers and generate invalid signatures for others

**Comment by KittyTools** [comment]
also having this error sometime : "Trade cannot be accepted, Trade cannot be accepted"

Really look like random

**Comment by sfriquet** [comment]
> also having this error sometime : "Trade cannot be accepted, Trade cannot be accepted"

This means the trade is not in a state where you can accept it (most likely it's already been accepted).

(that being said we shouldn't return the error twice, we'll fix that)

**Comment by sfriquet** [comment]
> Only error message I got is : "invalid signature" nothing else.

Can you share an ID of an offer you're trying to accept ?

**Comment by KittyTools** [comment]
"id": "SingleSaleOffer:f2b96899-4dd9-4009-9d27-a30ad887da8f",
  "blockchainId": "42691587202601558248218988666773256265",
  "marketFeeAmountWei": "50000000000000",
  "priceWei": "1000000000000000"

**Comment by KittyTools** [comment]
By the way your exemple use blockchainId while the website use id
I guess we can use either one or other?

**Comment by KittyTools** [comment]
> By the way your exemple use blockchainId while the website use id I guess we can use either one or other?

I tried both, got invalid signature for both.

If i try to copy cat the website requests (querying exchangeRate) and giving the same inputs from website, in response of prepareAcceptOffer, I have null value for authorizations

**Comment by KittyTools** [comment]
> "id": "SingleSaleOffer:f2b96899-4dd9-4009-9d27-a30ad887da8f", "blockchainId": "42691587202601558248218988666773256265", "marketFeeAmountWei": "50000000000000", "priceWei": "1000000000000000"

Did you try the exemple on this offer? Do you also have invalid signature or is it only me?

**Comment by sfriquet** [comment]
Yes you can use either `blockchainId` or `dealId`. 

Regarding the invalid signature issue, we think we've found the issue. It can happen on some secondary market offers with relatively small wei prices.

I'll reply when a fix is deployed.

**Comment by sfriquet** [comment]
We made some changes, do you still have the issue ?

**Comment by oooooblah** [comment]
I now occasionally get "invalid signature" when listing cards with createSingleSaleOffer. Listing Marcelo Brozovic for .0066 ETH worked without problems, listing Luis Lopes for .0068 ETH returned "invalid signature"

**Comment by KittyTools** [comment]
> 



> We made some changes, do you still have the issue ?

Its working now

**Comment by KittyTools** [comment]
> I now occasionally get "invalid signature" when listing cards with createSingleSaleOffer. Listing Marcelo Brozovic for .0066 ETH worked without problems, listing Luis Lopes for .0068 ETH returned "invalid signature"

maybe this can help you:

https://github.com/sorare/api/issues/459

**Comment by oooooblah** [comment]
> I now occasionally get "invalid signature" when listing cards with createSingleSaleOffer. Listing Marcelo Brozovic for .0066 ETH worked without problems, listing Luis Lopes for .0068 ETH returned "invalid signature"

Removing receiverSlug fixed this thanks Kitty & sfriquet
