### ISSUE TITLE
format Amount Bids value 

### ISSUE THREAD

**Issue by Meruem96** [sorare/api#46]
Hello everyone, 

I do not understand the format/meaning of the amount value in bids : 
![image](https://user-images.githubusercontent.com/61518622/139119417-28228fe8-1075-482e-88ca-b5a37160a318.png)

Can someone explain me what the amount means, what kind of units it reprents.

Thank you :)

**Comment by R0hm** [comment]
The amount is in WEI. WEI is to ETH what cents are to euros, or pennies to dollars 😉 
https://www.investopedia.com/terms/w/wei.asp

**Comment by redox** [comment]
Closing this issue as it has now been documented on the GraphQL schema and within our [examples](https://github.com/sorare/api/tree/master/examples).
