### ISSUE TITLE
PrepareOffer authorization None

### ISSUE THREAD

**Issue by Diglee147** [sorare/api#461]
Hello Support Team,

I am working on a project involving countering a direct offer using the Sorare API. At the moment, I am trying to use the prepareOffer mutation, but I am running into an issue.

The issue is that when I execute the prepareOffer mutation, the authorizations field is returning None, although I am expecting a list of AuthorizationRequest objects.

Here is the relevant code I am using to execute the mutation:

prepare_offer_input = {
    "type": "DIRECT_OFFER",
    "receiverSlug": sender_slug,
    "receiveAssetIds": sender_card_ids,
    "receiveWeiAmount": receive_eth,
    "sendAssetIds": receiver_card_ids,
    "sendWeiAmount": send_eth,
    "clientMutationId": mutation_id,
    "settlementCurrencies": ["WEI"]
}

prepare_offer_mutation = """
    mutation PrepareOffer($input: prepareOfferInput!) {
        prepareOffer(input: $input) {
            authorizations {
                id
                fingerprint
                request {
                    ... on StarkexLimitOrderAuthorizationRequest {
                        vaultIdSell
                        vaultIdBuy
                        amountSell
                        amountBuy
                        tokenSell
                        tokenBuy
                        nonce
                        expirationTimestamp
                    }
                }
            }
            limitOrders {
                amountBuy
                amountSell
                expirationTimestamp
                feeInfo {
                    feeLimit
                    tokenId
                    sourceVaultId
                }
                nonce
                tokenBuy
                tokenSell
                vaultIdBuy
                vaultIdSell
            }
            errors {
                message
            }
        }
    }
"""

Could you help me understand why the authorizations field is returning None and how I might resolve this issue?

I appreciate your help in advance.

**Comment by sfriquet** [comment]
Hello. If `authorizations` are empty then you should  sign the returned `limitOrders`. They both represent the same thing, `authorizations` will eventually replace `limitOrders`, but it's not entirely rolled out yet.

**Comment by Diglee147** [comment]
I already got it, sorry, i'm closing
