### ISSUE TITLE
CreateSingleSaleOffer mutation : invalid signature

### ISSUE THREAD

**Issue by KittyTools** [sorare/api#463]
Hello,
Same problem we used to have on AcceptOffer.

Using your exemple generate invalid signature.
Trying to get new fields from prepareOffer (authorizations) same like what is done on the website: return null authorizations.

**Comment by sfriquet** [comment]
Hi, can you share the request/response + your user_id or slug ?

**Comment by KittyTools** [comment]
**Request:**
_PrepareOffer_
mutation NewOfferLimitOrders($input: prepareOfferInput!) {
    prepareOffer(input: $input) {
      limitOrders {
        amountBuy
        amountSell
        expirationTimestamp
        feeInfo {
          feeLimit
          tokenId
          sourceVaultId
        }
        nonce
        tokenBuy
        tokenSell
        vaultIdBuy
        vaultIdSell
      }
      errors {
        message
      }
    }
  }

const prepareOfferInput = {
    type: 'SINGLE_SALE_OFFER',
    sendAssetIds: [sendAssetId],
    receiveAssetIds: receiveAssetIds?.split(',') || [],
    sendWeiAmount: sendWei,
    receiveWeiAmount: receiveWei,
    receiverSlug,
    clientMutationId: crypto.randomBytes(8).join('')
  }

_CreateSingleSaleOffer_
mutation CreateSingleSaleOffer($input: createSingleSaleOfferInput!) {
    createSingleSaleOffer(input: $input) {
      tokenOffer {
        id
      }
      errors {
        message
      }
    }
  }

  const sevenDaysDuration = 60 * 60 * 24 * 7
  const createSingleSaleOfferInput = {
    starkSignatures,
    dealId: crypto.randomBytes(8).join(''),
    assetId: sendAssetId,
    price: receiveWei,
    clientMutationId: crypto.randomBytes(8).join(''),
    duration: sevenDaysDuration,
    startDate: new Date().toISOString()
  }

**Response:**
_PrepareOffer_
{
  limitOrders: [
    {
      amountBuy: '237500',
      amountSell: '1',
      expirationTimestamp: 470893,
      feeInfo: null,
      nonce: xxxx,
      tokenBuy: 'xxxx',
      tokenSell: 'xxxx',
      vaultIdBuy: xxxx,
      vaultIdSell: xxx
    }
  ],
  errors: []
}
_CreateSingleSaleOffer_
invalid signature

**User Slug**: meowmeow7

**Comment by KittyTools** [comment]
Maybe the problem is that the fee info is null while the card got "secondaryMarketFeeEnabled": true ?

**Comment by KittyTools** [comment]
The exemple is on : owen-wolff-2022-limited-250
But happens on many cards

**Comment by sfriquet** [comment]
the `prepareOffer` call you pasted does not fetch `authorizations`, if you fetch them, do they match the returned `limitOrders` ?

**Comment by sfriquet** [comment]
I can also see in some of our logs that you try to prepare a single sale offer and you're setting yourself in the `receiver_slug` input. The receiver slug is meant for direct offer when you're sending an offer to someone else. Don't set this field when preparing a single sale offer.

**Comment by KittyTools** [comment]
If I fetch autrhorizations :

{
  authorizations: null,
  limitOrders: [
    {
      amountBuy: '237500',
      amountSell: '1',
      expirationTimestamp: 470892,
      feeInfo: null,
      nonce: xxx,
      tokenBuy: 'xxx',
      tokenSell: 'xxx',
      vaultIdBuy: xxxx,
      vaultIdSell: xxx
    }
  ],
  errors: []
}

**Comment by KittyTools** [comment]
> I can also see in some of our logs that you try to prepare a single sale offer and you're setting yourself in the `receiver_slug` input. The receiver slug is meant for direct offer when you're sending an offer to someone else. Don't set this field when preparing a single sale offer.

Okay, you got it!
This was the problem, its working now!
Thank you.

Btw, it was always working before.
Only today, setting a receiverSlug when not needed, cause invalid signature.

Anyway, thank you again

**Comment by KittyTools** [comment]
gg

**Comment by sfriquet** [comment]
> Btw, it was always working before.
> Only today, setting a receiverSlug when not needed, cause invalid signature.

Yes, I think I know why. We're in the middle of a migration from `limitOrders` to `authorizations`, the 2 aren't entirely interchangeable so we likely we missed some corner cases based on some combination of inputs...
We'll soon document how to use `authorizations` when creating and accepting offers. We just did for Bid (see Readme). It'll work the same for offers.
