### ISSUE TITLE
hasNextPage is never false

### ISSUE THREAD

**Issue by ZRuchiZ** [sorare/api#466]
Hello,
I'm trying to obtain all of the cards from a specific team, so I have a query like this:

`{
  allCards(
    rarities: limited
    positions: Midfielder
    teamSlugs: ["real-madrid-madrid"]
  ) {
    nodes {
      player {
        lastName
        activeClub {
          name
        }
        slug
        averageScore(type: LAST_FIFTEEN_SO5_AVERAGE_SCORE)
        playingStatus
        so5Scores(last: 5) {
          score
        }
      }
    }
    pageInfo {
      hasNextPage
      endCursor
    }
  }
}
`

After this initial query, i repeat it by adding a Cursor field with the endCursor i just received, and so on until i receive 'hasNextPage' to false, which never happens.
What am I doing wrong?
Thanks in advance!

**Comment by dnz1801** [comment]
Hey there,

Let's break it down step by step:

**Step 1 - Initial Query:**
In your first attempt, fire off your query without the after parameter. This will kickstart things and grab the first page of results. Here's an example of what it might look like:

```graphql
{
  allCards(
    rarities: limited
    positions: Midfielder
    teamSlugs: ["real-madrid-madrid"]
  ) {
    nodes {
      player {
        lastName
        activeClub {
          name
        }
        slug
        averageScore(type: LAST_FIFTEEN_SO5_AVERAGE_SCORE)
        playingStatus
        so5Scores(last: 5) {
          score
        }
      }
    }
    pageInfo {
      hasNextPage
      endCursor
    }
  }
}
```

**Step 2 - Subsequent Queries:**
Now, when you want more, it's time for the next round. For the following queries, add the after parameter. Grab the endCursor value from your previous response and plug it in as the after value. This tells the GraphQL server to start pulling results from where you left off. Here's a playful example of your second query:

```graphql
{
  allCards(
    rarities: limited
    positions: Midfielder
    teamSlugs: ["real-madrid-madrid"]
    after: "PasteYourPreviousEndCursorHere"
  ) {
    nodes {
      player {
        lastName
        activeClub {
          name
        }
        slug
        averageScore(type: LAST_FIFTEEN_SO5_AVERAGE_SCORE)
        playingStatus
        so5Scores(last: 5) {
          score
        }
      }
    }
    pageInfo {
      hasNextPage
      endCursor
    }
  }
}
```

Just make sure you replace "PasteYourPreviousEndCursorHere" with the actual endCursor value from the previous response.

**Comment by ZRuchiZ** [comment]
> Hey there,
> 
> Let's break it down step by step:
> 
> **Step 1 - Initial Query:** In your first attempt, fire off your query without the after parameter. This will kickstart things and grab the first page of results. Here's an example of what it might look like:
> 
> ```graphql
> {
>   allCards(
>     rarities: limited
>     positions: Midfielder
>     teamSlugs: ["real-madrid-madrid"]
>   ) {
>     nodes {
>       player {
>         lastName
>         activeClub {
>           name
>         }
>         slug
>         averageScore(type: LAST_FIFTEEN_SO5_AVERAGE_SCORE)
>         playingStatus
>         so5Scores(last: 5) {
>           score
>         }
>       }
>     }
>     pageInfo {
>       hasNextPage
>       endCursor
>     }
>   }
> }
> ```
> 
> **Step 2 - Subsequent Queries:** Now, when you want more, it's time for the next round. For the following queries, add the after parameter. Grab the endCursor value from your previous response and plug it in as the after value. This tells the GraphQL server to start pulling results from where you left off. Here's a playful example of your second query:
> 
> ```graphql
> {
>   allCards(
>     rarities: limited
>     positions: Midfielder
>     teamSlugs: ["real-madrid-madrid"]
>     after: "PasteYourPreviousEndCursorHere"
>   ) {
>     nodes {
>       player {
>         lastName
>         activeClub {
>           name
>         }
>         slug
>         averageScore(type: LAST_FIFTEEN_SO5_AVERAGE_SCORE)
>         playingStatus
>         so5Scores(last: 5) {
>           score
>         }
>       }
>     }
>     pageInfo {
>       hasNextPage
>       endCursor
>     }
>   }
> }
> ```
> 
> Just make sure you replace "PasteYourPreviousEndCursorHere" with the actual endCursor value from the previous response.

Hi @dnz1801 ,

Thank you so much for your answer!

Alas, that's what I'm doing right now.
The problem is, after the first query, i use a while loop that keeps on firing the second query until i get the "hasNextPage" flag to false, but it really "never" ends.

Just with Real Madrid and Midfielders, it can go on for more than an hour, and it feels like it just repeats the results after a certain amount of queries (or maybe it gives the same player but different season, thing is, it feels weird that it doesn't really never stop).

Have you seen this behaviour before?
Thanks,
Raúl

**Comment by dnz1801** [comment]
Hey Raúl,

It's great to see your interest in the code snippet! Let's dig a bit deeper into why the original `allCards` query might not be the best fit, and why I'm suggesting the alternative method using the `players` field. Check out this refined piece of code:

```graphql
{
  football {
    club(slug: "real-madrid-madrid") {
      players(after: "") {
        nodes {
          lastName
          age
          activeClub {
            name
          }
          slug
          averageScore(type: LAST_FIFTEEN_SO5_AVERAGE_SCORE)
          playingStatus
          so5Scores(last: 5) {
            score
          }
        }
        pageInfo {
          endCursor
          hasNextPage
        }
      }
    }
  }
}
```

Now, to break it down: The original `allCards` query seemed to be fetching one player card at a time, which could lead to repetitive data retrieval. For instance, if Toni Kroos had multiple limited cards, the query might be asking for each card separately, creating a data loop.

Now, the revamped `players` query is like gathering all the players for a data get-together. You grab everyone at once, and then smoothly go through the results using pagination. This approach helps avoid getting the same data multiple times, especially for players with many cards, making your data journey more efficient.

**Comment by ZRuchiZ** [comment]
Hi @dnz1801 ,

That query is just what I needed and brilliant.
I've adjusted my code and it is working beatifully.

Thank you so much!
