### ISSUE TITLE
ERR 503 'Service Temporarily Unavailable' 

### ISSUE THREAD

**Issue by ln-R** [sorare/api#47]
Hello,

I started querying the api to pull basic data, which worked fine for some time. Then after receiving a first "Too Many Requests" error I started getting this error: "Service Temporarily Unavailable" systematically (at least with my IP address) at the first query I try, even days later. 

Does anybody know why and if there's a way to fix this?

Thanks!

**Comment by allspain** [comment]
I am stuck on this as well and it seems to never clear. I was able to get around by VPNing to another location but it's extremely annoying.

**Comment by R0hm** [comment]
The API is rate limited, and when you go beyond that limit, your IP get banned for what seems to be 24 hours.
