### ISSUE TITLE
exchange rate has expired

### ISSUE THREAD

**Issue by sorareway** [sorare/api#471]
Hi team, 

Making a bid on an action according to [the updated API documentation](https://github.com/sorare/api#bidding-on-auction), I'm constantly receiving the GraphQL error `exchange rate has expired` indicating that it's no longer active. The actual info about the exchange rate is the following: `ExchangeRate(id=ExchangeRate:3fe4ff1c-da9a-48fa-8c63-1fb359218758, time=2023-07-28T10:00:00Z)`.

How can I request a valid exchange rate?

**Comment by redox** [comment]
How often do you refresh it @sorareway ?

**Comment by sorareway** [comment]
Since I'm adopting the client to work with a new API, I refresh it on per-bid basis. The last exchage rate I received:
`ExchangeRate(id=ExchangeRate:21d8fd5d-d4e1-4da7-8e63-1dd0fd536095, time=2023-07-28T12:00:00Z)`

**Comment by sorareway** [comment]
If I request `exchangeRateId` now, I receive: `ExchangeRate(id=ExchangeRate:fe8de219-559b-45c6-9c8d-ac428f243c6b, time=2023-07-31T10:00:00Z)`. What does `time` attribute mean: `activeFrom` or `activeUntil`? 

Trying to accept offer or make bid fails due to `exchange rate has expired`. Taking in mind my current timezone (GMT+4), might it be caused by incorrect conversion?

**Comment by AlexCapoen** [comment]
Any updates about this ?

**Comment by sorareway** [comment]
I have finally found the issue in my code. Take into account that exchangeRateId is coming as `ExchangeRate:3fe4ff1c-da9a-48fa-8c63-1fb359218758`, however `acceptOfferInput` or `bidInput` expects it being passed into as `3fe4ff1c-da9a-48fa-8c63-1fb359218758` (no prefix is necessary).
