### ISSUE TITLE
orderedSo5ScoresByPosition per Gameweek / Avoid 20 Player Limit per Position

### ISSUE THREAD

**Issue by JonasAgius** [sorare/api#473]
Hey Guys, 
using the following query for retrieving all So5 Scores per Gameweek. Using "pageinfo" to retrieve "has next page = true" but it seems like there are no other pages??  Any idea? is there another way to realize my goal? It's working but I only receive 20 results per postion. Also Playground showing "has next page = false". Thanks in advance

`query = """
query findso5($slug: String!, $position: String!, $cursor: String) {
  so5 {
    so5Fixture(slug: $slug) {
      orderedSo5ScoresByPosition(first: 1000, position: $position, after: $cursor, minScore: 20) {
        pageInfo {
          hasNextPage
          endCursor
        }
        edges {
          node {
            id
            score
            decisiveScore {
              totalScore
            }
            player {
              slug
              displayName
              position
              activeClub {
                slug
              }
            }
          }
        }
      }
    }
  }
}
"""`

**Comment by samatt1234** [comment]
Try removing `first: 1000`. It will return 50 nodes maximum anyway so it does not serve any purposes.
