### ISSUE TITLE
VALIDATION_INVALID_TYPE_VARIABLE on createDirectOffer

### ISSUE THREAD

**Issue by Mastafis** [sorare/api#475]
Hello,
i'm trying to create a direct offer with this mutation:
`        mutation CreateDirectOffer($input: createDirectOfferInput!) {
        createDirectOffer(input: $input) {
            tokenOffer {
            id
            }
            errors {
            code
            message
            path
            }
        }
        }
`

this is the createDirectOfferInput:
`
{'approvals': [{'fingerprint': 'c7580d3ffe1c5e82a89a3920fec090b9', 'starkexLimitOrderApproval': {'nonce': 107240, 'expirationTimestamp': 471142, 'signature': '{"r":"0x0000","s":"0x0000"}'}}], 'clientMutationId': '2214685245224131582', 'dealId': '1952252412139924116056', 'receiveAssetIds': ['0x04001776c58369de3ca699cb2d932102993df90f01f9ade9c0bd5b3429647207'], 'sendAssetIds': [], 'sendAmount': {'amount': '1500000000000000.0000', 'currency': 'WEI'}, 'receiverSlug': 'spizzico-open-to-trade'}
`

the query returns me this error:
`
{"errors":[{"message":"invalid type for variable: \"input\"","extensions{"name":"input","code":"VALIDATION_INVALID_TYPE_VARIABLE"}}]}
`

where did I go wrong??

**Comment by sfriquet** [comment]
Most likely you are not passing the variable correctly. You can take a look at our examples for reference.
