### ISSUE TITLE
Balance cash wallet

### ISSUE THREAD

**Issue by AlexCapoen** [sorare/api#477]
Hello,

Is it possible to retrieve the balance of the cash wallet using the query "currentUser" as it is possible with the "totalBalance" field for the wei value?

**Comment by redox** [comment]
Yes, do:

```graphql
{
  currentUser {
    slug    
    accounts {
      accountable {
        ... on FiatWalletAccount {
          availableBalance
          totalBalance
        }
      }
    }
  }
}
```

We'll add it to the root of the `currentUser` soon.

**Comment by AlexCapoen** [comment]
Thank you for the quick response.
I also have another question regarding the subscription tokenOfferWasUpdated and more precisely the field priceFiat. It doesn't seem to be working ("Only subscribable fields are allowed for this subscription").
