### ISSUE TITLE
Last xx completed offers

### ISSUE THREAD

**Issue by dinoderossi** [sorare/api#49]
I try but i don't find how write the query to extract the last xx(10 or 20) completed offers. It is possible?

**Comment by dinoderossi** [comment]
I have found only the query for the lastauction ( but i want the completed and not the auctions but the offers)
`{
transferMarket{
 englishAuctions(first:10){
  nodes{
    cards{
      name
    }
  }
}
}
}`

**Comment by feikede** [comment]
Need this, too!

BTW, you don't need the "transferMarket" if you go for sso,
```
{
  singleSaleOffers(before: "", first: 2) {
    totalCount
    pageInfo {
      endCursor
    }
    nodes {
      startDate
      open
 ...
```

**Comment by redox** [comment]
> To my knowledge there is no way of querying this generally without pulling in every single card (eg for a particular player). Unless you are able to use aCardWasUpdated

Yes that's correct.

>  and update in real time but this is beyond the scope for most small scale operators.

> I think the API and info provided on github are fantastic (thanks for all the hard work guys)

Thank you 😎 

> but I do think this lack of ability to do a general query on recent trades is a pretty significant flaw.

I understand @IDunnoSure; unfortunately providing such additional APIs is slightly off track compared to our current focus. I'm convinced we're going to continue to improve the API and add additional endpoints it but not in the short term.
