### ISSUE TITLE
Single Sale Offer

### ISSUE THREAD

**Issue by AlDuchanEng** [sorare/api#490]
Hi
I am taking 3 files from the official examples. package.json, single sale offer example as well as authorizations.js.
I keep getting the same error "The error message indicates that there's a conflict with the amount field in your GraphQL query. Specifically, in some cases, the field expects a return type of String!, and in others, it expects Int!. Since GraphQL is strongly typed, fields with the same name that are queried for different types will lead to conflicts.

To resolve this, you can use aliases in your GraphQL query. An alias allows you to rename the result of a field to something different than the actual field name."
I do not understand how to get around that issue.
... on StarkexTransferAuthorizationRequest {
    starkexAmount: amount
    ...
}
...
... on MangopayWalletTransferAuthorizationRequest {
    nonce
    mangopayAmount: amount
    ...
}
this solution does not work for some reason.

**Comment by KittyTools** [comment]
https://github.com/sorare/api/pull/481

**Comment by AlDuchanEng** [comment]
Now I am getting this, it seems that my authorizations consist of only my private key for some reason. I use the codes provided in the examples.
TypeError: authorizations.map is not a function

**Comment by AlDuchanEng** [comment]
do not know how but when i run everything from one file instead of createsinglesaleoffer and authorizations it worked
