### ISSUE TITLE
Alternative way to get live single sale offers

### ISSUE THREAD

**Issue by reekoz** [sorare/api#497]
Hello, first of all congrats for the work you do for the API =)

Reading docs and gh issues, I've realized that the only way to get all the living single sale offers for a particular player is to fetch all player's card (using cursor because result is paginated).

I just wondering if maybe there is an alternative way to get them, maybe using `token` query filtering by player `id`/`slug` all `TokenOffer`s live.

Thank you!

**Comment by redox** [comment]
Thanks for the kind words @reekoz . Indeed this is the only way for now, but we agree we need to provide some additional browsing/listing features to ease this. I cannot provide any ETA but I hope to be able to do something in the next couple of months.

**Comment by reekoz** [comment]
Thanks @redox  sounds great!

Meantime I will continue to use the "old school" way 😄

**Comment by reekoz** [comment]
@redox just for information, do you know a Sorare user named `Bellona`? He uses a bot/software to buy a card almost instantly, seems like he can access all living single sale offers of a particular player, without fetch all player's card, and check one by one which are for sale and at what price. 

Maybe he has build in these years a local database that keep updated with all players offers in the market...who knows? :)

**Comment by hagilani** [comment]
> @redox just for information, do you know a Sorare user named `Bellona`? He uses a bot/software to buy a card almost instantly, seems like he can access all living single sale offers of a particular player, without fetch all player's card, and check one by one which are for sale and at what price.
> 
> Maybe he has build in these years a local database that keep updated with all players offers in the market...who knows? ;-)

Bellona is one of the developers. Bellona has access to DB and finds cards that in 2 minutes cancelation time and the executes the purchasing request before anyone else.
I've spent too much time to beat Bellona. That's impossible.

**Comment by redox** [comment]
> > @redox just for information, do you know a Sorare user named `Bellona`? He uses a bot/software to buy a card almost instantly, seems like he can access all living single sale offers of a particular player, without fetch all player's card, and check one by one which are for sale and at what price.
> > Maybe he has build in these years a local database that keep updated with all players offers in the market...who knows? ;-)
> 
> Bellona is one of the developers. Bellona has access to DB and finds cards that in 2 minutes cancelation time and the executes the purchasing request before anyone else. I've spent too much time to beat Bellona. That's impossible.

I can confirm Bellona is not a developer or any sort of Sorare employee with any sort of access to our DB or to a magic/private API.

That being said, I've been very impressed by the way they have been optimizing their code, the number of API calls they do, the size of the requests, the heuristics they use to accept offers, their understanding of our infrastructure, etc...

Good luck beating them!

**Comment by hagilani** [comment]
> > > @redox just for information, do you know a Sorare user named `Bellona`? He uses a bot/software to buy a card almost instantly, seems like he can access all living single sale offers of a particular player, without fetch all player's card, and check one by one which are for sale and at what price.
> > > Maybe he has build in these years a local database that keep updated with all players offers in the market...who knows? ;-)
> > 
> > 
> > Bellona is one of the developers. Bellona has access to DB and finds cards that in 2 minutes cancelation time and the executes the purchasing request before anyone else. I've spent too much time to beat Bellona. That's impossible.
> 
> I can confirm Bellona is not a developer or any sort of Sorare employee with any sort of access to our DB or to a magic/private API.
> 
> That being said, I've been very impressed by the way they have been optimizing their code, the number of API calls they do, the size of the requests, the heuristics they use to accept offers, their understanding of our infrastructure, etc...
> 
> Good luck beating them!

Thanks for your response. To be honest, purchasing cards before anyone can try to buy, only needs access to APIs or Bugs behind Scene. The Main problem is Bellona Makes the orders before we receive the message from the web socket.
Respectfully, I'm asking you. Who can trigger a purchase call before the card info reaches the others?
