### ISSUE TITLE
Unable To Find Token With Asset_id - CreateDirectOffer

### ISSUE THREAD

**Issue by philnind** [sorare/api#498]
I am trying to create a direct offer where the sendAssetId is blank, however when I do this it seems to autopopulate that field with       tokenSell: '0xb333e3142fe16b78628f19bb15afddaef437e72d6d7f5c6c20c6801a27fba6', and then giving me the unable to find token with asset_id .

Essentialy I am trying to create a counter offer system here where we remove one card and offer just cash/eth...

**Comment by redox** [comment]
the `0xb333e3142fe16b78628f19bb15afddaef437e72d6d7f5c6c20c6801a27fba6` asset_id is the internal `asset_id` we use for ETH actually, so the fact you see it in `tokenSell` is expected but you should not try to find the associated card. It's safe to use it as a constant.

Good luck with the implementation!

**Comment by philnind** [comment]
Thanks for your answer, can you explain why I am seeing the "Unable to find token with asset_id" error then.

I have looked into the console.log(JSON.stringify(createDirectOffer, null, 2)); and then token object is showing Null. Why would this be?
