### ISSUE TITLE
Price meaning

### ISSUE THREAD

**Issue by descovi** [sorare/api#5]
How do I interpret the value of the price key?

1000000000000000000 it's very big :-)

![Graphql price](https://user-images.githubusercontent.com/104249/105737374-25ae8880-5f36-11eb-90dc-3d9a26757167.png)

Same for owners price in the past.

This is my query

```
{
  card(slug: "cristiano-ronaldo-dos-santos-aveiro-2020-rare-10") {
          id
          name
          position
          price
          slug
          owner {
            ownerable {
              ... on User {
               nickname
             }
           }
          }
          owners {
            ownerable {
               ... on User {
                nickname
              }
            }
            from
            price
          }
          club {
            name
          }
          ... on WithPictureInterface {
            pictureUrl
          }
        }
}
```

**Comment by Vinedine** [comment]
The number is in WEI format to convert to ETH you can use a library.

Depending on what programming language you use there are different libraries available;

https://medium.com/@piyopiyo/how-to-convert-ether-from-wei-and-vice-versa-with-web3-1-0-0-3e3e691e3f0e
https://docs.nethereum.com/en/latest/Nethereum.Workbooks/docs/nethereum-converting-units/

**Comment by descovi** [comment]
Ah ok! Thanks!
I'm a Rubyist.

I found only [this gem](https://github.com/DigixGlobal/ethereum-ruby) but the last update is 2016.
But it has what I need
https://github.com/DigixGlobal/ethereum-ruby/blob/2c9b79c3e9f9e1f8f9569fb26162888a081c0e38/lib/ethereum/formatter.rb#L79

I extract this converter in a more simple gist  ready to copy-paste ✂️ 
https://gist.github.com/descovi/5056ab3f433db61c7c19d040c4c03921

```
# Example of usage: 
# result = WeiConverter.new(1890000000000000000).call
# Result contains 1.89

class WeiConverter

  UNITS = {
    wei:        1,
    kwei:       1000,
    ada:        1000,
    femtoether: 1000,
    mwei:       1000000,
    babbage:    1000000,
    picoether:  1000000,
    gwei:       1000000000,
    shannon:    1000000000,
    nanoether:  1000000000,
    nano:       1000000000,
    szabo:      1000000000000,
    microether: 1000000000000,
    micro:      1000000000000,
    finney:     1000000000000000,
    milliether: 1000000000000000,
    milli:      1000000000000000,
    ether:      1000000000000000000,
    eth:        1000000000000000000,
    kether:     1000000000000000000000,
    grand:      1000000000000000000000,
    einstein:   1000000000000000000000,
    mether:     1000000000000000000000000,
    gether:     1000000000000000000000000000,
    tether:     1000000000000000000000000000000
  }

  def initialize(amount)
    @amount = amount
  end

  def call(unit: "ether")
    return nil if @amount.nil?
    unit = UNITS[unit.to_sym]
    (BigDecimal.new(@amount, 16) / BigDecimal.new(unit, 16)).to_s rescue nil
  end
end
```

Now is ok 👍 thanks a lot!

![imagine sorare ronaldo](https://user-images.githubusercontent.com/104249/105747016-7f1bb500-5f40-11eb-8de6-0af1b9dd066d.png)
