### ISSUE TITLE
Where to find all players `slug`?

### ISSUE THREAD

**Issue by saifulshihab** [sorare/api#50]

**Comment by BMorvillez** [comment]
You can get all competitions slugs with this :
{
  config{  
    so5LeaguesAlgoliaFilters
	}
}

Then, retrieve players slugs by querying competitions as follows:
{
  competition(slug: "[INSERT competition slug here]") {
    clubs {
      nodes {
        name
        slug
        activePlayers {
          nodes {
            displayName
            slug
          }
        }
      }
    }
  }
}

**Comment by BMorvillez** [comment]
You can get all competitions slugs with this :
{
config{
so5LeaguesAlgoliaFilters
}
}

Then, retrieve players slugs by querying competitions as follows:
{
competition(slug: "[INSERT competition slug here]") {
clubs {
nodes {
name
slug
activePlayers {
nodes {
displayName
slug
}
}
}
}
}
}

**Comment by saifulshihab** [comment]
@BMorvillez I don't get what you suggested, I want all players slug, like this one
![image](https://user-images.githubusercontent.com/45540333/141653346-2f5854c3-fb30-43fc-b418-94b3ed3f6409.png)

**Comment by BMorvillez** [comment]
@saifulshihab from the least I know you can't get all players slugs through one request
I needed to get competitions/clubs/players and above is how I did it
You first get competitions slugs, then you request to get clubs/players

**Comment by saifulshihab** [comment]
@BMorvillez thabks for time. One thing, Can I get response from my own react app, i am trying but it shows CORS error, Is there anything that we need to have to send the request to their graphql api server?

**Comment by feikede** [comment]
No. You need a proxy-host cause sorare.com don't want to serve requests from third party client apps.

**Comment by redox** [comment]
>> @BMorvillez thanks for time. One thing, Can I get response from my own react app, i am trying but it shows CORS error, Is there anything that we need to have to send the request to their graphql api server?

> No. You need a proxy-host cause sorare.com don't want to serve requests from third party client apps.

Correct, I've documented it in https://github.com/sorare/api#cors

> @saifulshihab from the least I know you can't get all players slugs through one request

Correct, as this isn't necessarily something we want to encourage using our API for, for now at least.

Closing this as it's all resolved.

**Comment by saifulshihab** [comment]
Thanks @redox <3
