### ISSUE TITLE
tokens.liveSingleSaleOffers(playerSlug) not exhaustive

### ISSUE THREAD

**Issue by KittyTools** [sorare/api#507]
Hello 
If we filter tokens.liveSingleSaleOffers with playerSlug, it returns a no exhaustive live single sale offers for that player.
Missing a lot of offers on many players.

This request is a great way to avoid taking all the cards and filter out no listed cards.
Would definitly use it if it could return all data

cheers

**Comment by redox** [comment]
Yes, we didn’t communicate yet of this new argument because of this exact reason. We have some technical limitations making it more complex than expected to implement exhaustivity; I might flag it as experimental until it’s working.

**Comment by reekoz** [comment]
Can we assume that query `tokens.liveSingleSaleOffers` returns always the min live offer for a player in the first set of results?
 
I've tested this query and for now it returns only "one page" of results (if I use param `after` with a valid `endCursor` it returns no results)

**Comment by redox** [comment]
Hey @KittyTools and @reekoz ; could you retry now and confirm it's exhaustive?

**Comment by KittyTools** [comment]
Look like good for now!

**Comment by reekoz** [comment]
for me second page is always null, so still missing some live offers

**Comment by KittyTools** [comment]
> for me second page is always null, so still missing some live offers

Could you give an exemple of a player-slug with more than 40 liveSingleSaleOffers and a null second page?

**Comment by KittyTools** [comment]
Because you count the auctions as a liveSingleSaleOffers, there is 3 auctions + 13 managers sales on wirtz

**Comment by KittyTools** [comment]
@redox 
Look at those exemples :

**Query**: 
`liveSingleSaleOffers(playerSlug: "randal-grichuk-19910813") { [...] }`
**Response**: 
```
[...]
          {
            "priceWei": "13100000000000000",
            "senderSide": {
              "nfts": [
                {
                  "card": {
                    "slug": "randal-grichuk-19910813-2022-rare-23",
                    "rarityBaseBall": "rare",
                    "totalBonus": 0.155,
                    "seasonBaseBall": "2022"
                  },
                  "owner": {
                    "user": {
                      "slug": "gaffattack"
                    }
                  }
                }
              ]
            }
          }
[...]
```
**If I look on the frontend**:
https://sorare.com/mlb/cards/randal-grichuk-19910813-2022-rare-23
price Eth : 0.0127 (Should be 0.0131 if priceWei would be 13100000000000000)

Another exemple :

**Query**: 
`liveSingleSaleOffers(playerSlug: "jose-iglesias-19900105") { [...] }`
**Response**: 
```
[...]
{
            "priceWei": "7400000000000000",
            "senderSide": {
              "nfts": [
                {
                  "card": {
                    "slug": "jose-iglesias-19900105-2022-rare-35",
                    "rarityBaseBall": "rare",
                    "totalBonus": 0.15000000000000002,
                    "seasonBaseBall": "2022"
                  },
                  "owner": {
                    "user": {
                      "slug": "josephsavage"
                    }
                  }
                }
              ]
            }
          }
[...]
```
**If I look on the frontend**:
https://sorare.com/mlb/cards/jose-iglesias-19900105-2022-rare-35
price Eth : 0.0073 (Should be 0.0074 if priceWei would be 7400000000000000)


Do you know why?

**Comment by redox** [comment]
> @redox Look at those exemples :
> 
> **Query**: `liveSingleSaleOffers(playerSlug: "randal-grichuk-19910813") { [...] }` **Response**:
> 
> ```
> [...]
>           {
>             "priceWei": "13100000000000000",
>             "senderSide": {
>               "nfts": [
>                 {
>                   "card": {
>                     "slug": "randal-grichuk-19910813-2022-rare-23",
>                     "rarityBaseBall": "rare",
>                     "totalBonus": 0.155,
>                     "seasonBaseBall": "2022"
>                   },
>                   "owner": {
>                     "user": {
>                       "slug": "gaffattack"
>                     }
>                   }
>                 }
>               ]
>             }
>           }
> [...]
> ```
> 
> **If I look on the frontend**: https://sorare.com/mlb/cards/randal-grichuk-19910813-2022-rare-23 price Eth : 0.0127 (Should be 0.0131 if priceWei would be 13100000000000000)
> 
> Another exemple :
> 
> **Query**: `liveSingleSaleOffers(playerSlug: "jose-iglesias-19900105") { [...] }` **Response**:
> 
> ```
> [...]
> {
>             "priceWei": "7400000000000000",
>             "senderSide": {
>               "nfts": [
>                 {
>                   "card": {
>                     "slug": "jose-iglesias-19900105-2022-rare-35",
>                     "rarityBaseBall": "rare",
>                     "totalBonus": 0.15000000000000002,
>                     "seasonBaseBall": "2022"
>                   },
>                   "owner": {
>                     "user": {
>                       "slug": "josephsavage"
>                     }
>                   }
>                 }
>               ]
>             }
>           }
> [...]
> ```
> 
> **If I look on the frontend**: https://sorare.com/mlb/cards/jose-iglesias-19900105-2022-rare-35 price Eth : 0.0073 (Should be 0.0074 if priceWei would be 7400000000000000)
> 
> Do you know why?

We need to remove the `priceWei` and `priceFiat` fields. Rather use:

```
        marketFeeAmounts {
          wei
          eur
          gbp
          usd
        }
        senderSide {
          nfts {
            slug
          }
          amounts {
            wei
            eur
            gbp
            usd
          }
        }
        receiverSide {
          nfts {
            slug
          }
          amounts {
            wei
            eur
            gbp
            usd
          }
        }
```
