### ISSUE TITLE
Subscription - aCardWasUpdated - Add filter sport (for NBA)

### ISSUE THREAD

**Issue by jmallot21** [sorare/api#509]
Currently for the aCardWasUpdated() method only FOOTBALL sport cards are updated.

Could you add a filter that would allow you to retrieve modifications on MLB/NBA cards?

`
subscription onAnyCardUpdated  { 
    aCardWasUpdated(sport: NBA) { 
        slug
        customCardEditionName
        player { slug } 
        token { collection }
      }
}
`

Thanks in advance.

**Comment by redox** [comment]
Hey @jmallot21 ,

the `aCardWasUpdated` is a legacy event that is indeed not usable for anything else than football cards.

Our new strategy is not anymore to notify about card event, but only focus on event triggered by auction or offers. Therefore, you should switch to `tokenAuctionWasUpdated` and `tokenOfferWasUpdated` that have both a way to filter by sport.

What have you been trying to implement?

**Comment by jmallot21** [comment]
On the SorareNbaJet project I store the entire market. All cards, their owner and sales.

Unfortunately I am unable to be notified via subscriptions when a SINGLE_BUY_OFFER or DIRECT_OFFER is accepted by a seller manager.
Therefore, my database is not up to date.

I would like to find a way to subscribe to these events.

However, I understand that it is not possible to subscribe to the SINGLE_BUY_OFFER and DIRECT_OFFER which have just been created.
I just want to be notified when they are accepted.

Is this currently possible?

**Comment by redox** [comment]
Makes sense, currently it's indeed not possible but time has maybe come to challenge this. I'll check what we can do.

**Comment by jmallot21** [comment]
Great news.

This will allow us to maintain consistency in our data and be able to remain “synchronized” with Sorare.

I can't wait to implement this :)
Thanks.

**Comment by jmallot21** [comment]
Have you been able to make progress on this subject?

Again, adding this method would avoid a lot of unnecessary calls.
