### ISSUE TITLE
Average score over the past 5 games

### ISSUE THREAD

**Issue by dunaevv** [sorare/api#51]
Guys, does anybody know, how can I get these values?
![avarages](https://user-images.githubusercontent.com/83603430/143310614-6439e61b-02b4-4277-ab19-bc7999a76f02.png)

**Comment by feikede** [comment]
You get L5 and L15 from api.sorare.com, i.e. like this:
```
{
card(slug:"raul-albiol-tortajada-2021-rare-14")
  {
  player{
    subscriptionsCount
    allSo5Scores(first:5) {nodes {score}}
    status {
              lastFifteenSo5Appearances
              lastFifteenSo5AverageScore
              lastFiveSo5Appearances
              lastFiveSo5AverageScore
              playingStatus
         }
     }
  }
}
```
Think L40 is calculated by sorare-data's own data collection.
