### ISSUE TITLE
currentUser.nbaCard - Add param playersSlug

### ISSUE THREAD

**Issue by jmallot21** [sorare/api#510]
Hi,

Would it be possible to add a parameter `playersSlug` to the method `currentUser.nbaCard()` ?
![image](https://github.com/sorare/api/assets/52312768/4bd98c31-5141-4b6f-b6df-f2444a53af30)

This would allow us to be much more efficient in some of our searches and would avoid having to go through the entire list of cards each time.

Thanks

**Comment by jmallot21** [comment]
I would like to relaunch this proposal which would provide **great flexibility** in the use of the API and which would avoid a large number of **unnecessary calls**.

Please take this request into consideration.
Thanks.

**Comment by jmallot21** [comment]
Hi, 

This filter is available for FOOTBALL with *paginatedCards(playerSlugs:[])*
![image](https://github.com/sorare/api/assets/52312768/a584b1d5-cb8c-4005-83a4-e8c45af5c7b0)

Can you add this filter **playerSlugs** for *nbaCards()* please ? 

Thanks in advance. @redox

**Comment by utay** [comment]
Hi @jmallot21, we have added the `playerSlugs` filter to `nbaCards` for `user` and `currentUser` query fields

**Comment by jmallot21** [comment]
Thank you so much ! That's great info ;)
