### ISSUE TITLE
nbaPlayer.cards() - Add parameter inSale 

### ISSUE THREAD

**Issue by jmallot21** [sorare/api#512]
Would it be possible to add the `inSale` parameter in the `nbaPlayer.cards()` method.
This parameter would allow you to quickly retrieve only the cards on sale.

![image](https://github.com/sorare/api/assets/52312768/7d2c8aef-853b-4c55-9716-7b816c5ac35f)

This would save us from having to go through the entire list of player cards to collect only those for sale.

What do you think about ?

**Comment by KittyTools** [comment]
There is an experimental version of this already in tokenRoot, hopefully it will return exhaustive results at some point

**Comment by jmallot21** [comment]
True. It's `tokens.tokenPrices()` .
![image](https://github.com/sorare/api/assets/52312768/99375488-72ae-47a9-8995-dddfbe7ec61b)

Thx . I close .

**Comment by jmallot21** [comment]
Done !
