### ISSUE TITLE
Need a nbaLineups() method

### ISSUE THREAD

**Issue by jmallot21** [sorare/api#522]
It is possible to call the `nbaLineup()` function to retrieve lineup information.

But would it be possible to do a `nbaLineups(ids: [])` method available in order to drastically reduce the number of calls?

Thanks in advance.

**Comment by jmallot21** [comment]
This method could save a LOT of queries...

Do you think this is feasible?

**Comment by jmallot21** [comment]
Thank you Yannick.

On the other hand, there is a problem when one of the lineupUids passed in the list does not exist in Sorare.
![image](https://github.com/sorare/api/assets/52312768/7532eab9-9f3a-48ab-a63d-6333502cac0b)
![image](https://github.com/sorare/api/assets/52312768/71ee7ffc-6e1f-45a4-a424-b4fb3a48b70f)

It throws an error without explaining why.
![image](https://github.com/sorare/api/assets/52312768/47bd2ae6-2c24-42ca-93e5-5183cf50fb42)

Could it be possible that there is simply no information returned for this non-existent lineup?

Thanks in advance.

**Comment by jmallot21** [comment]
I can't reopen this issue. Sorry !

**Comment by utay** [comment]
@jmallot21 Thanks for reporting, this is fixed now :)

**Comment by jmallot21** [comment]
Yes, it works fine now.
Thanks ;)
