### ISSUE TITLE
BUG : Authenticated Call - Complexity max 500 

### ISSUE THREAD

**Issue by jmallot21** [sorare/api#526]
I have been experiencing a strange bug for some time on my calls.
On certain calls I am limited to a complexity of 500 while I pass a valid and unexpired user token.

Example with this call:
```
{ currentUser {
	depositedEth 
	sorareAddress 
	ethereumAddress
	pendingDeposits { date id amount }
	accountEntries(entryType: [DEPOSIT,WITHDRAWAL,WITHDRAWAL_FEE]){
		pageInfo { hasNextPage endCursor }
		nodes{
		    id  amount 
		    amounts { wei eur usd gbp }
		    provisional date
		    entryType
		}
	}
}
}
```
With this headers :
![image](https://github.com/sorare/api/assets/52312768/6020dfbc-1ff7-4df8-b556-937f2ff57b93)

The response : 
`Query has complexity of 516, which exceeds max complexity of 500. Using an APIKEY the limit would be 30000.`

Why am I limited even though I am authenticated with an unexpired token?

**Comment by jmallot21** [comment]
If I make the call without `amounts { wei eur usd gbp }` then it works correctly.
Which clearly proves that my token is valid because I call the `currentUser` method.

**Comment by utay** [comment]
We had a bug where OAuth tokens were subject to the anonymous complexity limit and it's now fixed. Do you confirmed @jmallot21? Please reopen if it's not the case
