### ISSUE TITLE
Get last price players card sold

### ISSUE THREAD

**Issue by rikidas** [sorare/api#53]
Hi, im trying to passing a player name the query returns the last price payed for him.

I just think thats possible passing the card slug one by one and then picking the last price.

Is there any way to make it faster? 

Thanks

**Comment by feikede** [comment]
You can use a query like 
```
query cardQuery($cardSlugs:[String!]!) {
cards(slugs:$cardSlugs)
  {
    userOwnersWithRate {price}
    liveSingleSaleOffer {price}
  }
}
```
Just pass your array of cardSlugs as parameter.

**Comment by feikede** [comment]
If you don't want to fetch all card-slugs, use something like this:
```
{ player(slug:"raul-albiol-tortajada") {
  cards {
    nodes {
  	slug
  	userOwnersWithRate{price}
    }
  }
}
}

```

**Comment by rikidas** [comment]
> If you don't want to fetch all card-slugs, use something like this:
> 
> ```
> { player(slug:"raul-albiol-tortajada") {
>   cards {
>     nodes {
>   	slug
>   	userOwnersWithRate{price}
>     }
>   }
> }
> }
> ```

Thanks, that query helps me a lot, also i ve been searching on how to filter by rarity but i cant find any way to do it.

Someone knows any way to do it?

**Comment by loziobiz** [comment]
> 

I guess you need to fetch all player cards using pagination and filter it by yourself. Do it carefully because api is limited and you have to throttle your requests

**Comment by ngocdhoang** [comment]
> If you don't want to fetch all card-slugs, use something like this:
> 
> ```
> { player(slug:"raul-albiol-tortajada") {
>   cards {
>     nodes {
>   	slug
>   	userOwnersWithRate{price}
>     }
>   }
> }
> }
> ```

This doesn't work for me, can you give an example of a player that can be found in Soraredata? 

Also, is it possible to download this data?

**Comment by feikede** [comment]
Go https://api.sorare.com/graphql/playground and paste the code on the left side saying "# Write your query or mutation here". Then press the big play button.
To download the data you have to implement any gql client.

**Comment by ngocdhoang** [comment]
> Go https://api.sorare.com/graphql/playground and paste the code on the left side saying "# Write your query or mutation here". Then press the big play button. To download the data you have to implement any gql client.

Thank you for your reply!

Yes, I tried that and was able to see data for  "slug": "raul-albiol-tortajada-2021-common-84507f19-6f64-48ad-9c2d-32ce62dd7368", but when I changed the parameter to a different player's name (for example, "lionel-messi":

`{ player(slug:"lionel-messi") {
  cards {
    nodes {
  	slug
  	userOwnersWithRate{price}
    }
  }
}
}`

It returned: "Record not found"

I am new to GraphQL so any help is appreciate! 

Thank you,

NG

**Comment by feikede** [comment]
That's because the player slug is wrong, check https://sorare.com/players/lionel-messi
You'll find the correct slug in the URL on sorare.com

**Comment by redox** [comment]
Thank you @feikede for your help, much appreciated. Closing this issue.
