### ISSUE TITLE
BUG - tokenAuctionWasUpdated Doesn't always work

### ISSUE THREAD

**Issue by jmallot21** [sorare/api#530]
Good morning,

The token Auction Was Updated(sports: [NBA]) method does not always return me information when a new auction is added to a card.
How to overcome this problem?

I just did the test by adding a bid on a card and I received nothing in the subscriber.

Thanks

**Comment by jmallot21** [comment]
![image](https://github.com/sorare/api/assets/52312768/9fc8aa13-bc0e-4d5e-aa4c-793e1d950ea2)
However the documentation indicates that the call is made at each auction and at the end.

**Comment by redox** [comment]
> I just did the test by adding a bid on a card and I received nothing in the subscriber.

This is surprising, from time to time you can have up to a few minutes of lag - could this be related?

**Comment by jmallot21** [comment]
This is not what I detected.
Sometimes I never receive the call even though the underwriter is running fine.

When I see an example, I'll add it here.
