### ISSUE TITLE
Subscription - tokenOfferWasUpdated - Impossible access to card fields

### ISSUE THREAD

**Issue by jmallot21** [sorare/api#531]
It is currently impossible to access card fields from the `tokenAuctionWasUpdated()` and `tokenOfferWasUpdated()` methods

Example call:
![image](https://github.com/sorare/api/assets/52312768/3e4b25a8-ebd2-4a2e-81d8-180a52d4feaf)

Reponse :
```Field 'id' doesn't exist on type 'NBACard'```

However the documentation indicates that it is possible to access it.
![image](https://github.com/sorare/api/assets/52312768/671b1693-0b82-42c6-8aea-e7e7f5a32298)

**Comment by redox** [comment]
> It looks like AnyCard here works only for Card (football card).
> I am looking forward to when full support for AnyCard will be available in this subscription.

That is correct @miroshnik - we'll work on improving this in the next few weeks but so far it's indeed not possible. We should have removed this field from the subscription payload until we support all sports; sorry about this.
