### ISSUE TITLE
How to track player changes?

### ISSUE THREAD

**Issue by arik555** [sorare/api#54]
Hello @such @spinach @thom-des @piedup 
1. I fetch player information, like memberships, so5scores (at the moment of fetch).
2. I fetch all the cards, for that player (at the moment of fetch).
3. Subscriptions not working. Getting this issue: [https://github.com/ecthiender/py-graphql-client/issues/31](url)
4. I am using APIKEY header, but the limit still remains.

Now, 
how can I track or know, if there's any **new cards** (auctions + offers) added for that player?
also, how can I track if there is any **new memberships** for that player (switched some club, for example)?

**Comment by 8lank** [comment]
I have the same issue, although I try to get all the cards for a player using the API directly. But the order used for returning the cards is unreliable, so I have to iterate through all the cards to get the new ones. I have added the issue here: https://github.com/sorare/api/issues/44.

**Comment by redox** [comment]
We're working on adding filters to `allCards`; and will then figure out whether we can easily port those filters to the subscription.

In the meantime, did you try again the subscriptions now that it's documented here https://github.com/sorare/api#subscribing-to-graphql-events ?
