### ISSUE TITLE
password foramt in SignInMutation is changed

### ISSUE THREAD

**Issue by script-money** [sorare/api#540]
```json
{
    "operationName": "SignInMutation",
    "variables": {
        "input": {
            "email": "hello@script.money",
            "password": "$2a$11$you1aoHx4Hmw.AglGL3VruBnD5tOD8Qz7t/DBtG9vurYjY5MZe/s2",
            "deviceFingerprint": "50118236fafa9d4863363624079e46cd,47c28966832ee74cd871fef6a43d309e",
            "impactClickId": null
        }
    },
    "extensions": {
        "operationId": "React/d1c635749e896ffc5b21bf08f43dde40a5f0c753480128202e099c7f9f52290c"
    }
}
```
but ` bcrypt.hashpw(password.encode("utf-8"), salt.encode("utf-8"))` result is `$2a$11$you1aoHx4Hmw.AglGL2VrucEMqVzJBur3BnNnvmQv5hA1lcqlOnGC`. The password format is different.
How can I generate new password format?

**Comment by utay** [comment]
@script-money Our password format didn't change. Did you enter the right password and salt?

**Comment by script-money** [comment]
> @script-money Our password format didn't change. Did you enter the right password and salt?

My password is not right
