### ISSUE TITLE
Problem with cancelOffer mutation

### ISSUE THREAD

**Issue by koenigskebap** [sorare/api#546]
Hello,

i am trying to cancel a Listing from the secondary Market. So for this I am using the cancelOffer mutation. So far right?

I tried in Playground and in my app and I always get the same error output.

This is my code (I tried several versions, also more simple ones):

mutation cancelOffertest {
  cancelOffer(
    input: {blockchainId: "82732287523261805210001967584728013613256425403223149948231204855218149445007", clientMutationId: "da9080192f7e9af3"}
  ) {
    clientMutationId
    currentUser {
      id
      email
    }
    errors {
      code
      message
      path
    }
    tokenOffer {
      blockchainId
      status
    }
  }
}

This is the error output:

{
  "errors": [
    {
      "message": "Offer(id=) not found",
      "extensions": {
        "code": "NOT_FOUND"
      }
    }
  ]
}

In my app the mutation ID is being randomly generated.

I tried several blockchainIDs of cards I have listed on the market.

The blockchainID i get from a football query or paginatedcards query. It is always the same and I am sure its correct.

Can you please help me or give me a hint?

I dont know what am I doing wrong.

Thank you very much

**Comment by sfriquet** [comment]
> The blockchainID i get from a football query or paginatedcards query

it sounds like you're using the blockchainID of a Card/Token. To cancel an offer, you must use the blockchainID of that offer.

Hope that helps.
