### ISSUE TITLE
Get current best offer for a player

### ISSUE THREAD

**Issue by jjf21** [sorare/api#55]
Hi, im trying to get the best offer for a Scarcity.

Anyone could help ?

Thanks

**Comment by sirmelo** [comment]
As-tu trouver? je suis entrain de faire la même recherche.

**Comment by jjf21** [comment]
Someone mention doing this: https://github.com/sorare/api/issues/53#issuecomment-982006086
If you find out, let me know

**Comment by sirmelo** [comment]
J'ai vu ce commentaire. Ca fonctionne, mais il y a un gros travail de tri (filtre de la rareté,...) Et le plus gros problème est le volume important pour les "limited"...

**Comment by jjf21** [comment]
Il n'y a pas moyen de filtrer uniquement les cartes rare pour limiter le nombre de résultats?

**Comment by sirmelo** [comment]
Non je n'ai pas encore trouvé. Sauf a créer un tableau en backend, le
filtrer et le renvoyer. Le problème est que si la dernière carte vendu
remonte a longtemps, elle ne reflétera pas la valeur actuelle du joueur.

**Comment by r3v0lt76** [comment]
Salut à vous

Même recherche de mon coté, 
Chercher la meilleure offre et le dernier achat sur un joueur en fonction de la rareté,
Sans devoir se taper toutes les cartes et filtrer derrière

Vous avez toujours pas d'info j'imagine ?

**Comment by redox** [comment]
> Chercher la meilleure offre et le dernier achat sur un joueur en fonction de la rareté,

More filters are coming and we'll start with some filters on `cards` and `allCards`, you can follow #64 .

**Comment by r3v0lt76** [comment]
Thanks will follow

**Comment by redox** [comment]
I assume you could play with something like this (exemple with `paxten-aaronson` `rare`):

```
query {
  player(slug: "paxten-aaronson") {
    cards(owned: true, rarities: [rare]) {
      nodes {
        slug
        user {
          slug
        }
        onSale
        liveSingleSaleOffer {
          price
          priceInFiat {
            eur
          }
        }
      }
    }
  }
}
```

And filter all the one `onSale`.

**Comment by sirmelo** [comment]
Thanks, that's a good way to do it, but not all the cards are for sale. Do
you know why?

Le lun. 31 janv. 2022 à 23:04, Sylvain Utard ***@***.***> a
écrit :
