### ISSUE TITLE
SearchBar for a specific football player with the name

### ISSUE THREAD

**Issue by MickaelLP** [sorare/api#557]
Hi, 
I'm looking to create a SearchBar to get Players with the name like the official website. 
I looked in all issues and I found that we must to use allPlayers to get all of players's slug and search the player with slug in a second time but... isn't there another simple way to do that with the API ?

**Comment by redox** [comment]
Unfortunately there is no real way to search for players within the API, I recommend you store all players on your end and build a search feature within your own DB/Search engine.
