### ISSUE TITLE
BUG - Playground  - Invalid or incomplete schema

### ISSUE THREAD

**Issue by jmallot21** [sorare/api#565]
We encounter an error on the playground. **Invalid or incomplete schema**

![image](https://github.com/sorare/api/assets/52312768/ff1307df-3321-47c4-9f85-1687b76f79bc)

Could you look please?

**Comment by jmallot21** [comment]
![image](https://github.com/sorare/api/assets/52312768/a9631430-1fc8-4ee0-9f79-0768d8dc90b0)

**Comment by karimess19** [comment]
encountering the same error too

**Comment by utay** [comment]
Thanks for reporting this, it is now fixed!
