### ISSUE TITLE
Blocked error 403

### ISSUE THREAD

**Issue by Luca5om3** [sorare/api#569]
Hi, I've been blocked some days ago.
I asked for info opening a ticket then they say was a temporary block.
I asked how to prevent and they say to ask here.
Now I'm blocked again can you help me?

The first time I made many times more then 600 calls/minute.
So I thought that was the problem.
The second time i don't think so.
So idk what's the problem.
Please, tell me just where to paste additional info. Thanks.

**Comment by utay** [comment]
Hi @Luca5om3, I confirm that you must have been rate-limited by our system (see https://github.com/sorare/api?tab=readme-ov-file#rate-limit); your IP can be temporarily blocked in this case. Please re-open if it happens again and you believe you didn't exceed the 600 calls/minute.
