### ISSUE TITLE
Filtering connections using a search query

### ISSUE THREAD

**Issue by nemoeric** [sorare/api#6]
Will you support  syntax on the the arguments ? 
So we could query like this : 
```
query{
  player(slug:!Slug){
    cards(first: 10, query: "onSale:true") {
       onSale
       slug
    }
  }
}
```
Something like Shopify does in its GraphQL api 
https://shopify.dev/concepts/about-apis/search-syntax

That would rock !

**Comment by MarkOSullivan94** [comment]
I would love this! Being able to filter would be a massive help.

**Comment by jeremoquai** [comment]
any news on the filtering topic ? eg. how to get cards over/under a given price ?

**Comment by redox** [comment]
Without going that far with the `query` attribute, we'll still work on adding some extra filters on the `cards` query. Merging this with https://github.com/sorare/api/issues/64
