### ISSUE TITLE
transferMarket - Cannot query field "transferMarket" on type "Query"

### ISSUE THREAD

**Issue by Theoph1lus** [sorare/api#600]
There's a sample query in the README for the API page that uses the following query:

`query ListLast10EnglishAuctions {
  transferMarket {
    englishAuctions(last: 10) {
      nodes {
        slug
        currentPrice
        endDate
        bestBid {
          amount
          bidder {
            ... on User {
              nickname
            }
          }
        }
        minNextBid
        cards {
          slug
          name
          rarity
        }
      }
    }
  }
}`

Copy and pasting that query into the GraphQL Playground results in the error listed in the title. Am I missing something or was this potentially changed/deprecated?
Thanks,

**Comment by such** [comment]
I've fixed the documentation!
