### ISSUE TITLE
Special play-off cards invisible  

### ISSUE THREAD

**Issue by jmallot21** [sorare/api#603]
Special play-off cards are invisible in APIs. 
It is not possible to retrieve them. 

My call : 
`query getSpecialCardPlayOff {
  currentUser {
    nbaCards(rarities: limited) {
      nodes {
        slug
      }
    }
  }
}`

Response : 
![image](https://github.com/sorare/api/assets/52312768/3fb25302-ded9-438b-90d4-71ec3f940052)

But on Sorare Website : 
![image](https://github.com/sorare/api/assets/52312768/76bfecb6-88cf-4045-8c3b-891e5e98d8db)

Lively & Gobert are missing.

Could you please correct this? 
Thanks in advance.

**Comment by jmallot21** [comment]
@redox It's a **real problem**. 
Could you please take a look at what's going on with these cards?

**Comment by jmallot21** [comment]
I don't understand why reward of Rudy Gobert is not present in currentUser.nbaCards().

More information about this card.
![image](https://github.com/user-attachments/assets/19e1e42c-46e3-4c14-bab2-93751f7f6cf8)
![image](https://github.com/user-attachments/assets/1949f4c4-6636-4603-86fa-c745bc711c54)

Can you correct this please ? 
Thanks

**Comment by piedup** [comment]
You should use currentUser.cards and you can pass nba as a sport argument. nbaCards should be deprecated (will do now).

**Comment by jmallot21** [comment]
Perfect ! Thx

**Comment by jmallot21** [comment]
Work on **Playground**, but not with the API :/ 

`Cannot query field "cards" on type "CurrentUser". Did you mean "nbaCards"?`

Issue open : https://github.com/sorare/api/issues/611
