### ISSUE TITLE
Deprecated GraphQL API field TokenOffer.marketFeeAmountWei

### ISSUE THREAD

**Issue by KittyTools** [sorare/api#607]
Hello,

I received some mails alerting me that im using a deprecated field :

TokenOffer.marketFeeAmountWei

My problem is that if I use the marketFeeAmounts instead like its written in the doc the relative data is not returned :

**Query :**
`query queryGetAllNewLSSFromUserSlug($slug: String!, $first: Int) {
  user(slug: $slug) {
    singleSaleTokenOffers(sortByEndDate: DESC, first: $first) {
      nodes {
        marketFeeAmountWei
        marketFeeAmounts {
          eur
          gbp
          usd
          wei
          referenceCurrency
        }`

**Result :**
`{
            "marketFeeAmountWei": "300000000000000",
            "marketFeeAmounts": null,`

Where could I find the marketFeeAmountWei of 300000000000000 without using a deprecated field?

Thanks

**Comment by redox** [comment]
We'll fix this shortly, it's indeed not supposed to return null.
