### ISSUE TITLE
Invalid offer type SingleSaleOffer

### ISSUE THREAD

**Issue by wti3pvs** [sorare/api#61]
I am running the prepareOffer mutation with the following parameters:
'variables' => [ 'input' => [ 'receiveCardsSlugs'=>''
, 'receiveWeiAmount' => '1428571428571428'
,'sendCardsSlugs'=>['gustav-henriksson-2021-limited-153']
, 'sendWeiAmount' => '0'
,'type' =>'SINGLE_SALE_OFFER']]

However I get an "Invalid offer type SingleSaleOffer". Why does this happen?

Later I would like to run the CreateSingleSaleOffer mutation. What information must be put in the data variable of starkSignatures?

Thanks in advance.

**Comment by redox** [comment]
hey @wti3pvs ,

this is surprising because I think my code pretty much looks the same (https://github.com/sorare/api/blob/master/examples/createSingleSaleOffer.js#L112-L120) and works.

I've documented all of this in https://github.com/sorare/api#creating-offers , I hope this helps!

**Comment by MichaelBornand** [comment]
Hey @redox 

Reopening the issue as I happen to have the same problem.
I'm using ruby and have something like 

`prepareOfferInput = {
  type: "SINGLE_BUY_OFFER",
  sendCardsSlugs: [],
  receiveCardsSlugs: [cardSlug],
  sendWeiAmount: "0.0005",
  receiveWeiAmount: "0",
  receiverSlug: nil,
  clientMutationId: Sysrandom.base64(8)
}`

return value is 

`{"prepareOffer"=>{"limitOrders"=>nil, "errors"=>[{"message"=>"invalid offer type"}]}}`

When I try to modify the "type" key value, the server is responding with an error like 

`Variable $input of type prepareOfferInput! was provided invalid value for type (Expected \"SINGLE_BUY_OdezfezfeFFER\" to be one of: SINGLE_SALE_OFFER, SINGLE_BUY_OFFER, DIRECT_OFFER`

So I'm assuming that i'm sending the correct value for the type key, but still the server responding with an "invalid offer type" error. 

What I am missing ?

**Comment by redox** [comment]
Need to check with @piedup and @eulbat what’s going on.

**Comment by BobyCow** [comment]
Hey @redox , did you check with @piedup and @eulbat what's going on ? Because the issue is still running
