### ISSUE TITLE
Origin of essence

### ISSUE THREAD

**Issue by BMorvillez** [sorare/api#627]
I'd need to get essence details 
Something like this, declined by sport and scarcity :
`{
  user(slug: "") {
    essence{
      football{
        limited{
          total
          champion
          challenger
	  contender
          neutral
        }
      }
    }
  }
 }`

**Comment by Hugo-Hache** [comment]
`poolKeyShardsCounts` was recently introduced on `CardShardsChest`. You'll be able to retrieve origin of essence thanks to it. 

```
{
  currentUser {
    cardShardsChest(id: "CardShardsChest:...") {
      poolKeyShardsCounts {
        slug
        displayName
        count
      }
    }
  }
}
```

In case you're not used to it, a glossary of the product terms in the API:
* essence: shard
* essence "tank": cardShardsChest 
* origin: poolKey
