### ISSUE TITLE
Important information missing - Playing time 

### ISSUE THREAD

**Issue by jmallot21** [sorare/api#629]
:warning:  **Playing time is no longer accessible** in the APIs in terms of the stats a player has achieved during a match. 

The secondsPlayed field was available during the previous season. 

This data is **very important and weights a lot of other information**. 

Could you please integrate it again? 

Thanks in advance.

**Comment by piedup** [comment]
You cna use `minsPlayed`

**Comment by jmallot21** [comment]
Thx for fast response . 
But I have a problem. 
I can't call this filed.
Can you help me ?
![image](https://github.com/user-attachments/assets/929e164d-a054-4711-b987-ec62c4767e6d)

`
query getGameInfo($gameId: ID!) {
    anyGame(id: $gameId){
        players: anyPlayers{
          slug
          playerGameScores(last:5){
            game: anyGame{ date so5Fixture {slug} awayTeam{id slug} homeTeam{id slug} }
            playerGameStats: anyPlayerGameStats { 
              team: anyTeam { slug }
              onGameSheet reviewed live minsPlayed
            }
            score scoreStatus
            detailedScore {
              category points stat statValue totalScore
            }
          }
        }
      }
    }
`

{ "gameId": "Game:e9337b16-fd11-493b-8ffc-1f71bd47a055" }

**Comment by jmallot21** [comment]
Ok. 
My bad ! 
![image](https://github.com/user-attachments/assets/ee45ea77-b99a-4627-b15a-a70622fa37fd)
 
Thanks you so much !
