### ISSUE TITLE
Tokens.PrimaryOffers return the same price for all settled offers for a player

### ISSUE THREAD

**Issue by llehouerou** [sorare/api#634]
Let's take this request which returns the last primary offers settled for alex mc carthy :

```
{
 tokens {
  primaryOffers(ids:[
  "7d115b9d-718b-466f-b2a6-071ef5c99efe",
"b40ce002-e85f-4a6c-86c0-898b41a392d6",
"896f691d-fec1-4698-b049-ead7b4827438",
"7a2264ab-71a8-4b21-bab2-8621f5957751",
"1013d933-b9ed-4d03-9735-5e901047b6d8",
"dbea70db-519b-49f8-a695-3d5837940e59",
"692cf815-cb3f-453a-81c5-d9de8cd5b5f7",
"3c36b75a-2d29-4934-b4aa-164aec2b0afc"
  ]){
    anyCards{
      name
    }
    updatedAt
    price{
      eur
      referenceCurrency
    }
    
  }
    
}
}
```

it returns, at the time i am writing this, the same price for each offers (3,99€) which is not the real settled price for any of this offer if we believe what was sent at the time of settlement via the websocket stream.
I tested it on a couple of other players and it seems that it is a global problem for all players

**Comment by such** [comment]
Hello,

Thank you for this report.
This is fixed now!
