### ISSUE TITLE
Problem with AcceptOffer in EUR, (WEI, works)

### ISSUE THREAD

**Issue by Hanusek17** [sorare/api#635]
Hi, I have a script in which I can accept an offer by providing the ID and currency. For WEI everything works but when the offer is in FIAT then when accepting I get "Error in acceptOffer: BlockchainApi::Error 500 500 Internal Server Error"

My commands:
mutation PrepareAcceptOffer($input: prepareAcceptOfferInput!) {
    prepareAcceptOffer(input: $input) {
      authorizations {
        ...AuthorizationRequestFragment
      }
      errors {
        message
      }
    }
  }

{
  "input": {
    "offerId": "SingleSaleOffer:b....19",
    "settlementInfo": {
      "currency": "EUR",
      "paymentMethod": "WALLET",
      "exchangeRateId": "ExchangeRate:11a7cbdc-2bc4-4998-97d4-60201faf03e6"
    }
  }
}

mutation AcceptSingleSaleOffer($input: acceptOfferInput!) {
    acceptOffer(input: $input) {
      tokenOffer {
        id
      }
      errors {
        message
      }
    }
  }

{
  "input": {
    "offerId": "b......19",
    "approvals": [
      {
        "fingerprint": "f0.....564",
        "mangopayWalletTransferApproval": {
          "nonce": ....,
          "signature": {
            "r": "652e7......621bd6d7b7d56",
            "s": "5d2bb.....2b6107d57ecd"
          }
        }
      }
    ],
    "settlementInfo": {
      "currency": "EUR",
      "paymentMethod": "WALLET",
      "exchangeRateId": "ExchangeRate:14ae668a-79c7-48cb-97ff-5c2cee939448"
    },
    "clientMutationId": "5f.......c2d2"
  }
}
fragment AuthorizationRequestFragment on AuthorizationRequest {
    id
    fingerprint
    request {
      __typename
      ... on StarkexLimitOrderAuthorizationRequest {
        amountBuy
        amountSell
        expirationTimestamp
        feeInfo {
          feeLimit
          sourceVaultId
          tokenId
        }
        nonce
        tokenBuy
        tokenSell
        vaultIdBuy
        vaultIdSell
      }
      ... on StarkexTransferAuthorizationRequest {
        starkexTransferAmount: amount
        condition
        expirationTimestamp
        feeInfoUser {
          feeLimit
          sourceVaultId
          tokenId
        }
        nonce
        receiverPublicKey
        receiverVaultId
        senderVaultId
        token
      }
      ... on MangopayWalletTransferAuthorizationRequest {
        nonce
        amount
        currency
        operationHash
        mangopayWalletId
      }
    }
  }

Does anyone know where I went wrong?

**Comment by such** [comment]
Hello,
We'll make sure to send a better error on our side but I think the issue is that you should send:

"0x652e7......621bd6d7b7d56" and "0x5d2bb.....2b6107d57ecd" for the signature rather than without the "0x" prefix

**Comment by Hanusek17** [comment]
I thought about that too, but unfortunately that's not it. For WEI everything worked fine, but for EUR I have the same error as without the "0x" prefix

My main code

// Api/accept_offer/AcceptSingleSaleOffer.js

import { GraphQLClient, gql } from 'graphql-request';
import crypto from 'crypto';
import yargs from 'yargs/yargs';
import { hideBin } from 'yargs/helpers';

// Import default export from authorization.mjs
import authorization from '../authorizations/authorization.mjs';

const { authorizationRequestFragment, buildApprovals } = authorization;

// Config Import 
import CONFIG from './config.js';

// Defs
const ConfigQuery = gql`
  query ConfigQuery {
    config {
      exchangeRate {
        id
      }
    }
  }
`;

const PrepareAcceptOfferMutation = gql`
  mutation PrepareAcceptOffer($input: prepareAcceptOfferInput!) {
    prepareAcceptOffer(input: $input) {
      authorizations {
        ...AuthorizationRequestFragment
      }
      errors {
        message
      }
    }
  }
  
  ${authorizationRequestFragment}
`;

const AcceptSingleSaleOfferMutation = gql`
  mutation AcceptSingleSaleOffer($input: acceptOfferInput!) {
    acceptOffer(input: $input) {
      tokenOffer {
        id
      }
      errors {
        message
      }
    }
  }
`;

/**
 * Main func
 */
async function main() {
  // Parsowanie args
  const argv = yargs(hideBin(process.argv))
    .command('acceptSingleSaleOffer', 'Accept a single sale offer.')
    .option('offer-id', {
      description: 'The Offer ID of the offer to accept.',
      type: 'string',
      demandOption: true,
    })
    .option('currency', {
      description: 'Currency for settlement (WEI or EUR).',
      type: 'string',
      choices: ['WEI', 'EUR', 'GBP', 'USD'],
      demandOption: true,
    })
    .help()
    .alias('help', 'h').argv;

  // Args
  const { offerId, currency } = argv;
  console.log(`offer-id: ${offerId}`);
  console.log(`currency: ${currency}`);

  // Init
  console.log('Inicjalizacja GraphQLClient...');
  const graphQLClient = new GraphQLClient(
    'https://api.sorare.com/federation/graphql',
    {
      headers: {
        Authorization: `Bearer ${CONFIG.jwt}`,
        'JWT-AUD': CONFIG.aud,
        'Content-Type': 'application/json',
        Accept: 'application/json',
      },
    }
  );

  try {
    //  1: exchangeRateId
    console.log('exchangeRateId...');
    const configData = await graphQLClient.request(ConfigQuery);
    const exchangeRateId = configData.config.exchangeRate.id;
    console.log(`exchangeRateId: ${exchangeRateId}`);

    //  2: Prepare accept offer
    console.log('Prepare accept offer...');
    const prefixedOfferId = `SingleSaleOffer:${offerId}`;
    console.log(`Prefix offerId: ${prefixedOfferId}`);
    const prepareAcceptOfferInput = {
      offerId: prefixedOfferId,
      settlementInfo: {
        currency: currency, // 'WEI' lub 'EUR'
        paymentMethod: 'WALLET',
        exchangeRateId: exchangeRateId, // 'ExchangeRate:{UUID}'
      },
    };
    console.log('prepareAcceptOfferInput:', prepareAcceptOfferInput);

    console.log('Sending PrepareAcceptOffer mutation with variables:', JSON.stringify({
      input: prepareAcceptOfferInput,
    }, null, 2));

    const prepareAcceptOfferData = await graphQLClient.request(
      PrepareAcceptOfferMutation,
      {
        input: prepareAcceptOfferInput,
      }
    );

    const prepareAcceptOffer = prepareAcceptOfferData.prepareAcceptOffer;

    if (prepareAcceptOffer.errors && prepareAcceptOffer.errors.length > 0) {
      prepareAcceptOffer.errors.forEach((error) => {
        console.error('Error in prepareAcceptOffer:', error.message);
      });
      process.exit(2);
    }

    const authorizations = prepareAcceptOffer.authorizations;
    console.log(`authorizations: ${authorizations.length}`);

    // 3: authorizations
    console.log('authorizations...');
    const approvals = await buildApprovals(CONFIG.starkPrivateKey, CONFIG.ethPrivateKey, authorizations);
    console.log(`approvals: ${approvals.length}`);
    console.log('Approvals:', approvals);

    // Krok 4: Przygotuj acceptOfferInput
    console.log('Prepary acceptOfferInput...');
    const clientMutationId = crypto.randomBytes(8).toString('hex');
    console.log(`clientMutationId: ${clientMutationId}`);

    const acceptOfferInput = {
      offerId: prefixedOfferId,
      approvals: approvals.map((approval, index) => {
        console.log(`approval ${index + 1}`);
        return {
          fingerprint: approval.fingerprint,
          ...(approval.starkexLimitOrderApproval && {
            starkexLimitOrderApproval: {
              nonce: approval.starkexLimitOrderApproval.nonce,
              expirationTimestamp: approval.starkexLimitOrderApproval.expirationTimestamp,
              signature: approval.starkexLimitOrderApproval.signature, 
            },
          }),
          ...(approval.starkexTransferApproval && {
            starkexTransferApproval: {
              nonce: approval.starkexTransferApproval.nonce,
              expirationTimestamp: approval.starkexTransferApproval.expirationTimestamp,
              signature: approval.starkexTransferApproval.signature,
            },
          }),
          ...(approval.mangopayWalletTransferApproval && {
            mangopayWalletTransferApproval: {
              nonce: approval.mangopayWalletTransferApproval.nonce, // Number
              mangopayAmount: approval.mangopayWalletTransferApproval.mangopayAmount, // Number
              currency: approval.mangopayWalletTransferApproval.currency,
              operationHash: approval.mangopayWalletTransferApproval.operationHash,
              signature: approval.mangopayWalletTransferApproval.signature, 
            },
          }),
        };
      }),
      settlementInfo: {
        currency: currency, // 'WEI' lub 'EUR'
        paymentMethod: 'WALLET',
        exchangeRateId: exchangeRateId, // 'ExchangeRate:{UUID}'
      },
      clientMutationId,
    };
    console.log('acceptOfferInput:', JSON.stringify(acceptOfferInput, null, 2));

    // Krok 5: Send mutation acceptOffer
    console.log('Wysyłanie mutacji acceptOffer...');
    const acceptOfferData = await graphQLClient.request(
      AcceptSingleSaleOfferMutation,
      {
        input: acceptOfferInput,
      }
    );

    const acceptOffer = acceptOfferData.acceptOffer;

    if (acceptOffer.errors && acceptOffer.errors.length > 0) {
      acceptOffer.errors.forEach((error) => {
        console.error('Error  acceptOffer:', error.message);
      });
      process.exit(3);
    }

    const tokenOffer = acceptOffer.tokenOffer;
    console.log('Sukces!:', tokenOffer);
  } 
  catch (error) {
    console.error('Error:', error.message);
    if (error.response && error.response.errors) {
      error.response.errors.forEach((err) => {
        console.error('GraphQL Error:', err.message);
      });
    }
    if (error.response && error.response.body) {
      console.error('Response Body:', JSON.stringify(error.response.body, null, 2));
    }
    process.exit(1);
  }
}

main().catch((error) => {
  console.error(' Error:', error);
  process.exit(1);
});

**Comment by such** [comment]
Are you sure you're having the same error?

The only error I'm seeing is "Cannot convert 652e76e4019a9307726795d16b4b14c888d80a2a2fc9d1f1a61621bd6d7b7d56 to a BigInt"

This has stopped now that we've introduced input validation higher up the chain.

**Comment by Hanusek17** [comment]
Yeah, below is my full sricpt output 

```
Received offer-id: b657a930-9......69027e05d019
Set currency: EUR
Initializing GraphQLClient...
Fetching exchangeRateId...
Using exchangeRateId: ExchangeRate:d9add479-1e20-472e-91bb-5b830302c2c9
Preparing to accept the offer...
Prefixed offerId: SingleSaleOffer:b657a9......1-69027e05d019
prepareAcceptOfferInput: {
  offerId: 'SingleSaleOffer:b657a930......69027e05d019',
  settlementInfo: {
    currency: 'EUR',
    paymentMethod: 'WALLET',
    exchangeRateId: 'ExchangeRate:d9add479-1e20-472e-91bb-5b830302c2c9'
  }
}
Sending PrepareAcceptOffer mutation with variables: {
  "input": {
    "offerId": "SingleSaleOffer:b657a......9027e05d019",
    "settlementInfo": {
      "currency": "EUR",
      "paymentMethod": "WALLET",
      "exchangeRateId": "ExchangeRate:d9add479-1e20-472e-91bb-5b830302c2c9"
    }
  }
}
Received authorizations: 1
Signing authorizations...
Building approvals...
Building approval for authorization 1
Building approval for fingerprint: f0aa3......803bd564
Authorization type: MangopayWalletTransferAuthorizationRequest
Original Authorization Request: {
  __typename: 'MangopayWalletTransferAuthorizationRequest',
  nonce: 497,
  amount: 95,
  currency: 'EUR',
  operationHash: '7ce568ce7f......5e0d207dff5d',
  mangopayWalletId: 'wlt_m_01......V4ZB6HQM6A0'
}
Operation Hash to sign: 7ce568ce7f58......8939e5e0d207dff5d
SigningKey instance: SigningKey {
  curve: 'secp256k1',
  privateKey: '0x6843a37.............23d',
  publicKey: '0x04baddba009ede6d07............1d5ec5c22',
  compressedPublicKey: '0x02badd......2f09c',
  _isSigningKey: true
}
Signature object: {
  r: '0x652e......1bd6d7b7d56',
  s: '0x5d2bb......3662b6107d57ecd',
  _vs: '0xdd2bb7a......07d57ecd',
  recoveryParam: 1,
  v: 28,
  yParityAndS: '0xdd2bb7......62b6107d57ecd',
  compact: '0x652e76e4............d57ecd'
}
Signature split into r and s: {
  r: '0x652e76......621bd6d7b7d56',
  s: '0x5d2bb7......2b6107d57ecd'
}
Signature returned from SigningKey: {
  r: '0x652e76e4......21bd6d7b7d56',
  s: '0x5d2bb7a3......3662b6107d57ecd'
}
Generated approvals: 1
Approvals: [
  {
    fingerprint: 'f0aa3......564',
    mangopayWalletTransferApproval: { nonce: 497, signature: [Object] }
  }
]
Preparing acceptOfferInput...
clientMutationId: 4b822bede77f816f
Processing approval 1
acceptOfferInput: {
  "offerId": "SingleSaleOffer:b657......05d019",
  "approvals": [
    {
      "fingerprint": "f0aa3......bd564",
      "mangopayWalletTransferApproval": {
        "nonce": 497,
        "signature": {
          "r": "0x652e76e40......bd6d7b7d56",
          "s": "0x5d2bb7a3b......613662b6107d57ecd"
        }
      }
    }
  ],
  "settlementInfo": {
    "currency": "EUR",
    "paymentMethod": "WALLET",
    "exchangeRateId": "ExchangeRate:d9add479-1e20-472e-91bb-5b830302c2c9"
  },
  "clientMutationId": "4b......16f"
}
Sending acceptOffer mutation...
Error in acceptOffer: BlockchainApi::Error      500     500 Internal Server Error

```

And my autorization.mjs

```
// Api/authorizations/authorization.mjs

import { gql } from 'graphql-request';
import { signLimitOrder } from '@sorare/crypto';
import { arrayify } from '@ethersproject/bytes'; // Importing arrayify
import { SigningKey } from '@ethersproject/signing-key'; // Importing SigningKey from '@ethersproject/signing-key'

/**
 * Fragment AuthorizationRequestFragment for use in GraphQL mutations.
 */
const authorizationRequestFragment = gql`
  fragment AuthorizationRequestFragment on AuthorizationRequest {
    id
    fingerprint
    request {
      __typename
      ... on StarkexLimitOrderAuthorizationRequest {
        amountBuy
        amountSell
        expirationTimestamp
        feeInfo {
          feeLimit
          sourceVaultId
          tokenId
        }
        nonce
        tokenBuy
        tokenSell
        vaultIdBuy
        vaultIdSell
      }
      ... on StarkexTransferAuthorizationRequest {
        starkexTransferAmount: amount
        condition
        expirationTimestamp
        feeInfoUser {
          feeLimit
          sourceVaultId
          tokenId
        }
        nonce
        receiverPublicKey
        receiverVaultId
        senderVaultId
        token
      }
      ... on MangopayWalletTransferAuthorizationRequest {
        nonce
        amount
        currency
        operationHash
        mangopayWalletId
      }
    }
  }
`;

/**
 * Function converting specified properties to BigInt.
 * @param {object} request - AuthorizationRequest object.
 * @returns {object|null} - Converted AuthorizationRequest object or null in case of an error.
 */
const convertValuesToBigInt = (request) => {
  if (!request || typeof request !== 'object') {
    console.error('Invalid request object:', request);
    return null;
  }

  const fieldsToConvert = [
    'amountBuy',
    'amountSell',
    'expirationTimestamp',
    'vaultIdBuy',
    'vaultIdSell',
    'vaultId',
    'feeLimit',
    'sourceVaultId',
    'transferAmount',
    'receiverVaultId',
    'senderVaultId',
    'nonce', // Added to conversion
  ];

  const convertedRequest = { ...request };

  for (const field of fieldsToConvert) {
    if (convertedRequest[field] !== undefined && convertedRequest[field] !== null) {
      const value = convertedRequest[field];
      if (typeof value === 'string' || typeof value === 'number') {
        try {
          convertedRequest[field] = BigInt(value);
        } catch (e) {
          console.error(`Failed to convert field ${field} with value ${value} to BigInt:`, e);
          return null;
        }
      }
    }
  }

  return convertedRequest;
};

/**
 * Function for building approval based on AuthorizationRequest type.
 * @param {string} starkPrivateKey - Your StarkEx private key.
 * @param {string} ethPrivateKey - Your Ethereum private key.
 * @param {object} authorization - AuthorizationRequest object.
 * @returns {object} - Approval object with a signature.
 */
// authorization.mjs

// ... existing imports and code ...

const buildApproval = async (starkPrivateKey, ethPrivateKey, authorization) => {
  const { fingerprint, request } = authorization;

  console.log(`Building approval for fingerprint: ${fingerprint}`);
  console.log(`Authorization type: ${request.__typename}`);
  console.log('Original Authorization Request:', request);

  if (request.__typename === 'MangopayWalletTransferAuthorizationRequest') {
    const operationHash = request.operationHash;
    if (!operationHash) {
      console.error('operationHash is required for MangopayWalletTransferAuthorizationRequest');
      throw new Error('operationHash is required for MangopayWalletTransferAuthorizationRequest');
    }

    // Sign the operationHash using Ethereum private key
    let signature;
    try {
      const signingKey = new SigningKey(ethPrivateKey);
      const digest = arrayify(operationHash.startsWith('0x') ? operationHash : `0x${operationHash}`);
      const signatureObj = signingKey.signDigest(digest);

      // Ensure 'r' and 's' have '0x' prefix
      signature = {
        r: signatureObj.r.startsWith('0x') ? signatureObj.r : `0x${signatureObj.r}`,
        s: signatureObj.s.startsWith('0x') ? signatureObj.s : `0x${signatureObj.s}`,
      };
    } catch (e) {
      console.error('Error while signing operationHash:', e);
      throw new Error('Failed to sign operationHash.');
    }

    // Return the approval with all required fields
    return {
      fingerprint: fingerprint,
      mangopayWalletTransferApproval: {
        nonce: request.nonce.toString(),
        mangopayAmount: request.amount.toString(),
        currency: request.currency,
        operationHash: request.operationHash.startsWith('0x') ? request.operationHash : `0x${request.operationHash}`,
        signature: signature,
      },
    };
  }

  // ... handle other authorization types ...

  throw new Error(`Unknown or unsupported AuthorizationRequest type: ${request.__typename}`);
};

// ... existing exports ...

/**
 * Function for building all approvals.
 * @param {string} starkPrivateKey - Your StarkEx private key.
 * @param {string} ethPrivateKey - Your Ethereum private key.
 * @param {array} authorizations - Array of AuthorizationRequest objects.
 * @returns {array} - Array of approval objects.
 */
const buildApprovals = async (starkPrivateKey, ethPrivateKey, authorizations) => {
  console.log('Building approvals...');
  const approvals = [];
  for (let index = 0; index < authorizations.length; index++) {
    const authorization = authorizations[index];
    console.log(`Building approval for authorization ${index + 1}`);
    const approval = await buildApproval(starkPrivateKey, ethPrivateKey, authorization);
    approvals.push(approval);
  }
  return approvals;
};

export default { authorizationRequestFragment, buildApprovals };

```

**Comment by such** [comment]
It looks like your signature is invalid. Here is the actual error: "Error: r must be 0 < r < CURVE.n"

**Comment by such** [comment]
Hello,

We're expecting a starkware signature here. You can use
https://github.com/sorare/crypto/blob/master/src/index.ts and your
starkware private key

**Comment by Hanusek17** [comment]
That helped, thanks
