### ISSUE TITLE
Was the field rotowireProjectedScore removed from the API?

### ISSUE THREAD

**Issue by id021960** [sorare/api#637]
Previously, I was able to retrieve the rotowireProjectedScore field in an API call. However, I can no longer find this field in the API documentation, nor can I access it as I did before.

Example query:

```graphql
basketballPlayer {
displayName
averageScore(type: LAST_TEN_PLAYED_SO5_AVERAGE_SCORE)
rotowireProjectedScore
}
```

**Comment by elkesrio** [comment]
Hello, 

Yes this field has been removed in favor of the new field `projectedScore` that's in the `PlayerGameScoreInterface`. This field has only sense in the context of a game score

**Comment by id021960** [comment]
thanks
