### ISSUE TITLE
Add a rarity filter to allCards

### ISSUE THREAD

**Issue by juliusdanek** [sorare/api#64]
It would be great if you could add filters to the allCards query. The most important filter would be a **rarity** filter. Right now, it shows all cards including common cards. I would like to be able to only see unique cards for example or be able to exclude 'common' cards.

Other filters that would be really helpful:

1. Season
2. Player
3. Club

Additionally, on the player object it would be great to allow those filters as well. That way it becomes much more efficient to query cards.

**Comment by redox** [comment]
> Hey guys, as said by @juliusdanek a filter available on the **rarity** data would be very helpful. The common cards are causing lots of noise.

It's coming.

> Also a filter on **blockchainId** would be great as well.

What's your use-case for this @PAMuser ?

**Comment by juliusdanek** [comment]
@PAMuser why don't use you use the cardByBlockchainId? That allows you to retrieve cards by blockchainid.

**Comment by PAMuser** [comment]
I was actually thinking of being able to target and filter cards with "blockchainId not null",  it would be another way to exclude common cards (which don't have blockchainId from my understanding) without having to precise the rarity. 

Yes it is a useful query thanks for the tips. 

I also have another question (would be better in another issue maybe), can you confirm that a card which is part of a pack (bundleAuction) has a variable "inRollup" = true ?

**Comment by redox** [comment]
@PAMuser @juliusdanek @arik555 @big-javascript-fan @nemoeric @jeremoquai @Maaaarko hey everyone, you have all ben requesting the need for additional filters on the `cards` & `allCards` queries+connections. We just deployed a new version of the API as documented in #91 . We would love to hear your feedback!

**Comment by juliusdanek** [comment]
❤️ hell yes, this is awesome. Thanks! Definitely much needed. Now, let's get to those filter on aCardWasUpdated subscription 😃

**Comment by redox** [comment]
> Now, let's get to those filter on the aCardWasUpdated subscription 😃

We're working on it 😎

**Comment by PAMuser** [comment]
Thanks a lot guys ! It's gonna be so useful ! 

Also I have a little question, is there a variable or something that helps to determine if an auction is part of a bundle auction ? 
I'm using a little script that gets all the EnglishAuction but it also includes the bundle auctions. I just saw there is a boolean flag "bundled". Is it a new one and is it true trustworthy ?

**Comment by redox** [comment]
> is there a variable or something that helps to determine if an auction is part of a bundle auction

Since a few months now, all auctions are BundledAuctions on our end. Even if the bundle has size of 1. We're still in the middle of this (technical) migration and we plan to entirely unify all those auction types in the near future. @PAMuser does it make sense?
