### ISSUE TITLE
Add the "deal" object to userOwnersWithRates

### ISSUE THREAD

**Issue by juliusdanek** [sorare/api#67]
Would it be possible to add the **deal** object to userOwnersWithRates? That would make it a lot easier to match the transaction data to the actual deals behind it.

**Comment by such** [comment]
Hello,

The deal field has been deprecated now. What is the data you're after?

**Comment by juliusdanek** [comment]
Hey Adrien,

with the deal field being deprecated, what are you going to use as the unique identifier for the offer? So far it had two, correct? The offerId and the dealId. 

I was trying to see the details of direct offers in userOwnersWithRates. Which cards were being sent and which ones were being received over all. Currently it shows no details at all.

**Comment by redox** [comment]
@juliusdanek while the `deal` object is deprecated, we've added the `dealId` field to `UserOwnerWithRates` objects.
