### ISSUE TITLE
Connecting to Excel

### ISSUE THREAD

**Issue by DmitriySh12** [sorare/api#69]
Good afternoon!
Are there options for connecting the So rare API to Excel? Maybe through Power Query or VBA?

**Comment by redox** [comment]
Hi @DmitriySh12 ,

unfortunately this is not something we'll work on within the Sorare team anytime soon. Maybe someone from the community will build it.

Have fun playing Sorare!

**Comment by DmitriySh12** [comment]
I see!
But the question is more to the community: maybe someone has already implemented other graphml queries, or is it Solare!?
