### ISSUE TITLE
Getting a decisive score and an all-around score separately

### ISSUE THREAD

**Issue by skomuro** [sorare/api#70]
Hi,

Is it possible to get a decisive score and an all-around score separately? I think that way makes more sense when it comes to the score analysis.

**Comment by Mertecagner** [comment]
Hi, leaving a comment as i am also interested in thius issue. Would like to have a database with all the decisive an All around scores

**Comment by redox** [comment]
The split is indeed not available within the API directly and a bunch is computed within our frontend code. I'll check how to continue improving this. I cannot provide any ETA however.

**Comment by redox** [comment]
Hey @skomuro  & @Mertecagner ,

The `So5Score` type has been updated and now includes a `decisiveScore` and `allAroundStats` fields as well as `positiveDecisiveStats` and `negativeDecisiveStats` field.
