### ISSUE TITLE
Example of pagination with Cursor to get more than 50 lines in Allcards query

### ISSUE THREAD

**Issue by PAMuser** [sorare/api#71]
Hello guys, 

Working on python I'm trying to get a loop on all English Auctions with details on it. I understand there is a way to get this by using pagination with the cursor of the page but could someone provide an exemple on how to do it please ? 

I only get 50 records on my result now.

Here is an example of my query:
query_listeEncheres = 
'''
query  {
  transferMarket {
    englishAuctions {
      nodes {
        name
        slug
        endDate
        currentPrice
        minNextBid
        deal {
          dealId
        }
        cards {
            age
            position
            rarity
            u23Eligible
            power
            blockchain
            blockchainId
            canBuy
            inRollup
            owner{
                account{id}}
          
        }
      }
    }
  }
}
'''

**Comment by redox** [comment]
Hey @PAMuser , I've just added a `Pagination` section in the README; I hope this helps!

**Comment by PAMuser** [comment]
Hey @redox ,

Thanks a lot for your contribution and reactivity,  it helps me a lot !!
