### ISSUE TITLE
Sales history

### ISSUE THREAD

**Issue by SpicySand** [sorare/api#73]
Is there any method to get what rarity cards have sold for before. Like to see what Rare Mbappe cards have sold for before?

**Comment by redox** [comment]
> Is there any method to get what rarity cards have sold for before. Like to see what Rare Mbappe cards have sold for before?

Not really, but your can see the latest prices of a specific Mbappe card. See https://github.com/sorare/api/issues/8

**Comment by SpicySand** [comment]
Thank you.
