### ISSUE TITLE
Retrieve average price

### ISSUE THREAD

**Issue by BMorvillez** [sorare/api#75]
Since cards.price is deprecated, how can we retrieve a player average price as SorareData does ?
Would be nice to fetch an average price for the last 5 cards sold (auction or offer).

**Comment by redox** [comment]
> Since cards.price is deprecated, how can we retrieve a player average price as SorareData does ?
> Would be nice to fetch an average price for the last 5 cards sold (auction or offer).

That's correct, but it's also not that relevant to get a single price for a card. You can use `priceRange` instead; it's not an average but can help. Also, you can get all past prices of a card with:

```gql
{
  card(slug: "cardslug") {
    userOwnersWithRate {
      price
      from
    }
  }
}
```

I hope this helps!

**Comment by BMorvillez** [comment]
Thanks @redox ! 

`priceRange` doesn't seem accurate enough: I've spotted 1 to 10 ratio between min & max

I'm gonna try with `userOwnersWithRate` but it implies to know the serial from the last cards sold

To be transparent, I'm using price average and so5 performance to calculate a cost/performance (a KPI that doesn't exist on SorareData)

**Comment by redox** [comment]
> `priceRange` doesn't seem accurate enough: I've spotted 1 to 10 ratio between min & max
> 
> I'm gonna try with `userOwnersWithRate` but it implies to know the serial from the last cards sold

Well, the other way would be for you (because our API won't go there) to build a database of all bids, listening to the `aCardWasUpdated` subscription and accumulating all sales done on cards.

**Comment by BMorvillez** [comment]
Thanks again!
I'm guessing this is what SorareData is doing ?
I'm lacking some documentations to listen/handle subscriptions though... :/

**Comment by lechner-philipp** [comment]
@redox Could you provide an example query on how to use priceRange? Thank you.
