### ISSUE TITLE
Retrieve all active "gameauctions" and "playeroffers" - Price question

### ISSUE THREAD

**Issue by AlessandroCordella** [sorare/api#78]
Is there a way to retrieve trough a grapql query:

- all the active auctions (for all the football players or just for only one) for new cards 
- all the player's offers for a football player

I only found a way to retrieve all the player's offer for a specific footbal player card (ex 172/1000) and not for all the offer in general (ex all the offers for limited mbappe).

Furthermore, in a query like the following:
`query {
   transferMarket {
                singleSaleOffers {
                    nodes {
                        id
                        blockchainId
                        price
                        card {
                            slug
                            rarity
                        }
                    }
                    pageInfo {
                        endCursor
                        hasNextPage
                    }
                }
            }
            
}`
what is the unit of the price value? For example for a card with 0,03 ETH value, I get "price": "30000000000000000".

Thank you

**Comment by Policy56** [comment]
The unit is in WEI 

Convert here : https://eth-converter.com/

Or <price>/1000000000000000000 to get price in ETH ! :)

**Comment by redox** [comment]
hey @AlessandroCordella ,

I assume you could navigate the list of owned cards to find all `canBuy: true` as well as the list of english auctions with:

```gql
query {
  player(slug: "paxten-aaronson") {
    cards(owned: true, rarities: [limited, rare, super_rare, unique]) {
      nodes {
        slug
        user {
          slug
        }
        canBuy
        publicSingleBuyOfferMinPrice {
          amount
        }
      }
    }
  }
  transferMarket {
    englishAuctions(playerSlugs: ["paxten-aaronson"]) {
      nodes {
        cards {
          slug
        }
        currentPrice
      }
    }
  }
}
```

Good luck with the implementation!
