### ISSUE TITLE
Unable to login

### ISSUE THREAD

**Issue by mnadalc** [sorare/api#79]
Good morning,

I'm testing some queries/mutations in the GraphQL Playground.
Yesterday I was able to login with my user without a problem, following these steps:

1) Retrieve my hashed password doing `$ curl https://api.sorare.com/api/v1/users/myemail@mydomain.com`
2) Inside the playground, add the `signIn` mutation with the needed variables for the `$input` field
```gql
mutation SignInMutation($input: signInInput!) {
  signIn(input: $input) {
    currentUser {
      slug
      jwtToken(aud: "test-app") {
        token
        expiredAt
      }
    }
    errors {
      code
      message
      path
    }
  }
}
```

I did retrieve the JWT token in order to do some queries, and it worked perfectly.

After that, I enabled 2FA and tried to do the login again in order to get the `otpSessionChallenge` value.
But now, after trying to do the `SigInMutation`, I'm always getting the following response:

```json
{
  "data": {
    "signIn": {
      "currentUser": null,
      "otpSessionChallenge": null,
      "errors": [
        {
          "code": null,
          "message": "invalid",
          "path": null
        }
      ]
    }
  }
}
```

I still can do queries/mutations with the previous JWT token without the need to do the login again. But I'd like to test how to get the `otpSessionChallenge`.

I have created a new user to check if was something wrong with my current one, but I'm getting the same error message.

Am I missing someting?
Thanks in advance!

**Comment by mnadalc** [comment]
I'm closing the issue as retrying again after waiting for a few minutes I have managed to get the response successfully. 🎉

**Comment by redox** [comment]
Great to hear, you might have been rate-limited while re-trying in loop.
