### ISSUE TITLE
Get price history

### ISSUE THREAD

**Issue by adwulfran** [sorare/api#8]
Hello,

1)Is it possible to get  price history of one card with this API ? 
2) Is it possible to get price history of one card on ethereum blockchain explorer ?

Thanks for reading

**Comment by Vinedine** [comment]
I can only answer the first question; Yes it is look at the object _userOwnersWithRate_

![image](https://user-images.githubusercontent.com/19403380/111807750-94bfb200-88d3-11eb-99ab-f2c59ee077f6.png)

**Comment by redox** [comment]
Yes correct @Vinedine , you can for instance use:

```gql
{
  card(slug: "kylian-mbappe-lottin-2021-rare-4") {
    userOwnersWithRate {
      price
      from
    }
  }
}
```
