### ISSUE TITLE
Calculation of the Supply and Averages for a player

### ISSUE THREAD

**Issue by arik555** [sorare/api#80]
How can I achieve this?
Screenshot: https://prnt.sc/25ypjhf

**Comment by redox** [comment]
Unfortunately, this is not something the Sorare API will be able to deliver. We recommend you to build your own database of historical values, subscribing to the `aCardWasUpdated` GraphQL event & storing each values. All bids & sales are triggering this event.

**Comment by arik555** [comment]
Hello,
@redox 
Please write an example of how we can use the subscription event. Because many are not able to get it correctly, few of them facing errors, etc.

Best.

**Comment by redox** [comment]
> Hello, @redox Please write an example of how we can use the subscription event. Because many are not able to get it correctly, few of them facing errors, etc.

Yes, I'm currently working on this.

**Comment by redox** [comment]
@arik555 would love your feedback on https://github.com/sorare/api/pull/84

**Comment by redox** [comment]
@arik555 @bash-bash would love your feedback on https://github.com/sorare/api/pull/84
