### ISSUE TITLE
Country code ISO-1 not implemented 

### ISSUE THREAD

**Issue by MarvinStakeholder** [sorare/api#86]
Countries codes are not referenced, for example "FR" or "FRA" for France are not working well. 
Getting Country(code=FR) not found"

From this simple query : 

query countrycheck {
  country(slug: "FR") {
    subscriptionsCount
  }
}

**Comment by redox** [comment]
The `slug` is the `code`, which is a ISO 3166-1 country code. It must be lowercase.

```gql
query countrycheck {
  country(slug: "fr") {
    subscriptionsCount
  }
}
```

This works ^. Did I miss something?

**Comment by MarvinStakeholder** [comment]
oups I feel really sorry. 
My bad, thanks for the quick answer
