### ISSUE TITLE
How to get list of all managers and their information, through GraphQL API?

### ISSUE THREAD

**Issue by arik555** [sorare/api#87]
- How to get the list of all available managers in sorare?
- How to get the manager information and history?

**Comment by redox** [comment]
> * How to get the list of all available managers in sorare?

There is no way to iterate over all managers with the API, this isn't really what it's designed for. You could iterate over all cards and collect all user slugs:

```gql
query {
  allCards {
    nodes {
      user {
        slug
      }
    }
  }
}
```


> * How to get the manager information and history?

Then you can use the `user` query to get some information (including auction & directoffer infos) for each of them:

```gql
query {
  user(slug: "pique-d4f1c325-c331-4c06-9bf8-20fa4bd568ca") {
    slug
    nickname
    profile {
      clubName
    }
    createdAt
    cardsCount
    followersCount
    boughtSingleSaleOffers {
      nodes {
        card {
          slug
        }
        price
        acceptedAt
      }
    }
    wonEnglishAuctions{
      nodes {
        cards {
          slug
        }
        currentPrice
      }
    }
  }
}
```

**Comment by redox** [comment]
We're also working on #64 to add more filtering capabilities to `allCards`.
