### ISSUE TITLE
Last x so5scores of player

### ISSUE THREAD

**Issue by nvsk89** [sorare/api#89]
Hi all, 

Sorry for being such a newb, but, is there a way to get so5scores for the last x GW of a given player ?
If yes, would there be a way to query such data for all the existing players in order to have an exhaustive table ?

Many thanks

**Comment by nvsk89** [comment]
I close the issue because I managed to solve it.

**Comment by redox** [comment]
Hi @nvsk89 , thank you for your issue. Do you mind sharing here the query you're using so that the community can learn from your experience?
