### ISSUE TITLE
Question about Contestants usage

### ISSUE THREAD

**Issue by Matbtz** [sorare/api#92]
Hello, 

I have a question  regarding the use of "contestants". I would like to retrieve all player information of all a user cards and also their upcoming games. I can retrieve the name of the Away team and Home team just fine, even though I'm using depreciated functions since I don't get how to use AwayTeam/HomeTeam with the Union...

However I cannot find a way to retrieve the rank of each team for the upcoming matches.
Indeed it seems that we cannot use contestants within a game lists : 
_"Selecting `contestants` within a list of `Game` (`domesticLeague`) is not supported, please select `contestants` for a specific `Game` instead.",_

Thus i'm not sure how I can solve my need, do you have any suggestion to retrieve the information without the need to launch a second parallel query only for rankings ? 

Feel free to cancel this ticket if this is not the appropriate channel.

```
{user(slug: "matbtz") {
      paginatedCards(after: null) {
        nodes {u23Eligible
          rarity
          position
          power
          player{
            displayName
            status{
              playingStatus
              lastFiveSo5Appearances
              lastFiveSo5AverageScore
              lastFifteenSo5Appearances
              lastFifteenSo5AverageScore
              }
            allSo5Scores(first:5){
              nodes{
                score
                }
              }
            activeClub{
                domesticLeague{displayName}
                name
                upcomingGames(first:3){
                  so5Fixture{gameWeek}
                  away{
                    name
                  }
                  home{name}
                }
              }
            }
        }
        pageInfo {
          endCursor
        }
      }
    }
  }
```

Best regards, 

Mathieu

**Comment by redox** [comment]
Hi @Matbtz ,

> "Selecting `contestants` within a list of `Game` (`domesticLeague`) is not supported, please select `contestants` for a specific `Game` instead.",

This is a limitation we've added in order to ensure the complexity of the queries is not too high and the API not abused. What it means is that you cannot get the `contestants` while getting a list of `games`: you first need to get all games with 1 query, then do 1 query per game you want to get get the contestants from.

First get the list of games:

```gql
{
  user(slug: "matbtz") {
    paginatedCards(after: null) {
      nodes {
        u23Eligible
        rarity
        position
        power
        player {
          displayName
          status {
            playingStatus
            lastFiveSo5Appearances
            lastFiveSo5AverageScore
            lastFifteenSo5Appearances
            lastFifteenSo5AverageScore
          }
          allSo5Scores(first: 5) {
            nodes {
              score
            }
          }
          activeClub {
            domesticLeague {
              displayName
            }
            name
            upcomingGames(first: 3) {
              id # <============ only select their ID
            }
          }
        }
      }
      pageInfo {
        endCursor
      }
    }
  }
}
```

and then for each game:

```gql
{
  game(id: "44b34aea-2399-45e1-9ec1-dc5aeb36cc6c") {  # <=== run 1 query per ID
    competition {
      contestants(seasonStartYear: 2021) {
        id
        matchesWon
        matchesLost
        matchesDrawn
        matchesPlayed
        team {
          __typename
          ... on Club {
            name
          }
          ... on NationalTeam {
            name
          }
        }
      }
    }
  }
}
```

> I can retrieve the name of the Away team and Home team just fine, even though I'm using depreciated functions since I don't get how to use AwayTeam/HomeTeam with the Union...

You need to use this syntax to handle the union:

```gql
      team {
          __typename
          ... on Club {
            name
          }
          ... on NationalTeam {
            name
          }
        }

```



> Feel free to cancel this ticket if this is not the appropriate channel.

It's the right channel! Closing for now but feel free to let me know if I missed something.
