### ISSUE TITLE
Websocket subscription auth error

### ISSUE THREAD

**Issue by arctcpk** [sorare/api#96]
Hi all. I've been successfully using the aCardWasUpdated subscription via the Python websocket-client for a while now. Starting today, I'm always receiving an auth error and no card data:

```
Jan 26 08:07:10 PM  ++Rcv raw: b'\x88\x0c\x03\xf3Auth Error'
Jan 26 08:07:10 PM  DEBUG    [2022-01-26 19:07:10,057] websocket: ++Rcv raw: b'\x88\x0c\x03\xf3Auth Error'
Jan 26 08:07:10 PM  ++Rcv decoded: fin=1 opcode=8 data=b'\x03\xf3Auth Error'
Jan 26 08:07:10 PM  DEBUG    [2022-01-26 19:07:10,057] websocket: ++Rcv decoded: fin=1 opcode=8 data=b'\x03\xf3Auth Error'
```

I've not used any authentication in the websockets subscription in the past (which, again, worked successfully with no issues at all). After seeing this issue, I did try submitting the `APIKEY` and `Authorization` headers, but no change, same error.

Has anyone run into this issue? Any idea what might go on?

**Comment by redox** [comment]
We have some ongoing problems with the websockets, the team is working on it; should be back up soon.

**Comment by redox** [comment]
Should be good now. Sorry about this @arctcpk , a dependency update caused this issue.
