### ISSUE TITLE
currentUser null after successful authentication

### ISSUE THREAD

**Issue by githubLewis** [sorare/api#97]
I have some code that has been working fine for a while but has recently (~13th) started returning null for the currentUser. I'm successfully authenticating as I get a token which I subsequently use in my calls. 

My query is valid (validates in Playground) and when testing in code, Playground or Postman everything seems to work - the call is returning a statusCode of 200 for example but I never get the currentUser.

Has something changed recently that would cause this behaviour? Not sure if its coincidence but this problem seems to have started happening around the same time as some of the Graph changes (cards -> paginatedCards).

**Comment by redox** [comment]
Hey @githubLewis ,

thanks for reporting this. Do you mind sharing the graphQL you're using? With a `JWT` or an OAuth tokens I'm successfully able to query `currentUser` and get my nickname and email.

```bash
curl 'https://api.sorare.com/graphql' \
-H 'content-type: application/json' \
-H 'Authorization: Bearer **********' \
-d '{
    "query": "query CurrentUserQuery { currentUser { slug } }"
}'
```

and

```bash
curl 'https://api.sorare.com/graphql'
-H 'content-type: application/json' \
-H 'Authorization: Bearer **********' \
-H 'JWT-AUD: myapp' \
-d '{
    "query": "query CurrentUserQuery { currentUser { slug email } }"
}'
```

Both work

**Comment by githubLewis** [comment]
Hey @redox ,

So to keep it simple, I just tried your examples and neither work for me;

`curl -X POST -H "Content-Type: application/json; charset=utf-8" -H "Authorization: Bearer ******" -H "JWT-AUD: ******" "https://api.sorare.com/graphql" -d "{\"query\":\"query CurrentUserQuery { currentUser { slug } }\"}"`

returns
`{"data":{"currentUser":null}}`

with a status of 200. 

I should also mention that this has been tested on different machines (local & hosted) and both exhibit the same behaviour, so I don't think I'm being blocked via IP (which has happened before). My only other theory is its related to my account - adding\removing my API_Key doesn't make any difference.

**Comment by djizus** [comment]
Hello,

I have the exact same issue. 
The sign in mutation works well, I get the token but the CurrentUserQuery just doesn't work, it always returns {"data": {"currentUser": null}}. 
I've tried the curl requests posted and have the same message. I've tried several machines as well and it doesnt change a thing.

**Comment by redox** [comment]
I really don't get what could happen :/ Could you both share with me your Sorare slug?

**Comment by djizus** [comment]
My slug is "djizus". Thanks for looking into it !

**Comment by redox** [comment]
> My slug is "djizus". Thanks for looking into it !

Crazy, I don't see anything obvious. You confirm the signInMutation goes through, right? Especially: **for accounts with 2FA you need to submit the `optAttempt` after sending the user/password**, otherwise the `currentUser` will be null.

**Comment by githubLewis** [comment]
Hey, slug is "Saint_LC". My code logs in & gets a token, so the mutation\otp challenge appears to be working.

As mentioned previously, this code was working fine but  will review my code & verify this afternoon.

**Comment by djizus** [comment]
> Crazy, I don't see anything obvious. You confirm the signInMutation goes through, right? Especially: **for accounts with 2FA you need to submit the `optAttempt` after sending the user/password**, otherwise the `currentUser` will be null.

I found the issue, it wasn't with the 2FA but with my JWT-AUD value within the signInMutation apparently. I've changed it to a new one, changed the value in my header request and it now works :
`2022-02-01 13:36:58,003 <<< {"data":{"currentUser":{"slug":"djizus"}}}`

Thanks for your time, hope this can help @githubLewis too !

**Comment by githubLewis** [comment]
Hey,

Similar fix for me - although in my code, the JWT-AUD value passed in the signInMutation was different than the value I was passing in the headers. Once these matched (I used a new value) my current user came back correctly;

```
{
    "data": {
        "currentUser": {
            "slug": "saint_lc"
        }
    }
}
```

Good find @djizus 👍

**Comment by redox** [comment]
Oh nice :) Well, maybe this is something we can improve; I'll check whether we have a way to fail more aggressively.

**Comment by redox** [comment]
The API should now fail if the `aud` is not set, instead of 200 with `null`.
