### ISSUE TITLE
Player missing

### ISSUE THREAD

**Issue by ziruzavar** [sorare/api#98]
I am trying to collect teams from MLS and their players and their cards respectively. For example I want to collect all the players from: slug:"philadelphia-union-chester-pennsylvania" Philadelphia. When I collected them, I found out that Kai Wagner is missing, so I searched him slug:"kai-wagner' , he was there, he has activeClub: "Philadelphia" ,but his cards doesn't have team (it returns empty {}), Then I tried with slug:"paxten-aaronson" who appears in Philadelphia players and he returns the same results as Kai. How is this possible, two players from the same team, but one of them can't be found from the club request.
![Screenshot 2022-01-31 141936](https://user-images.githubusercontent.com/21009509/151792858-48bc6da7-db97-4cd6-9df3-10e2862f8580.png)
![Screenshot 2022-01-31 141951](https://user-images.githubusercontent.com/21009509/151792868-bb72aa83-9e82-4013-a1a1-cdeadcdda537.png)

**Comment by redox** [comment]
Hello @ziruzavar,

the `team` attribute is a GraphQL union, so to query the team you need to handle the case of the team being a `Club` or a `NationalTeam`:

```gql
query {
  player(slug: "kai-wagner") {
    age
    displayName
    activeClub {
      name
    }
    cards {
      nodes {
        name
        team {
          __typename
          ... on Club {
            name
          }
          ... on NationalTeam {
            name
          }
        }
      }
    }
  }
}
```

![image](https://user-images.githubusercontent.com/29529/151878270-e6083959-e1e8-4c0f-a201-91b32f4b6379.png)

The difference with **paxten-aaronson** is that Paxten plays in the national team:

```gql
query {
  player(slug: "paxten-aaronson") {
    age
    displayName
    activeClub {
      name
    }
    activeNationalTeam {
      name
    }
    cards {
      nodes {
        name
        team {
          __typename
          ... on Club {
            name
          }
          ... on NationalTeam {
            name
          }
        }
      }
    }
  }
}
```

![image](https://user-images.githubusercontent.com/29529/151878442-12efbd11-7769-4aa8-a63d-f67dd1282d8e.png)

Hope it helps! Closing this.

**Comment by ziruzavar** [comment]
Thanks for clarifying this, but my question is why can't I see Kai Wagner in Philadelphia's players.
![Screenshot 2022-02-01 102523](https://user-images.githubusercontent.com/21009509/151935046-3a704742-f8c0-42e0-ba3b-c452096a632f.png)

**Comment by redox** [comment]
Oh this is just because you didn't go to the next page (`players` is paginated) and there are more than 100 players.

You need to do:

```gql
query {
  club(slug: "philadelphia-union-chester-pennsylvania") {
    players(after: null) {
      nodes {
        displayName
        slug
      }
      pageInfo {
        endCursor
      }
    }
  }
}
```

Get the `endCursor` (in my case `WyJSb3dlIiwiNGMyMjc0ZjctODcwYi00MmY2LWFhNGItZmRmZjcxNTA1ZTRiIl0`) and then go to the 2nd page:

```gql
query {
  club(slug: "philadelphia-union-chester-pennsylvania") {
    players(after: "WyJSb3dlIiwiNGMyMjc0ZjctODcwYi00MmY2LWFhNGItZmRmZjcxNTA1ZTRiIl0") {
      nodes {
        displayName
        slug
      }
      pageInfo {
        endCursor
      }
    }
  }
}
```

And you'll see Kai Wagner is there.
