### ISSUE TITLE
Delay on singleSaleOffers (Can't get data instantly)

### ISSUE THREAD

**Issue by asilbalaban** [sorare/api#99]
`
        query ListLast10SingleSaleOffers {
          transferMarket {
            singleSaleOffers(last: 10) {
              nodes {
                id
                price
                card {
                  slug
                }
                price
              }
            }
          }
        }
`

The data coming with this query is delayed by 8-10 minutes. Why can't we get instant data? is there a conscious restriction on this issue?

**Comment by redox** [comment]
Hello @asilbalaban ,

> The data coming with this query is delayed by 8-10 minutes.

Well, that seems off. We have some caching mechanism but we're speaking 30 seconds. What do you use to confirm this 8-10 minutes delay? Can you show me an example of data you receive and how you interpret it?

**Comment by asilbalaban** [comment]
`query ListLast10SingleSaleOffers { transferMarket { singleSaleOffers(last: 10) { nodes { id price card { slug } price } } } }`

I run this query on https://api.sorare.com/graphql/playground or my client to get last 10 result. 
And when I check these results, I usually see that there are cards that were opened for sale at least 7-8 minutes ago.

However if i run this query without (last: 10) filter;

``query ListLast10SingleSaleOffers { transferMarket { singleSaleOffers { nodes { id price card { slug } price } } } }``

Now i get 50 results but this sales start from 20 - 40 seconds ago.

**Comment by redox** [comment]
Oh got it @asilbalaban . Actually the `singleSaleOffers` is sorted by `date DESC` so in order to get the latest one; you should use `singleSaleOffers(first: 10)` (not `last:`) -> this should give you what you need. Does that make sense?

**Comment by asilbalaban** [comment]
I did not notice that. Sorry about it.
